"""Fetch the prebuilt `aarch64-apple-ios-sim` ONNX Runtime static lib.

This is the SAME artifact ort-sys's `download-binaries` grabs for the simulator
slice (its `build/download/dist.txt`, `ms@1.23.2`) — i.e. the same binary the
`boltffi pack apple` release already ships in the `ios-arm64-simulator` slice.
We fetch + extract it hermetically at repo-fetch time instead of:

  - vendoring another ~74 MiB `.a` into git (the device slice already costs
    that; this keeps the natives strategy pointed at fetch-not-commit), or
  - letting a build action download it (Bazel's action sandbox blocks network;
    only repository rules may reach out).

The device slice stays committed under `vendor/ort-ios/` (proven by G1-G3); this
only ADDS the simulator slice, so the proven device path is untouched.

Format note: pyke ships a raw-LZMA2 stream inside `.tar.lzma2` (magic
`e4 29 db ff`, NOT an xz container `fd 37 7a`), so Bazel's own
`download_and_extract` can't read it. ort-sys decodes it with
`lzma_rust2::Lzma2Reader::new(reader, 1 << 26, None)` — raw LZMA2, 64 MiB dict,
no preset. Host `xz --format=raw --lzma2=dict=64MiB` reproduces exactly that,
so we decode to a plain `.tar` and let Bazel extract it. The ios-sim slice is
only ever built under `--config=ios` on a Mac, where `xz` is present (GitHub
`macos-*` images ship it), so the host-tool dependency is safe here.
"""

# dist.txt row: `none  aarch64-apple-ios-sim  <url>  <sha256>` (ort-sys 2.0.0-rc.11).
_URL = "https://cdn.pyke.io/0/pyke:ort-rs/ms@1.23.2/aarch64-apple-ios-sim.tar.lzma2"
_SHA256 = "8ae2dfc164b21d0a9f7b8ad046193eb20b4e9c198a21ba8dba0a71e962e15776"

# ort-sys's Lzma2Reader(1 << 26) = 64 MiB decode dict; the decoder dict must be
# >= the encoder's, and 64 MiB fully decodes the artifact (verified).
_LZMA2_DICT = "64MiB"

_BUILD_FILE = """\
# Generated by //bazel:ort_ios_sim.bzl — the pyke aarch64-apple-ios-sim slice.
# `lib` is the DIRECTORY handed to ort-sys via ORT_LIB_LOCATION (see MODULE.bazel);
# it must contain `libonnxruntime.a` at its root, exactly like the committed
# device slice's `ios-arm64/` dir.
filegroup(
    name = "lib",
    srcs = ["libonnxruntime.a"],
    visibility = ["//visibility:public"],
)
"""

def _emit_placeholder(ctx):
    # An empty libonnxruntime.a keeps @ort_ios_arm64_sim//:lib resolvable without
    # a download. It is only ever staged as an input-only `data` entry on builds
    # that never link the simulator slice, so its contents are never read.
    ctx.file("libonnxruntime.a", "", executable = False)
    ctx.file("BUILD.bazel", _BUILD_FILE, executable = False)

def _ort_ios_sim_impl(ctx):
    # This repo is referenced from the ort-sys annotation's UNCONDITIONAL `data`
    # (crate.annotation has no per-triple `data`, and a select() branch still
    # loads its label), so the rule is evaluated on EVERY build — including Linux
    # RBE and the windows-gnu cross, which never touch the iOS simulator. Only
    # actually fetch on macOS (where the sim slice is built); elsewhere emit an
    # empty placeholder so no 74 MiB download or `xz` dependency is imposed on
    # non-Apple builds (which may run in minimal containers without `xz`).
    if not ctx.os.name.startswith("mac"):
        _emit_placeholder(ctx)
        return

    xz = ctx.which("xz")
    if xz == None:
        # On macOS but `xz` is missing: DON'T fail the fetch — that would break
        # unrelated desktop/macOS builds that merely reference this repo. Warn and
        # emit the placeholder; a real iOS-simulator build then fails later at the
        # onnxruntime link, with this warning already pointing at the cause.
        # buildifier: disable=print
        print("WARNING: `xz` not found on PATH — the iOS-simulator ONNX Runtime " +
              "slice was NOT fetched. Run `brew install xz` to build the simulator " +
              "slice (`bazel build --config=ios //bindings/apple:XybridFFI`).")
        _emit_placeholder(ctx)
        return

    ctx.download(
        url = _URL,
        sha256 = _SHA256,
        output = "ort.tar.lzma2",
    )

    # Raw LZMA2 -> plain tar, then let Bazel extract (portable, no host `tar`).
    res = ctx.execute(
        [
            "bash",
            "-c",
            "'{xz}' -dc --format=raw --lzma2=dict={dict} ort.tar.lzma2 > ort.tar".format(
                xz = xz,
                dict = _LZMA2_DICT,
            ),
        ],
        timeout = 300,
    )
    if res.return_code != 0:
        fail("failed to decode ONNX Runtime ios-sim archive with xz: {}".format(res.stderr))

    ctx.extract(archive = "ort.tar")
    if not ctx.path("libonnxruntime.a").exists:
        fail("libonnxruntime.a missing after extracting the ort ios-sim archive")

    ctx.delete("ort.tar.lzma2")
    ctx.delete("ort.tar")
    ctx.file("BUILD.bazel", _BUILD_FILE, executable = False)

ort_ios_sim_repository = repository_rule(
    implementation = _ort_ios_sim_impl,
    doc = "Fetches + extracts the pyke aarch64-apple-ios-sim ONNX Runtime static lib.",
)
