// Auto-generated by BoltFFI. Do not edit.
// swiftlint:disable all
// swiftformat:disable all

import Foundation
import XybridFFI
typealias BoltFFICallbackHandle = XybridFFI.BoltFFICallbackHandle

public struct FfiError: Error {
    public let message: String
    public init(message: String) { self.message = message }
    public init(fromC c: XybridFFI.FfiError) {
        self.message = stringFromFfi(c.message)
    }
}

/// Single metadata key/value entry. BoltFFI doesn't auto-derive
/// `WireEncode` for `HashMap<String, String>`, so we expose metadata as
/// `Vec<XybridMetadataEntry>`. The conversion back to `HashMap` happens
/// at the facade boundary inside [`XybridEnvelope::into`].
public struct XybridMetadataEntry: Hashable, Equatable, Sendable {
    public var key: String
    public var value: String

    public init(key: String, value: String) {
        self.key = key
        self.value = value
    }

}

extension XybridMetadataEntry: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> XybridMetadataEntry {
        XybridMetadataEntry(key: reader.readString(), value: reader.readString())
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeString(self.key)
        writer.writeString(self.value)
    }
}

public struct XybridEnvelope: Hashable, Equatable, Sendable {
    public var kind: XybridEnvelopeKind
    public var metadata: [XybridMetadataEntry]

    public init(kind: XybridEnvelopeKind, metadata: [XybridMetadataEntry]) {
        self.kind = kind
        self.metadata = metadata
    }

}

extension XybridEnvelope: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> XybridEnvelope {
        XybridEnvelope(kind: XybridEnvelopeKind.decode(from: &reader), metadata: reader.readArray { reader in XybridMetadataEntry.decode(from: &reader) })
    }
    @inlinable func encode(to writer: inout WireWriter) {
        self.kind.encode(to: &writer)
        writer.writeArray(self.metadata) { writer, item in item.encode(to: &writer) }
    }
}

public struct XybridGenerationConfig: Hashable, Equatable, Sendable {
    public var maxTokens: UInt32?
    public var temperature: Float?
    public var topP: Float?
    public var minP: Float?
    public var topK: UInt32?
    public var repetitionPenalty: Float?
    public var stopSequences: [String]

    public init(maxTokens: UInt32? = nil, temperature: Float? = nil, topP: Float? = nil, minP: Float? = nil, topK: UInt32? = nil, repetitionPenalty: Float? = nil, stopSequences: [String]) {
        self.maxTokens = maxTokens
        self.temperature = temperature
        self.topP = topP
        self.minP = minP
        self.topK = topK
        self.repetitionPenalty = repetitionPenalty
        self.stopSequences = stopSequences
    }

}

extension XybridGenerationConfig: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> XybridGenerationConfig {
        XybridGenerationConfig(maxTokens: reader.readOptional { reader in reader.readU32() }, temperature: reader.readOptional { reader in reader.readF32() }, topP: reader.readOptional { reader in reader.readF32() }, minP: reader.readOptional { reader in reader.readF32() }, topK: reader.readOptional { reader in reader.readU32() }, repetitionPenalty: reader.readOptional { reader in reader.readF32() }, stopSequences: reader.readArray { reader in reader.readString() })
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeOptional(self.maxTokens) { writer, v in writer.writeU32(v) }
        writer.writeOptional(self.temperature) { writer, v in writer.writeF32(v) }
        writer.writeOptional(self.topP) { writer, v in writer.writeF32(v) }
        writer.writeOptional(self.minP) { writer, v in writer.writeF32(v) }
        writer.writeOptional(self.topK) { writer, v in writer.writeU32(v) }
        writer.writeOptional(self.repetitionPenalty) { writer, v in writer.writeF32(v) }
        writer.writeArray(self.stopSequences) { writer, item in writer.writeString(item) }
    }
}

public struct XybridRunOptions: Hashable, Equatable, Sendable {
    public var generationConfig: XybridGenerationConfig?
    public var abortOn: [XybridAbortSignal]
    public var fallbackToCloud: Bool
    public var maxGraceTokens: UInt32
    public var correlationId: String?

    public init(generationConfig: XybridGenerationConfig? = nil, abortOn: [XybridAbortSignal], fallbackToCloud: Bool, maxGraceTokens: UInt32, correlationId: String? = nil) {
        self.generationConfig = generationConfig
        self.abortOn = abortOn
        self.fallbackToCloud = fallbackToCloud
        self.maxGraceTokens = maxGraceTokens
        self.correlationId = correlationId
    }

}

extension XybridRunOptions: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> XybridRunOptions {
        XybridRunOptions(generationConfig: reader.readOptional { reader in XybridGenerationConfig.decode(from: &reader) }, abortOn: reader.readArray { reader in XybridAbortSignal(wireTag: reader.readI32()) }, fallbackToCloud: reader.readBool(), maxGraceTokens: reader.readU32(), correlationId: reader.readOptional { reader in reader.readString() })
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeOptional(self.generationConfig) { writer, v in v.encode(to: &writer) }
        writer.writeArray(self.abortOn) { writer, item in writer.writeI32(item.wireTag) }
        writer.writeBool(self.fallbackToCloud)
        writer.writeU32(self.maxGraceTokens)
        writer.writeOptional(self.correlationId) { writer, v in writer.writeString(v) }
    }
}

public struct XybridStageLatency: Hashable, Equatable, Sendable {
    public var stageId: String
    public var latencyMs: UInt32

    public init(stageId: String, latencyMs: UInt32) {
        self.stageId = stageId
        self.latencyMs = latencyMs
    }

}

extension XybridStageLatency: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> XybridStageLatency {
        XybridStageLatency(stageId: reader.readString(), latencyMs: reader.readU32())
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeString(self.stageId)
        writer.writeU32(self.latencyMs)
    }
}

public struct XybridInferenceMetrics: Hashable, Equatable, Sendable {
    public var totalMs: UInt32
    public var ttftMs: UInt32?
    public var tokensPerSecond: Float?
    public var prefillTps: Float?
    public var decodeTps: Float?
    public var tokensOut: UInt32?
    public var stageLatenciesMs: [XybridStageLatency]

    public init(totalMs: UInt32, ttftMs: UInt32? = nil, tokensPerSecond: Float? = nil, prefillTps: Float? = nil, decodeTps: Float? = nil, tokensOut: UInt32? = nil, stageLatenciesMs: [XybridStageLatency]) {
        self.totalMs = totalMs
        self.ttftMs = ttftMs
        self.tokensPerSecond = tokensPerSecond
        self.prefillTps = prefillTps
        self.decodeTps = decodeTps
        self.tokensOut = tokensOut
        self.stageLatenciesMs = stageLatenciesMs
    }

}

extension XybridInferenceMetrics: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> XybridInferenceMetrics {
        XybridInferenceMetrics(totalMs: reader.readU32(), ttftMs: reader.readOptional { reader in reader.readU32() }, tokensPerSecond: reader.readOptional { reader in reader.readF32() }, prefillTps: reader.readOptional { reader in reader.readF32() }, decodeTps: reader.readOptional { reader in reader.readF32() }, tokensOut: reader.readOptional { reader in reader.readU32() }, stageLatenciesMs: reader.readArray { reader in XybridStageLatency.decode(from: &reader) })
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeU32(self.totalMs)
        writer.writeOptional(self.ttftMs) { writer, v in writer.writeU32(v) }
        writer.writeOptional(self.tokensPerSecond) { writer, v in writer.writeF32(v) }
        writer.writeOptional(self.prefillTps) { writer, v in writer.writeF32(v) }
        writer.writeOptional(self.decodeTps) { writer, v in writer.writeF32(v) }
        writer.writeOptional(self.tokensOut) { writer, v in writer.writeU32(v) }
        writer.writeArray(self.stageLatenciesMs) { writer, item in item.encode(to: &writer) }
    }
}

/// Inference output. Named `XybridResult` (not `XybridInferenceResult`)
/// to match the existing uniffi-generated Kotlin/Swift name — the iOS
/// example references `XybridResult` directly.
public struct XybridResult: Hashable, Equatable, Sendable {
    public var envelope: XybridEnvelope
    public var outputType: XybridOutputType
    public var modelId: String
    public var latencyMs: UInt32
    public var metrics: XybridInferenceMetrics

    public init(envelope: XybridEnvelope, outputType: XybridOutputType, modelId: String, latencyMs: UInt32, metrics: XybridInferenceMetrics) {
        self.envelope = envelope
        self.outputType = outputType
        self.modelId = modelId
        self.latencyMs = latencyMs
        self.metrics = metrics
    }

}

extension XybridResult: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> XybridResult {
        XybridResult(envelope: XybridEnvelope.decode(from: &reader), outputType: XybridOutputType(wireTag: reader.readI32()), modelId: reader.readString(), latencyMs: reader.readU32(), metrics: XybridInferenceMetrics.decode(from: &reader))
    }
    @inlinable func encode(to writer: inout WireWriter) {
        self.envelope.encode(to: &writer)
        writer.writeI32(self.outputType.wireTag)
        writer.writeString(self.modelId)
        writer.writeU32(self.latencyMs)
        self.metrics.encode(to: &writer)
    }
}

public struct XybridVoiceInfo: Hashable, Equatable, Sendable {
    public var id: String
    public var name: String
    public var gender: String?
    public var language: String?
    public var style: String?

    public init(id: String, name: String, gender: String? = nil, language: String? = nil, style: String? = nil) {
        self.id = id
        self.name = name
        self.gender = gender
        self.language = language
        self.style = style
    }

}

extension XybridVoiceInfo: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> XybridVoiceInfo {
        XybridVoiceInfo(id: reader.readString(), name: reader.readString(), gender: reader.readOptional { reader in reader.readString() }, language: reader.readOptional { reader in reader.readString() }, style: reader.readOptional { reader in reader.readString() })
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeString(self.id)
        writer.writeString(self.name)
        writer.writeOptional(self.gender) { writer, v in writer.writeString(v) }
        writer.writeOptional(self.language) { writer, v in writer.writeString(v) }
        writer.writeOptional(self.style) { writer, v in writer.writeString(v) }
    }
}

/// Errors surfaced across the FFI boundary. Variants mirror
/// [`facade::Error`] — the facade owns the SDK→FFI translation; this enum
/// only re-decorates it for the BoltFFI generator (proc macros must live
/// on the type definition).
///
/// Named `XybridError` (not `Error`) so the emitted Swift type doesn't
/// shadow / collide with Swift's stdlib `Error` protocol, and so the
/// Kotlin sealed-hierarchy name matches the existing uniffi consumer
/// expectations.
///
/// **Variant order is part of the wire contract.** BoltFFI encodes `#[error]`
/// (and `#[data]`) enums by ordinal tag, so reordering or inserting a variant
/// renumbers every variant after it and breaks already-built foreign clients.
/// Only ever append at the tail, and keep this order in lockstep with
/// [`facade::Error`] and its `code()` table.
public enum XybridError: Hashable, Equatable, Sendable, Error {
    case modelNotFound(id: String)
    case directoryNotFound(path: String)
    case metadataNotFound(path: String)
    case metadataInvalid(message: String)
    case loadError(message: String)
    case inferenceError(message: String)
    case abortedForCloudFallback(reason: String)
    case streamingNotSupported
    case notLoaded
    case configError(message: String)
    case networkError(message: String)
    case offline(message: String)
    case ioError(message: String)
    case cacheError(message: String)
    case pipelineError(message: String)
    case circuitOpen(message: String)
    case rateLimited(retryAfterSecs: UInt64)
    case timeout(timeoutMs: UInt64)
    case missingArtifact(message: String)
    case unsupportedModelCapability(message: String)
    case unsupportedBackendCapability(message: String)
    case invalidImage(message: String)

}

extension XybridError: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> XybridError {
        let tag = reader.readI32()
        switch tag {
        case 0:
            return .modelNotFound(id: reader.readString())
        case 1:
            return .directoryNotFound(path: reader.readString())
        case 2:
            return .metadataNotFound(path: reader.readString())
        case 3:
            return .metadataInvalid(message: reader.readString())
        case 4:
            return .loadError(message: reader.readString())
        case 5:
            return .inferenceError(message: reader.readString())
        case 6:
            return .abortedForCloudFallback(reason: reader.readString())
        case 7:
            return .streamingNotSupported
        case 8:
            return .notLoaded
        case 9:
            return .configError(message: reader.readString())
        case 10:
            return .networkError(message: reader.readString())
        case 11:
            return .offline(message: reader.readString())
        case 12:
            return .ioError(message: reader.readString())
        case 13:
            return .cacheError(message: reader.readString())
        case 14:
            return .pipelineError(message: reader.readString())
        case 15:
            return .circuitOpen(message: reader.readString())
        case 16:
            return .rateLimited(retryAfterSecs: reader.readU64())
        case 17:
            return .timeout(timeoutMs: reader.readU64())
        case 18:
            return .missingArtifact(message: reader.readString())
        case 19:
            return .unsupportedModelCapability(message: reader.readString())
        case 20:
            return .unsupportedBackendCapability(message: reader.readString())
        case 21:
            return .invalidImage(message: reader.readString())
        default:
            fatalError("Invalid XybridError tag: \(tag)")
        }
    }

    @inlinable func encode(to writer: inout WireWriter) {
        switch self {
        case let .modelNotFound(id):
            writer.writeI32(0)
            writer.writeString(id)
        case let .directoryNotFound(path):
            writer.writeI32(1)
            writer.writeString(path)
        case let .metadataNotFound(path):
            writer.writeI32(2)
            writer.writeString(path)
        case let .metadataInvalid(message):
            writer.writeI32(3)
            writer.writeString(message)
        case let .loadError(message):
            writer.writeI32(4)
            writer.writeString(message)
        case let .inferenceError(message):
            writer.writeI32(5)
            writer.writeString(message)
        case let .abortedForCloudFallback(reason):
            writer.writeI32(6)
            writer.writeString(reason)
        case .streamingNotSupported:
            writer.writeI32(7)
        case .notLoaded:
            writer.writeI32(8)
        case let .configError(message):
            writer.writeI32(9)
            writer.writeString(message)
        case let .networkError(message):
            writer.writeI32(10)
            writer.writeString(message)
        case let .offline(message):
            writer.writeI32(11)
            writer.writeString(message)
        case let .ioError(message):
            writer.writeI32(12)
            writer.writeString(message)
        case let .cacheError(message):
            writer.writeI32(13)
            writer.writeString(message)
        case let .pipelineError(message):
            writer.writeI32(14)
            writer.writeString(message)
        case let .circuitOpen(message):
            writer.writeI32(15)
            writer.writeString(message)
        case let .rateLimited(retryAfterSecs):
            writer.writeI32(16)
            writer.writeU64(retryAfterSecs)
        case let .timeout(timeoutMs):
            writer.writeI32(17)
            writer.writeU64(timeoutMs)
        case let .missingArtifact(message):
            writer.writeI32(18)
            writer.writeString(message)
        case let .unsupportedModelCapability(message):
            writer.writeI32(19)
            writer.writeString(message)
        case let .unsupportedBackendCapability(message):
            writer.writeI32(20)
            writer.writeString(message)
        case let .invalidImage(message):
            writer.writeI32(21)
            writer.writeString(message)
        }
    }
}

public enum XybridEnvelopeKind: Hashable, Equatable, Sendable {
    case text(text: String)
    case audio(bytes: Data)
    case embedding(values: [Float])
    case image(bytes: Data, format: String)
    case multiPart(parts: [XybridEnvelope])

}

extension XybridEnvelopeKind: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> XybridEnvelopeKind {
        let tag = reader.readI32()
        switch tag {
        case 0:
            return .text(text: reader.readString())
        case 1:
            return .audio(bytes: reader.readBytes())
        case 2:
            return .embedding(values: reader.readBlittableArray() as [Float])
        case 3:
            return .image(bytes: reader.readBytes(), format: reader.readString())
        case 4:
            return .multiPart(parts: reader.readArray { reader in XybridEnvelope.decode(from: &reader) })
        default:
            fatalError("Invalid XybridEnvelopeKind tag: \(tag)")
        }
    }

    @inlinable func encode(to writer: inout WireWriter) {
        switch self {
        case let .text(text):
            writer.writeI32(0)
            writer.writeString(text)
        case let .audio(bytes):
            writer.writeI32(1)
            writer.writeBytes(bytes)
        case let .embedding(values):
            writer.writeI32(2)
            writer.writeBlittableArray(values)
        case let .image(bytes, format):
            writer.writeI32(3)
            writer.writeBytes(bytes)
            writer.writeString(format)
        case let .multiPart(parts):
            writer.writeI32(4)
            writer.writeArray(parts) { writer, item in item.encode(to: &writer) }
        }
    }
}

public enum XybridMessageRole: Int32, Hashable, Sendable, CaseIterable {
    case system = 0
    case user = 1
    case assistant = 2

    @usableFromInline init(fromC c: Int32) { self = XybridMessageRole(rawValue: c)! }
    @usableFromInline var cValue: Int32 { rawValue }
    @usableFromInline init(wireTag: Int32) {
        switch wireTag {
        case 0: self = .system
        case 1: self = .user
        case 2: self = .assistant
        default: fatalError("Invalid XybridMessageRole wire tag: \(wireTag)")
        }
    }
    @usableFromInline var wireTag: Int32 {
        switch rawValue {
        case 0: return 0
        case 1: return 1
        case 2: return 2
        default: fatalError("Invalid XybridMessageRole raw value: \(rawValue)")
        }
    }

}

extension XybridMessageRole: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> XybridMessageRole { XybridMessageRole(wireTag: reader.readI32()) }
    @inlinable func encode(to writer: inout WireWriter) { writer.writeI32(wireTag) }
}

public enum XybridAbortSignal: Int32, Hashable, Sendable, CaseIterable {
    case memoryPressureWarn = 0
    case memoryPressureCritical = 1
    case thermalHot = 2
    case thermalCritical = 3

    @usableFromInline init(fromC c: Int32) { self = XybridAbortSignal(rawValue: c)! }
    @usableFromInline var cValue: Int32 { rawValue }
    @usableFromInline init(wireTag: Int32) {
        switch wireTag {
        case 0: self = .memoryPressureWarn
        case 1: self = .memoryPressureCritical
        case 2: self = .thermalHot
        case 3: self = .thermalCritical
        default: fatalError("Invalid XybridAbortSignal wire tag: \(wireTag)")
        }
    }
    @usableFromInline var wireTag: Int32 {
        switch rawValue {
        case 0: return 0
        case 1: return 1
        case 2: return 2
        case 3: return 3
        default: fatalError("Invalid XybridAbortSignal raw value: \(rawValue)")
        }
    }

}

extension XybridAbortSignal: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> XybridAbortSignal { XybridAbortSignal(wireTag: reader.readI32()) }
    @inlinable func encode(to writer: inout WireWriter) { writer.writeI32(wireTag) }
}

public enum XybridOutputType: Int32, Hashable, Sendable, CaseIterable {
    case text = 0
    case audio = 1
    case embedding = 2
    case unknown = 3

    @usableFromInline init(fromC c: Int32) { self = XybridOutputType(rawValue: c)! }
    @usableFromInline var cValue: Int32 { rawValue }
    @usableFromInline init(wireTag: Int32) {
        switch wireTag {
        case 0: self = .text
        case 1: self = .audio
        case 2: self = .embedding
        case 3: self = .unknown
        default: fatalError("Invalid XybridOutputType wire tag: \(wireTag)")
        }
    }
    @usableFromInline var wireTag: Int32 {
        switch rawValue {
        case 0: return 0
        case 1: return 1
        case 2: return 2
        case 3: return 3
        default: fatalError("Invalid XybridOutputType raw value: \(rawValue)")
        }
    }

}

extension XybridOutputType: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> XybridOutputType { XybridOutputType(wireTag: reader.readI32()) }
    @inlinable func encode(to writer: inout WireWriter) { writer.writeI32(wireTag) }
}

public enum XybridThermalState: Int32, Hashable, Sendable, CaseIterable {
    case normal = 0
    case warm = 1
    case hot = 2
    case critical = 3

    @usableFromInline init(fromC c: Int32) { self = XybridThermalState(rawValue: c)! }
    @usableFromInline var cValue: Int32 { rawValue }
    @usableFromInline init(wireTag: Int32) {
        switch wireTag {
        case 0: self = .normal
        case 1: self = .warm
        case 2: self = .hot
        case 3: self = .critical
        default: fatalError("Invalid XybridThermalState wire tag: \(wireTag)")
        }
    }
    @usableFromInline var wireTag: Int32 {
        switch rawValue {
        case 0: return 0
        case 1: return 1
        case 2: return 2
        case 3: return 3
        default: fatalError("Invalid XybridThermalState raw value: \(rawValue)")
        }
    }

}

extension XybridThermalState: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> XybridThermalState { XybridThermalState(wireTag: reader.readI32()) }
    @inlinable func encode(to writer: inout WireWriter) { writer.writeI32(wireTag) }
}

public func setThermalState(state: XybridThermalState) {
    boltffi_set_thermal_state(state.rawValue)
}

public func clearThermalState() {
    boltffi_clear_thermal_state()
}

public func setBatteryLevel(percent: UInt8) {
    boltffi_set_battery_level(percent)
}

public func clearBatteryLevel() {
    boltffi_clear_battery_level()
}

/// One-stop SDK initialization: API key + gateway/ingest URL overrides in
/// one call. Delegates to [`facade::configure_runtime`]; blank strings are
/// treated as absent. This is the canonical init the Swift
/// `Xybrid.initialize(apiKey:gatewayUrl:ingestUrl:)` and Kotlin
/// `Xybrid.init(context, apiKey, gatewayUrl, ingestUrl)` wrappers call.
public func configureRuntime(apiKey: String?, gatewayUrl: String?, ingestUrl: String?) {
    let apiKeyBytes = boltffiEncode { writer in writer.writeOptional(apiKey) { writer, v in writer.writeString(v) } }
    let gatewayUrlBytes = boltffiEncode { writer in writer.writeOptional(gatewayUrl) { writer, v in writer.writeString(v) } }
    let ingestUrlBytes = boltffiEncode { writer in writer.writeOptional(ingestUrl) { writer, v in writer.writeString(v) } }
    apiKeyBytes.withUnsafeBufferPointer { apiKeyBuf in
        gatewayUrlBytes.withUnsafeBufferPointer { gatewayUrlBuf in
            ingestUrlBytes.withUnsafeBufferPointer { ingestUrlBuf in
                boltffi_configure_runtime(apiKeyBuf.baseAddress, UInt(apiKeyBuf.count), gatewayUrlBuf.baseAddress, UInt(gatewayUrlBuf.count), ingestUrlBuf.baseAddress, UInt(ingestUrlBuf.count))
            }
        }
    }
}

public func initSdkCacheDir(cacheDir: String) {
    var cacheDir = cacheDir
    cacheDir.withUTF8 { cacheDirBuf in
        boltffi_init_sdk_cache_dir(cacheDirBuf.baseAddress!, UInt(cacheDirBuf.count))
    }
}

public func setBinding(binding: String) {
    var binding = binding
    binding.withUTF8 { bindingBuf in
        boltffi_set_binding(bindingBuf.baseAddress!, UInt(bindingBuf.count))
    }
}

public func setApiKey(apiKey: String) {
    var apiKey = apiKey
    apiKey.withUTF8 { apiKeyBuf in
        boltffi_set_api_key(apiKeyBuf.baseAddress!, UInt(apiKeyBuf.count))
    }
}

public func setProviderApiKey(provider: String, apiKey: String) {
    var provider = provider
    var apiKey = apiKey
    provider.withUTF8 { providerBuf in
        apiKey.withUTF8 { apiKeyBuf in
            boltffi_set_provider_api_key(providerBuf.baseAddress!, UInt(providerBuf.count), apiKeyBuf.baseAddress!, UInt(apiKeyBuf.count))
        }
    }
}

public final class XybridModel {
    let handle: OpaquePointer

    init(handle: OpaquePointer) {
        self.handle = handle
    }

    /// Load from the xybrid registry. Recommended path.
    public convenience init(fromRegistry id: String) throws {
        var id = id
        let ptr = id.withUTF8 { idBuf -> OpaquePointer? in boltffi_xybrid_model_from_registry(idBuf.baseAddress!, UInt(idBuf.count)) }
        guard let ptr = ptr else {
            throw FfiError(message: takeLastErrorMessage())
        }
        self.init(handle: ptr)
    }

    /// Load from a local model directory (must contain `model_metadata.json`).
    public convenience init(fromDirectory path: String) throws {
        var path = path
        let ptr = path.withUTF8 { pathBuf -> OpaquePointer? in boltffi_xybrid_model_from_directory(pathBuf.baseAddress!, UInt(pathBuf.count)) }
        guard let ptr = ptr else {
            throw FfiError(message: takeLastErrorMessage())
        }
        self.init(handle: ptr)
    }

    /// Load from a local `.xyb` bundle.
    public convenience init(fromBundle path: String) throws {
        var path = path
        let ptr = path.withUTF8 { pathBuf -> OpaquePointer? in boltffi_xybrid_model_from_bundle(pathBuf.baseAddress!, UInt(pathBuf.count)) }
        guard let ptr = ptr else {
            throw FfiError(message: takeLastErrorMessage())
        }
        self.init(handle: ptr)
    }

    /// Resolve and load from a HuggingFace repo (`org/repo` or `org/repo:variant`).
    public convenience init(fromHuggingface repo: String) throws {
        var repo = repo
        let ptr = repo.withUTF8 { repoBuf -> OpaquePointer? in boltffi_xybrid_model_from_huggingface(repoBuf.baseAddress!, UInt(repoBuf.count)) }
        guard let ptr = ptr else {
            throw FfiError(message: takeLastErrorMessage())
        }
        self.init(handle: ptr)
    }

    deinit {
        boltffi_xybrid_model_free(handle)
    }

    public func modelId() -> String {
        let buf = boltffi_xybrid_model_model_id(handle)
        defer { boltffi_free_buf(buf) }
        return boltffiDecodeOwnedBuf(buf.ptr, Int(buf.len)) { reader in reader.readString() }
    }

    public func version() -> String {
        let buf = boltffi_xybrid_model_version(handle)
        defer { boltffi_free_buf(buf) }
        return boltffiDecodeOwnedBuf(buf.ptr, Int(buf.len)) { reader in reader.readString() }
    }

    public func outputType() -> XybridOutputType {
        return XybridOutputType(rawValue: boltffi_xybrid_model_output_type(handle))!
    }

    public func isLoaded() -> Bool {
        return boltffi_xybrid_model_is_loaded(handle)
    }

    public func supportsStreaming() -> Bool {
        return boltffi_xybrid_model_supports_streaming(handle)
    }

    public func isLlm() -> Bool {
        return boltffi_xybrid_model_is_llm(handle)
    }

    public func hasVoices() -> Bool {
        return boltffi_xybrid_model_has_voices(handle)
    }

    public func voices() -> [XybridVoiceInfo] {
        let buf = boltffi_xybrid_model_voices(handle)
        defer { boltffi_free_buf(buf) }
        return boltffiDecodeOwnedBuf(buf.ptr, Int(buf.len)) { reader in reader.readArray { reader in XybridVoiceInfo.decode(from: &reader) } }
    }

    public func defaultVoice() -> XybridVoiceInfo? {
        let buf = boltffi_xybrid_model_default_voice(handle)
        defer { boltffi_free_buf(buf) }
        return boltffiDecodeOwnedBuf(buf.ptr, Int(buf.len)) { reader in reader.readOptional { reader in XybridVoiceInfo.decode(from: &reader) } }
    }

    public func voice(voiceId: String) -> XybridVoiceInfo? {
        var voiceId = voiceId
        return voiceId.withUTF8 { voiceIdBuf in
            let buf = boltffi_xybrid_model_voice(handle, voiceIdBuf.baseAddress!, UInt(voiceIdBuf.count))
            defer { boltffi_free_buf(buf) }
            return boltffiDecodeOwnedBuf(buf.ptr, Int(buf.len)) { reader in reader.readOptional { reader in XybridVoiceInfo.decode(from: &reader) } }
        }
    }

    /// Run inference, optionally with [`XybridRunOptions`] (generation config,
    /// abort signals, cloud-fallback). Pass `None` for the model's defaults.
    ///
    /// The hand-written wrappers add a one-arg `run(envelope)` convenience that
    /// forwards `None`, so simple call sites stay ergonomic.
    public func run(envelope: XybridEnvelope, options: XybridRunOptions?) throws -> XybridResult {
        let envelopeBytes = boltffiEncode { writer in envelope.encode(to: &writer) }
        let optionsBytes = boltffiEncode { writer in writer.writeOptional(options) { writer, v in v.encode(to: &writer) } }
        return try envelopeBytes.withUnsafeBufferPointer { envelopeBuf in
            return try optionsBytes.withUnsafeBufferPointer { optionsBuf in
                let buf = boltffi_xybrid_model_run(handle, envelopeBuf.baseAddress, UInt(envelopeBuf.count), optionsBuf.baseAddress, UInt(optionsBuf.count))
                defer { boltffi_free_buf(buf) }
                return try boltffiDecodeOwnedBuf(buf.ptr, Int(buf.len)) { reader in try { let tag = reader.readU8(); if tag == 0 { return XybridResult.decode(from: &reader) } else { throw XybridError.decode(from: &reader) } }() }
            }
        }
    }

    public func warmup() throws {
        let buf = boltffi_xybrid_model_warmup(handle)
        defer { boltffi_free_buf(buf) }
        return try boltffiDecodeOwnedBuf(buf.ptr, Int(buf.len)) { reader in try { let tag = reader.readU8(); if tag == 0 { return () } else { throw XybridError.decode(from: &reader) } }() }
    }

    public func unload() throws {
        let buf = boltffi_xybrid_model_unload(handle)
        defer { boltffi_free_buf(buf) }
        return try boltffiDecodeOwnedBuf(buf.ptr, Int(buf.len)) { reader in try { let tag = reader.readU8(); if tag == 0 { return () } else { throw XybridError.decode(from: &reader) } }() }
    }

}

@inline(__always)
private func stringFromFfi(_ ffiString: FfiString) -> String {
    guard ffiString.len > 0, let pointer = ffiString.ptr else { return "" }
    return String(decoding: UnsafeBufferPointer(start: pointer, count: Int(ffiString.len)), as: UTF8.self)
}

@inline(__always)
private func takeLastErrorMessage() -> String {
    var out = FfiString()
    ensureOk(boltffi_last_error_message(&out))
    defer { boltffi_free_string(out) }
    return stringFromFfi(out)
}

@inline(__always)
private func checkStatus(_ status: FfiStatus, context: StaticString = #function) throws {
    guard status.code == 0 else {
        throw FfiError(message: "FFI failed in \(context) with code \(status.code)")
    }
}

@inline(__always)
private func ensureOk(_ status: FfiStatus, context: StaticString = #function) {
    guard status.code == 0 else {
        fatalError("FFI failed in \(context) [\(status.code)]")
    }
}

@usableFromInline protocol WireCodable {
    static func decode(from reader: inout WireReader) -> Self
    func encode(to writer: inout WireWriter)
}

@usableFromInline struct WireReader {
    @usableFromInline let data: Data
    @usableFromInline var position: Int
    @inlinable init(ptr: UnsafePointer<UInt8>, len: Int) { self.data = Data(bytes: ptr, count: len); self.position = 0 }

    @inlinable mutating func readU8() -> UInt8 { let v = data[position]; position += 1; return v }
    @inlinable mutating func readI8() -> Int8 { Int8(bitPattern: readU8()) }
    @inlinable mutating func readU16() -> UInt16 { let v = data.withUnsafeBytes { $0.loadUnaligned(fromByteOffset: position, as: UInt16.self) }; position += 2; return v }
    @inlinable mutating func readI16() -> Int16 { Int16(bitPattern: readU16()) }
    @inlinable mutating func readU32() -> UInt32 { let v = data.withUnsafeBytes { $0.loadUnaligned(fromByteOffset: position, as: UInt32.self) }; position += 4; return v }
    @inlinable mutating func readI32() -> Int32 { Int32(bitPattern: readU32()) }
    @inlinable mutating func readU64() -> UInt64 { let v = data.withUnsafeBytes { $0.loadUnaligned(fromByteOffset: position, as: UInt64.self) }; position += 8; return v }
    @inlinable mutating func readI64() -> Int64 { Int64(bitPattern: readU64()) }
    @inlinable mutating func readF32() -> Float { Float(bitPattern: readU32()) }
    @inlinable mutating func readF64() -> Double { Double(bitPattern: readU64()) }
    @inlinable mutating func readBool() -> Bool { readU8() != 0 }

    @inlinable mutating func readString() -> String {
        let len = Int(readU32())
        guard len > 0 else { return "" }
        let start = position
        position += len
        return String(decoding: data[start..<(start + len)], as: UTF8.self)
    }

    @inlinable mutating func readBytes() -> Data {
        let len = Int(readU32())
        guard len > 0 else { return Data() }
        let start = position
        position += len
        return data[start..<(start + len)]
    }

    @inlinable mutating func readDuration() -> TimeInterval {
        let seconds = readU64()
        let nanoseconds = readU32()
        return Double(seconds) + (Double(nanoseconds) / 1.0e9)
    }

    @inlinable mutating func readTimestamp() -> Date {
        let seconds = readI64()
        let nanoseconds = readU32()
        let delta = seconds >= 0
            ? (Double(seconds) + (Double(nanoseconds) / 1.0e9))
            : (Double(seconds) - (Double(nanoseconds) / 1.0e9))
        return Date(timeIntervalSince1970: delta)
    }

    @inlinable mutating func readUuid() -> UUID {
        let hi = readU64()
        let lo = readU64()
        var uuid: uuid_t = (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
        var hiBe = hi.bigEndian
        var loBe = lo.bigEndian
        withUnsafeMutableBytes(of: &uuid) { uuidBytes in
            Swift.withUnsafeBytes(of: &hiBe) { uuidBytes[0..<8].copyBytes(from: $0) }
            Swift.withUnsafeBytes(of: &loBe) { uuidBytes[8..<16].copyBytes(from: $0) }
        }
        return UUID(uuid: uuid)
    }

    @inlinable mutating func readUrl() -> URL {
        guard let url = URL(string: readString()) else { fatalError("Invalid URL") }
        return url
    }

    @inlinable mutating func readOptional<T>(_ body: (inout WireReader) -> T) -> T? {
        guard readU8() != 0 else { return nil }
        return body(&self)
    }

    @inlinable mutating func readResultOrThrow<T>(
        ok: (inout WireReader) -> T,
        err: (inout WireReader) -> any Error
    ) throws -> T {
        if readU8() == 0 {
            return ok(&self)
        } else {
            throw err(&self)
        }
    }

    @inlinable mutating func readArray<T>(_ body: (inout WireReader) -> T) -> [T] {
        let count = Int(readU32())
        guard count > 0 else { return [] }
        var result = [T]()
        result.reserveCapacity(count)
        for _ in 0..<count { result.append(body(&self)) }
        return result
    }

    @inlinable mutating func readBlittable<T>() -> T {
        let v = data.withUnsafeBytes { $0.loadUnaligned(fromByteOffset: position, as: T.self) }
        position += MemoryLayout<T>.stride
        return v
    }

    @inlinable mutating func readBlittableArray<T>() -> [T] {
        let count = Int(readU32())
        guard count > 0 else { return [] }
        let byteCount = count * MemoryLayout<T>.stride
        let start = position
        position += byteCount
        return data.withUnsafeBytes { rawBuffer in
            Array<T>(unsafeUninitializedCapacity: count) { buffer, initialized in
                memcpy(buffer.baseAddress!, rawBuffer.baseAddress!.advanced(by: start), byteCount)
                initialized = count
            }
        }
    }

    @inlinable mutating func read<T: WireCodable>() -> T {
        T.decode(from: &self)
    }
}

@usableFromInline struct WireWriter {
    @usableFromInline var bytes: [UInt8]
    @inlinable init() { self.bytes = [] }

    @inlinable mutating func writeU8(_ v: UInt8) { bytes.append(v) }
    @inlinable mutating func writeI8(_ v: Int8) { writeU8(UInt8(bitPattern: v)) }
    @inlinable mutating func writeU16(_ v: UInt16) { var val = v; Swift.withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) } }
    @inlinable mutating func writeI16(_ v: Int16) { writeU16(UInt16(bitPattern: v)) }
    @inlinable mutating func writeU32(_ v: UInt32) { var val = v; Swift.withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) } }
    @inlinable mutating func writeI32(_ v: Int32) { writeU32(UInt32(bitPattern: v)) }
    @inlinable mutating func writeU64(_ v: UInt64) { var val = v; Swift.withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) } }
    @inlinable mutating func writeI64(_ v: Int64) { writeU64(UInt64(bitPattern: v)) }
    @inlinable mutating func writeF32(_ v: Float) { writeU32(v.bitPattern) }
    @inlinable mutating func writeF64(_ v: Double) { writeU64(v.bitPattern) }
    @inlinable mutating func writeBool(_ v: Bool) { writeU8(v ? 1 : 0) }

    @inlinable mutating func writeString(_ v: String) {
        var s = v
        s.withUTF8 { utf8 in
            writeU32(UInt32(utf8.count))
            bytes.append(contentsOf: utf8)
        }
    }

    @inlinable mutating func writeBytes(_ v: Data) {
        writeU32(UInt32(v.count))
        bytes.append(contentsOf: v)
    }

    @inlinable mutating func writeDuration(_ v: TimeInterval) {
        if v.rounded(.down) > Double(Int64.max) { fatalError("Duration overflow") }
        if v < 0 { fatalError("Invalid duration") }
        let seconds = UInt64(v)
        let nanoseconds = UInt32((v - Double(seconds)) * 1.0e9)
        writeU64(seconds)
        writeU32(nanoseconds)
    }

    @inlinable mutating func writeTimestamp(_ v: Date) {
        var delta = v.timeIntervalSince1970
        var sign: Int64 = 1
        if delta < 0 { sign = -1; delta = -delta }
        if delta.rounded(.down) > Double(Int64.max) { fatalError("Timestamp overflow") }
        let seconds = Int64(delta)
        let nanoseconds = UInt32((delta - Double(seconds)) * 1.0e9)
        writeI64(sign * seconds)
        writeU32(nanoseconds)
    }

    @inlinable mutating func writeUuid(_ v: UUID) {
        var uuid = v.uuid
        let (hi, lo) = Swift.withUnsafeBytes(of: &uuid) { raw -> (UInt64, UInt64) in
            let hiBe = raw.loadUnaligned(fromByteOffset: 0, as: UInt64.self)
            let loBe = raw.loadUnaligned(fromByteOffset: 8, as: UInt64.self)
            return (UInt64(bigEndian: hiBe), UInt64(bigEndian: loBe))
        }
        writeU64(hi)
        writeU64(lo)
    }

    @inlinable mutating func writeUrl(_ v: URL) { writeString(v.absoluteString) }

    @inlinable mutating func writeOptional<T>(_ v: T?, _ body: (inout WireWriter, T) -> Void) {
        guard let value = v else { writeU8(0); return }
        writeU8(1)
        body(&self, value)
    }

    @inlinable mutating func writeArray<T>(_ v: [T], _ body: (inout WireWriter, T) -> Void) {
        writeU32(UInt32(v.count))
        for item in v { body(&self, item) }
    }

    @inlinable mutating func writeBlittable<T>(_ value: T) {
        var copy = value
        let size = MemoryLayout<T>.size
        let stride = MemoryLayout<T>.stride
        Swift.withUnsafeBytes(of: &copy) { bytes.append(contentsOf: $0) }
        if stride > size {
            bytes.append(contentsOf: repeatElement(UInt8(0), count: stride - size))
        }
    }

    @inlinable mutating func writeBlittableArray<T>(_ v: [T]) {
        writeU32(UInt32(v.count))
        v.withUnsafeBytes { bytes.append(contentsOf: $0) }
    }

    @inlinable mutating func write<T: WireCodable>(_ v: T) { v.encode(to: &self) }

    @inlinable func finalize() -> [UInt8] { bytes }
}

@inlinable func boltffiInvokeWireCallback(
    _ callback: (@convention(c) (UInt64, UnsafePointer<UInt8>?, UInt, FfiStatus) -> Void)?,
    _ callbackData: UInt64,
    _ encoded: [UInt8],
    _ status: FfiStatus
) {
    encoded.withUnsafeBufferPointer { buf in
        callback?(callbackData, buf.baseAddress, UInt(buf.count), status)
    }
}

@inlinable func boltffiDecodeOwnedBuf<T>(_ ptr: UnsafePointer<UInt8>?, _ len: Int, _ decode: (inout WireReader) -> T) -> T {
    var reader = WireReader(ptr: ptr!, len: len)
    return decode(&reader)
}

@inlinable func boltffiDecodeOwnedBuf<T>(_ ptr: UnsafePointer<UInt8>?, _ len: Int, _ decode: (inout WireReader) throws -> T) throws -> T {
    var reader = WireReader(ptr: ptr!, len: len)
    return try decode(&reader)
}

@discardableResult
@inlinable func boltffiStoreEncodedCallbackResult(
    _ encoded: [UInt8],
    _ outPtr: UnsafeMutablePointer<UnsafeMutablePointer<UInt8>?>?,
    _ outLen: UnsafeMutablePointer<UInt>?
) -> Bool {
    if encoded.isEmpty {
        outPtr?.pointee = nil
        outLen?.pointee = 0
        return true
    }
    guard let allocated = malloc(encoded.count)?.assumingMemoryBound(to: UInt8.self) else {
        return false
    }
    _ = encoded.withUnsafeBytes { bytes in
        memcpy(allocated, bytes.baseAddress!, bytes.count)
    }
    outPtr?.pointee = allocated
    outLen?.pointee = UInt(encoded.count)
    return true
}

@inlinable func boltffiEncode(_ body: (inout WireWriter) -> Void) -> [UInt8] {
    var writer = WireWriter()
    body(&writer)
    return writer.finalize()
}
