// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System.Runtime.InteropServices;

namespace XybridBolt
{
    public readonly struct XybridInferenceMetrics
    {
        public XybridInferenceMetrics(uint TotalMs, uint? TtftMs, float? TokensPerSecond, float? PrefillTps, float? DecodeTps, uint? TokensOut, XybridStageLatency[] StageLatenciesMs) { this.TotalMs = TotalMs; this.TtftMs = TtftMs; this.TokensPerSecond = TokensPerSecond; this.PrefillTps = PrefillTps; this.DecodeTps = DecodeTps; this.TokensOut = TokensOut; this.StageLatenciesMs = StageLatenciesMs; }
        public uint TotalMs { get; }
        public uint? TtftMs { get; }
        public float? TokensPerSecond { get; }
        public float? PrefillTps { get; }
        public float? DecodeTps { get; }
        public uint? TokensOut { get; }
        public XybridStageLatency[] StageLatenciesMs { get; }

        internal static XybridInferenceMetrics Decode(WireReader reader) =>
            new XybridInferenceMetrics(
                reader.ReadU32(),
                reader.ReadU8() == 0 ? default(uint?) : reader.ReadU32(),
                reader.ReadU8() == 0 ? default(float?) : reader.ReadF32(),
                reader.ReadU8() == 0 ? default(float?) : reader.ReadF32(),
                reader.ReadU8() == 0 ? default(float?) : reader.ReadF32(),
                reader.ReadU8() == 0 ? default(uint?) : reader.ReadU32(),
                reader.ReadArray(reader => XybridStageLatency.Decode(reader))
            );

        internal void Encode(WireWriter writer)
        {
            {
                writer.WriteU32(this.TotalMs);
            }
            {
                if (this.TtftMs is { } boltffiValue0)
                {
                    writer.WriteU8(1);
                    writer.WriteU32(boltffiValue0);
                }
                else
                {
                    writer.WriteU8(0);
                }
            }
            {
                if (this.TokensPerSecond is { } boltffiValue0)
                {
                    writer.WriteU8(1);
                    writer.WriteF32(boltffiValue0);
                }
                else
                {
                    writer.WriteU8(0);
                }
            }
            {
                if (this.PrefillTps is { } boltffiValue0)
                {
                    writer.WriteU8(1);
                    writer.WriteF32(boltffiValue0);
                }
                else
                {
                    writer.WriteU8(0);
                }
            }
            {
                if (this.DecodeTps is { } boltffiValue0)
                {
                    writer.WriteU8(1);
                    writer.WriteF32(boltffiValue0);
                }
                else
                {
                    writer.WriteU8(0);
                }
            }
            {
                if (this.TokensOut is { } boltffiValue0)
                {
                    writer.WriteU8(1);
                    writer.WriteU32(boltffiValue0);
                }
                else
                {
                    writer.WriteU8(0);
                }
            }
            {
                writer.WriteU32(checked((uint)this.StageLatenciesMs.Length));
                foreach (var boltffiValue0 in this.StageLatenciesMs)
                {
                    boltffiValue0.Encode(writer);
                }
            }
        }

    }
}