// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System.Runtime.InteropServices;

namespace XybridBolt
{
    /// <summary>
    /// The outcome of running one tool, fed back with [`tool_results_envelope`].
    /// </summary>
    /// <param name="CallId">The [`XybridToolCall::id`] this answers.</param>
    /// <param name="ContentJson">The tool's output as a JSON string.</param>
    public readonly struct XybridToolResult
    {
        public XybridToolResult(string CallId, string Name, string ContentJson) { this.CallId = CallId; this.Name = Name; this.ContentJson = ContentJson; }
        public string CallId { get; }
        public string Name { get; }
        public string ContentJson { get; }

        internal static XybridToolResult Decode(WireReader reader) =>
            new XybridToolResult(
                reader.ReadString(),
                reader.ReadString(),
                reader.ReadString()
            );

        internal void Encode(WireWriter writer)
        {
            {
                writer.WriteString(this.CallId);
            }
            {
                writer.WriteString(this.Name);
            }
            {
                writer.WriteString(this.ContentJson);
            }
        }

    }
}