// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

namespace XybridBolt
{
    public enum XybridOutputType : int
    {
        Text = 0,
        Audio = 1,
        Embedding = 2,
        Unknown = 3
    }
}