// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System.Runtime.InteropServices;

namespace XybridBolt
{
    /// <summary>
    /// One pull from a streaming inference session.
    ///
    /// This is a flat record instead of a data-carrying enum because the pinned
    /// C# generator cannot lower that enum shape reliably. `kind` selects the one
    /// populated payload: `token` for `Token`, none for `Complete`. A `Complete`
    /// event is followed by [`XybridModel::stream_result`] to retrieve the final
    /// result. Inference failures are returned as typed [`XybridError`] values by
    /// [`XybridModel::stream_next`].
    /// </summary>
    public readonly struct XybridStreamEvent
    {
        public XybridStreamEvent(XybridStreamEventKind Kind, XybridStreamToken? Token, XybridTtsAudioChunk? Audio) { this.Kind = Kind; this.Token = Token; this.Audio = Audio; }
        public XybridStreamEventKind Kind { get; }
        public XybridStreamToken? Token { get; }
        public XybridTtsAudioChunk? Audio { get; }

        internal static XybridStreamEvent Decode(WireReader reader) =>
            new XybridStreamEvent(
                (XybridStreamEventKind)reader.ReadI32(),
                reader.ReadU8() == 0 ? default(XybridStreamToken?) : XybridStreamToken.Decode(reader),
                reader.ReadU8() == 0 ? default(XybridTtsAudioChunk?) : XybridTtsAudioChunk.Decode(reader)
            );

        internal void Encode(WireWriter writer)
        {
            {
                writer.WriteI32((int)this.Kind);
            }
            {
                if (this.Token is { } boltffiValue0)
                {
                    writer.WriteU8(1);
                    boltffiValue0.Encode(writer);
                }
                else
                {
                    writer.WriteU8(0);
                }
            }
            {
                if (this.Audio is { } boltffiValue0)
                {
                    writer.WriteU8(1);
                    boltffiValue0.Encode(writer);
                }
                else
                {
                    writer.WriteU8(0);
                }
            }
        }

    }
}