// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System;

namespace XybridBolt
{
    /// <summary>
    /// Where a result was produced — observed fact, not a routing preference.
    /// </summary>
    public enum XybridExecutionTarget : int
    {
        Local = 0,
        Cloud = 1
    }

    internal static class XybridExecutionTargetWire
    {
        internal const int WireEncodedSize = 4;

        internal static XybridExecutionTarget Decode(WireReader reader) =>
            reader.ReadI32() switch
            {
                0 => XybridExecutionTarget.Local,
                1 => XybridExecutionTarget.Cloud,
                int tag => throw new InvalidOperationException($"Unknown XybridExecutionTarget wire tag: {tag}"),
            };

        internal static void WireEncodeTo(this XybridExecutionTarget value, WireWriter wire) =>
            wire.WriteI32(value switch
            {
                XybridExecutionTarget.Local => 0,
                XybridExecutionTarget.Cloud => 1,
                _ => throw new InvalidOperationException($"Unknown XybridExecutionTarget variant: {value}"),
            });
    }
}