// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System.Runtime.InteropServices;

namespace XybridBolt
{
    /// <summary>
    /// A partial transcript emitted while audio is streaming.
    /// </summary>
    /// <param name="Text">
    /// Best-effort transcript so far. Cumulative, not a delta — render it in
    /// place of the previous partial rather than appending.
    /// </param>
    /// <param name="IsStable">`true` once this span is committed and will not change.</param>
    /// <param name="ChunkSequence">Monotonic chunk sequence number this result corresponds to.</param>
    /// <param name="AudioDurationMs">Audio covered so far, in milliseconds.</param>
    public readonly struct XybridPartialResult
    {
        public XybridPartialResult(string Text, bool IsStable, ulong ChunkSequence, ulong AudioDurationMs) { this.Text = Text; this.IsStable = IsStable; this.ChunkSequence = ChunkSequence; this.AudioDurationMs = AudioDurationMs; }
        public string Text { get; }
        public bool IsStable { get; }
        public ulong ChunkSequence { get; }
        public ulong AudioDurationMs { get; }

        internal static XybridPartialResult Decode(WireReader reader) =>
            new XybridPartialResult(
                reader.ReadString(),
                reader.ReadBool(),
                reader.ReadU64(),
                reader.ReadU64()
            );

        internal void Encode(WireWriter writer)
        {
            {
                writer.WriteString(this.Text);
            }
            {
                writer.WriteBool(this.IsStable);
            }
            {
                writer.WriteU64(this.ChunkSequence);
            }
            {
                writer.WriteU64(this.AudioDurationMs);
            }
        }

    }
}