// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System;
using System.Threading;
using System.Text;

namespace XybridBolt
{
    /// <summary>
    /// Opaque handle for multi-turn conversation history.
    ///
    /// Build it up with [`push`](Self::push) / [`set_system`](Self::set_system),
    /// then pass it to [`XybridModel::run_with_context`] /
    /// [`XybridModel::run_stream_with_context`]. Wraps the facade's
    /// interior-mutable, thread-safe `ConversationContextHandle`.
    /// </summary>
    public sealed partial class XybridConversationContext : IDisposable
    {
        private IntPtr _handle;

        // Private handle-adopting ctor; used only by chained `: this(...)` and the static factories below.
        private XybridConversationContext(IntPtr handle)
        {
            _handle = handle;
        }

        /// <summary>
        /// Create an empty conversation context (fresh id).
        /// </summary>
        public XybridConversationContext()
            : this(XybridConversationContextNewHandle()) { }

        private static IntPtr XybridConversationContextNewHandle()
        {
            return NativeMethods.XybridConversationContextNew();
        }

        /// <summary>
        /// Create a context with a caller-supplied id (for telemetry correlation
        /// across turns).
        /// </summary>
        public static XybridConversationContext WithId(string id)
        {
            byte[] _idBytes = Encoding.UTF8.GetBytes(id);
            return new XybridConversationContext(NativeMethods.XybridConversationContextWithId(_idBytes, (UIntPtr)_idBytes.Length));
        }

        /// <summary>
        /// Drop the history; the system envelope (if any) is preserved.
        /// </summary>
        public void Clear()
        {
            ThrowIfDisposed();
            NativeMethods.XybridConversationContextClear(_handle);
        }

        /// <summary>
        /// The context id.
        /// </summary>
        public string Id()
        {
            ThrowIfDisposed();
            FfiBuf _buf = NativeMethods.XybridConversationContextId(_handle);
            try
            {
                return new WireReader(_buf).ReadString();
            }
            finally
            {
                NativeMethods.FreeBuf(_buf);
            }
        }

        /// <summary>
        /// Number of history turns (excludes the system envelope).
        /// </summary>
        public uint HistoryLen()
        {
            ThrowIfDisposed();
            return NativeMethods.XybridConversationContextHistoryLen(_handle);
        }

        /// <summary>
        /// Whether a persistent system-prompt envelope is set.
        /// </summary>
        public bool HasSystem()
        {
            ThrowIfDisposed();
            return NativeMethods.XybridConversationContextHasSystem(_handle);
        }

        /// <summary>
        /// Set the max history length before FIFO pruning.
        /// </summary>
        public void SetMaxHistoryLen(uint len)
        {
            ThrowIfDisposed();
            NativeMethods.XybridConversationContextSetMaxHistoryLen(_handle, len);
        }

        internal IntPtr RawHandle => _handle;

        private void ThrowIfDisposed()
        {
            if (_handle == IntPtr.Zero) throw new ObjectDisposedException(nameof(XybridConversationContext));
        }

        public void Dispose()
        {
            IntPtr handle = Interlocked.Exchange(ref _handle, IntPtr.Zero);
            if (handle == IntPtr.Zero) return;
            NativeMethods.XybridConversationContextFree(handle);
            GC.SuppressFinalize(this);
        }

        ~XybridConversationContext()
        {
            Dispose();
        }
    }
}