// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System.Runtime.InteropServices;

namespace XybridBolt
{
    /// <summary>
    /// Final transcript returned when a live ASR session is flushed.
    /// </summary>
    public readonly struct XybridAsrTranscriptionResult
    {
        public XybridAsrTranscriptionResult(string Text, ulong DurationMs, ulong ChunksProcessed) { this.Text = Text; this.DurationMs = DurationMs; this.ChunksProcessed = ChunksProcessed; }
        public string Text { get; }
        public ulong DurationMs { get; }
        public ulong ChunksProcessed { get; }

        internal static XybridAsrTranscriptionResult Decode(WireReader reader) =>
            new XybridAsrTranscriptionResult(
                reader.ReadString(),
                reader.ReadU64(),
                reader.ReadU64()
            );

        internal void Encode(WireWriter writer)
        {
            {
                writer.WriteString(this.Text);
            }
            {
                writer.WriteU64(this.DurationMs);
            }
            {
                writer.WriteU64(this.ChunksProcessed);
            }
        }

    }
}