// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System.Runtime.InteropServices;

namespace XybridBolt
{
    /// <summary>
    /// Download progress + state in one consistent read.
    /// </summary>
    /// <param name="Progress">0.0..=1.0.</param>
    public readonly struct XybridDownloadStatus
    {
        public XybridDownloadStatus(XybridDownloadState State, float Progress) { this.State = State; this.Progress = Progress; }
        public XybridDownloadState State { get; }
        public float Progress { get; }

        internal static XybridDownloadStatus Decode(WireReader reader) =>
            new XybridDownloadStatus(
                (XybridDownloadState)reader.ReadI32(),
                reader.ReadF32()
            );

        internal void Encode(WireWriter writer)
        {
            {
                writer.WriteI32((int)this.State);
            }
            {
                writer.WriteF32(this.Progress);
            }
        }

    }
}