// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System;

namespace XybridBolt
{
    /// <summary>
    /// Download progress + state in one consistent read.
    /// </summary>
    /// <param name="Progress">0.0..=1.0.</param>
    public readonly struct XybridDownloadStatus
    {
        public XybridDownloadStatus(XybridDownloadState State, float Progress) { this.State = State; this.Progress = Progress; }
        public XybridDownloadState State { get; }
        public float Progress { get; }

        internal static XybridDownloadStatus Decode(WireReader reader) =>
            new XybridDownloadStatus(
                XybridDownloadStateWire.Decode(reader),
                reader.ReadF32()
            );

        internal int WireEncodedSize() =>
            4 +
            4;

        internal void WireEncodeTo(WireWriter wire)
        {
            this.State.WireEncodeTo(wire);
            wire.WriteF32(this.Progress);
        }
    }
}