// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System.Runtime.InteropServices;

namespace XybridBolt
{
    /// <summary>
    /// Configuration for a live, rolling-window ASR session.
    /// </summary>
    /// <param name="SampleRate">PCM sample rate. Must currently be 16 kHz.</param>
    /// <param name="Language">Optional language hint; `None` preserves the model bundle's behavior.</param>
    /// <param name="AudioCtx">Optional Whisper encoder context override in mel frames.</param>
    public readonly struct XybridAsrStreamConfig
    {
        public XybridAsrStreamConfig(uint SampleRate, bool EnableVad, float VadThreshold, string? VadModelDir, string? Language, uint? AudioCtx) { this.SampleRate = SampleRate; this.EnableVad = EnableVad; this.VadThreshold = VadThreshold; this.VadModelDir = VadModelDir; this.Language = Language; this.AudioCtx = AudioCtx; }
        public uint SampleRate { get; }
        public bool EnableVad { get; }
        public float VadThreshold { get; }
        public string? VadModelDir { get; }
        public string? Language { get; }
        public uint? AudioCtx { get; }

        internal static XybridAsrStreamConfig Decode(WireReader reader) =>
            new XybridAsrStreamConfig(
                reader.ReadU32(),
                reader.ReadBool(),
                reader.ReadF32(),
                reader.ReadU8() == 0 ? default(string?) : reader.ReadString(),
                reader.ReadU8() == 0 ? default(string?) : reader.ReadString(),
                reader.ReadU8() == 0 ? default(uint?) : reader.ReadU32()
            );

        internal void Encode(WireWriter writer)
        {
            {
                writer.WriteU32(this.SampleRate);
            }
            {
                writer.WriteBool(this.EnableVad);
            }
            {
                writer.WriteF32(this.VadThreshold);
            }
            {
                if (this.VadModelDir is { } boltffiValue0)
                {
                    writer.WriteU8(1);
                    writer.WriteString(boltffiValue0);
                }
                else
                {
                    writer.WriteU8(0);
                }
            }
            {
                if (this.Language is { } boltffiValue0)
                {
                    writer.WriteU8(1);
                    writer.WriteString(boltffiValue0);
                }
                else
                {
                    writer.WriteU8(0);
                }
            }
            {
                if (this.AudioCtx is { } boltffiValue0)
                {
                    writer.WriteU8(1);
                    writer.WriteU32(boltffiValue0);
                }
                else
                {
                    writer.WriteU8(0);
                }
            }
        }

    }
}