// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System;
using System.Threading;
using System.Text;

namespace XybridBolt
{
    public sealed partial class XybridModel : IDisposable
    {
        private IntPtr _handle;

        // Private handle-adopting ctor; used only by chained `: this(...)` and the static factories below.
        private XybridModel(IntPtr handle)
        {
            _handle = handle;
        }

        /// <summary>
        /// Load from the xybrid registry. Recommended path.
        /// </summary>
        public static XybridModel FromRegistry(string id)
        {
            byte[] _idBytes = Encoding.UTF8.GetBytes(id);
            IntPtr _handle = NativeMethods.XybridModelFromRegistry(_idBytes, (UIntPtr)_idBytes.Length);
            if (_handle == IntPtr.Zero) throw new BoltException(NativeMethods.TakeLastErrorMessage("Factory constructor failed"));
            return new XybridModel(_handle);
        }

        /// <summary>
        /// Load from the registry, serving from the cloud gateway while the weights
        /// download in the background.
        ///
        /// Returns almost immediately instead of blocking on the download. Requires
        /// a resolvable API key and an uncached model; otherwise it behaves exactly
        /// like `from_registry`. Poll `download_status` for progress and
        /// `is_cloud_serving` to know which leg is answering. LLM/chat models only.
        /// </summary>
        public static XybridModel FromRegistrySpeculative(string id)
        {
            byte[] _idBytes = Encoding.UTF8.GetBytes(id);
            IntPtr _handle = NativeMethods.XybridModelFromRegistrySpeculative(_idBytes, (UIntPtr)_idBytes.Length);
            if (_handle == IntPtr.Zero) throw new BoltException(NativeMethods.TakeLastErrorMessage("Factory constructor failed"));
            return new XybridModel(_handle);
        }

        /// <summary>
        /// Load from a local model directory (must contain `model_metadata.json`).
        /// </summary>
        public static XybridModel FromDirectory(string path)
        {
            byte[] _pathBytes = Encoding.UTF8.GetBytes(path);
            IntPtr _handle = NativeMethods.XybridModelFromDirectory(_pathBytes, (UIntPtr)_pathBytes.Length);
            if (_handle == IntPtr.Zero) throw new BoltException(NativeMethods.TakeLastErrorMessage("Factory constructor failed"));
            return new XybridModel(_handle);
        }

        /// <summary>
        /// Load from a local `.xyb` bundle.
        /// </summary>
        public static XybridModel FromBundle(string path)
        {
            byte[] _pathBytes = Encoding.UTF8.GetBytes(path);
            IntPtr _handle = NativeMethods.XybridModelFromBundle(_pathBytes, (UIntPtr)_pathBytes.Length);
            if (_handle == IntPtr.Zero) throw new BoltException(NativeMethods.TakeLastErrorMessage("Factory constructor failed"));
            return new XybridModel(_handle);
        }

        /// <summary>
        /// Resolve and load from a HuggingFace repo (`org/repo` or `org/repo:variant`).
        /// </summary>
        public static XybridModel FromHuggingface(string repo)
        {
            byte[] _repoBytes = Encoding.UTF8.GetBytes(repo);
            IntPtr _handle = NativeMethods.XybridModelFromHuggingface(_repoBytes, (UIntPtr)_repoBytes.Length);
            if (_handle == IntPtr.Zero) throw new BoltException(NativeMethods.TakeLastErrorMessage("Factory constructor failed"));
            return new XybridModel(_handle);
        }

        /// <summary>
        /// Load from a raw GGUF file, auto-generating `model_metadata.json` from the
        /// GGUF header (written next to the file if absent).
        /// </summary>
        public static XybridModel FromModelFile(string path)
        {
            byte[] _pathBytes = Encoding.UTF8.GetBytes(path);
            IntPtr _handle = NativeMethods.XybridModelFromModelFile(_pathBytes, (UIntPtr)_pathBytes.Length);
            if (_handle == IntPtr.Zero) throw new BoltException(NativeMethods.TakeLastErrorMessage("Factory constructor failed"));
            return new XybridModel(_handle);
        }

        public string ModelId()
        {
            ThrowIfDisposed();
            FfiBuf _buf = NativeMethods.XybridModelModelId(_handle);
            try
            {
                return new WireReader(_buf).ReadString();
            }
            finally
            {
                NativeMethods.FreeBuf(_buf);
            }
        }

        public string Version()
        {
            ThrowIfDisposed();
            FfiBuf _buf = NativeMethods.XybridModelVersion(_handle);
            try
            {
                return new WireReader(_buf).ReadString();
            }
            finally
            {
                NativeMethods.FreeBuf(_buf);
            }
        }

        public XybridOutputType OutputType()
        {
            ThrowIfDisposed();
            return NativeMethods.XybridModelOutputType(_handle);
        }

        public bool IsLoaded()
        {
            ThrowIfDisposed();
            return NativeMethods.XybridModelIsLoaded(_handle);
        }

        /// <summary>
        /// Whether runs are currently answered by the cloud because the local
        /// weights are not ready yet. `false` for ordinary local models.
        /// </summary>
        public bool IsCloudServing()
        {
            ThrowIfDisposed();
            return NativeMethods.XybridModelIsCloudServing(_handle);
        }

        /// <summary>
        /// Download progress + state in one read — poll this to drive a progress
        /// bar. Reports `Ready` at 1.0 for an ordinary local model, so hosts need
        /// no special case.
        /// </summary>
        public XybridDownloadStatus DownloadStatus()
        {
            ThrowIfDisposed();
            FfiBuf _buf = NativeMethods.XybridModelDownloadStatus(_handle);
            try
            {
                return XybridDownloadStatus.Decode(new WireReader(_buf));
            }
            finally
            {
                NativeMethods.FreeBuf(_buf);
            }
        }

        /// <summary>
        /// Block until the download finishes or `timeout_ms` elapses, then report
        /// the status. Call it off the UI thread (the same place `from_registry` is
        /// already called). `timeout_ms = 0` makes it a non-blocking read.
        /// </summary>
        public XybridDownloadStatus AwaitDownload(ulong timeoutMs)
        {
            ThrowIfDisposed();
            FfiBuf _buf = NativeMethods.XybridModelAwaitDownload(_handle, timeoutMs);
            try
            {
                return XybridDownloadStatus.Decode(new WireReader(_buf));
            }
            finally
            {
                NativeMethods.FreeBuf(_buf);
            }
        }

        public bool SupportsStreaming()
        {
            ThrowIfDisposed();
            return NativeMethods.XybridModelSupportsStreaming(_handle);
        }

        /// <summary>
        /// Whether this model emits true token-by-token output.
        /// </summary>
        public bool SupportsTokenStreaming()
        {
            ThrowIfDisposed();
            return NativeMethods.XybridModelSupportsTokenStreaming(_handle);
        }

        public bool IsLlm()
        {
            ThrowIfDisposed();
            return NativeMethods.XybridModelIsLlm(_handle);
        }

        public bool HasVoices()
        {
            ThrowIfDisposed();
            return NativeMethods.XybridModelHasVoices(_handle);
        }

        public XybridVoiceInfo[] Voices()
        {
            ThrowIfDisposed();
            FfiBuf _buf = NativeMethods.XybridModelVoices(_handle);
            try
            {
                return new WireReader(_buf).ReadEncodedArray<XybridVoiceInfo>(r0 => XybridVoiceInfo.Decode(r0));
            }
            finally
            {
                NativeMethods.FreeBuf(_buf);
            }
        }

        public XybridVoiceInfo? DefaultVoice()
        {
            ThrowIfDisposed();
            FfiBuf _buf = NativeMethods.XybridModelDefaultVoice(_handle);
            try
            {
                var reader = new WireReader(_buf);
                return reader.ReadU8() == 0 ? (XybridVoiceInfo?)null : XybridVoiceInfo.Decode(reader);
            }
            finally
            {
                NativeMethods.FreeBuf(_buf);
            }
        }

        public XybridVoiceInfo? Voice(string voiceId)
        {
            ThrowIfDisposed();
            byte[] _voiceIdBytes = Encoding.UTF8.GetBytes(voiceId);
            FfiBuf _buf = NativeMethods.XybridModelVoice(_handle, _voiceIdBytes, (UIntPtr)_voiceIdBytes.Length);
            try
            {
                var reader = new WireReader(_buf);
                return reader.ReadU8() == 0 ? (XybridVoiceInfo?)null : XybridVoiceInfo.Decode(reader);
            }
            finally
            {
                NativeMethods.FreeBuf(_buf);
            }
        }

        /// <summary>
        /// Block until the next item for `stream_id` is ready.
        /// </summary>
        public XybridStreamEvent StreamNext(ulong streamId)
        {
            ThrowIfDisposed();
            FfiBuf _buf = NativeMethods.XybridModelStreamNext(_handle, streamId);
            try
            {
                var reader = new WireReader(_buf);
                if (reader.ReadU8() != 0) throw new XybridErrorException(XybridError.Decode(reader));
                return XybridStreamEvent.Decode(reader);
            }
            finally
            {
                NativeMethods.FreeBuf(_buf);
                // StreamNext can block for the full inter-token gap. Keep
                // this wrapper alive so its finalizer cannot free _handle
                // while the native call is still using it.
                GC.KeepAlive(this);
            }
        }

        /// <summary>
        /// Forget a streaming session.
        /// </summary>
        public void StreamClose(ulong streamId)
        {
            ThrowIfDisposed();
            NativeMethods.XybridModelStreamClose(_handle, streamId);
        }

        public void Warmup()
        {
            ThrowIfDisposed();
            FfiBuf _buf = NativeMethods.XybridModelWarmup(_handle);
            try
            {
                var reader = new WireReader(_buf);
                if (reader.ReadU8() != 0) throw new XybridErrorException(XybridError.Decode(reader));
            }
            finally
            {
                NativeMethods.FreeBuf(_buf);
            }
        }

        public void Unload()
        {
            ThrowIfDisposed();
            FfiBuf _buf = NativeMethods.XybridModelUnload(_handle);
            try
            {
                var reader = new WireReader(_buf);
                if (reader.ReadU8() != 0) throw new XybridErrorException(XybridError.Decode(reader));
            }
            finally
            {
                NativeMethods.FreeBuf(_buf);
            }
        }

        internal IntPtr RawHandle => _handle;

        private void ThrowIfDisposed()
        {
            if (_handle == IntPtr.Zero) throw new ObjectDisposedException(nameof(XybridModel));
        }

        public void Dispose()
        {
            IntPtr handle = Interlocked.Exchange(ref _handle, IntPtr.Zero);
            if (handle == IntPtr.Zero) return;
            NativeMethods.XybridModelFree(handle);
            GC.SuppressFinalize(this);
        }

        ~XybridModel()
        {
            Dispose();
        }
    }
}