// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System.Runtime.InteropServices;

namespace XybridBolt
{
    /// <summary>
    /// Result of [`XybridPipeline::run`]: the final output plus every stage's own
    /// output, so a voice pipeline can show the transcript and the reply as well
    /// as play the audio.
    /// </summary>
    /// <param name="Envelope">
    /// The final stage's output — the same envelope as the last entry of
    /// `stages`.
    /// </param>
    /// <param name="LatencyMs">Wall-clock time of the whole run.</param>
    /// <param name="Stages">Every executed stage, in order.</param>
    public readonly struct XybridPipelineResult
    {
        public XybridPipelineResult(XybridEnvelope Envelope, XybridOutputType OutputType, uint LatencyMs, XybridStageResult[] Stages) { this.Envelope = Envelope; this.OutputType = OutputType; this.LatencyMs = LatencyMs; this.Stages = Stages; }
        public XybridEnvelope Envelope { get; }
        public XybridOutputType OutputType { get; }
        public uint LatencyMs { get; }
        public XybridStageResult[] Stages { get; }

        internal static XybridPipelineResult Decode(WireReader reader) =>
            new XybridPipelineResult(
                XybridEnvelope.Decode(reader),
                (XybridOutputType)reader.ReadI32(),
                reader.ReadU32(),
                reader.ReadArray(reader => XybridStageResult.Decode(reader))
            );

        internal void Encode(WireWriter writer)
        {
            {
                this.Envelope.Encode(writer);
            }
            {
                writer.WriteI32((int)this.OutputType);
            }
            {
                writer.WriteU32(this.LatencyMs);
            }
            {
                writer.WriteU32(checked((uint)this.Stages.Length));
                foreach (var boltffiValue0 in this.Stages)
                {
                    boltffiValue0.Encode(writer);
                }
            }
        }

    }
}