// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

namespace XybridBolt
{
    public enum XybridMessageRole : int
    {
        System = 0,
        User = 1,
        Assistant = 2
    }
}