// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

namespace XybridBolt
{
    public sealed class XybridBundle : global::System.IDisposable
    {
        private long handle;

        internal ulong Handle => unchecked((ulong)(ulong)global::System.Threading.Interlocked.Read(ref handle));

        internal XybridBundle(ulong handle)
        {
            if (handle == 0) throw new global::System.ArgumentException("handle must not be zero", nameof(handle));
            this.handle = unchecked((long)(ulong)handle);
        }


        /// <summary>
        /// Open and parse a `.xyb` bundle (decompress zstd, parse tar, validate the
        /// manifest).
        /// </summary>
        public static XybridBundle Open(string path)
        {
            WireWriter pathWriter = new WireWriter();
            {
                pathWriter.WriteString(path);
            }
            byte[] pathBytes = pathWriter.ToArray();
            FfiBuf boltffiErrorBuffer = NativeMethods.NativeXybridBundleOpen(pathBytes, (nuint)pathBytes.Length, out ulong boltffiHandle);
            if (boltffiErrorBuffer.ptr != 0)
            {
                try
                {
                    WireReader boltffiErrorReader = new WireReader(boltffiErrorBuffer);
                    throw new global::XybridBolt.XybridErrorException(global::XybridBolt.XybridError.Decode(boltffiErrorReader));
                }
                finally
                {
                    NativeMethods.FreeBuf(boltffiErrorBuffer);
                }
            }
            return boltffiHandle == 0 ? throw new global::System.InvalidOperationException("BoltFFI returned a null XybridBundle handle") : new XybridBundle(boltffiHandle);
        }


        /// <summary>
        /// The model identifier from the manifest.
        /// </summary>
        public string ModelId()
        {
            ThrowIfDisposed();
            FfiBuf boltffiResultBuffer = NativeMethods.NativeXybridBundleModelId(this.Handle);
            try
            {
                WireReader resultReader = new WireReader(boltffiResultBuffer);
                return resultReader.ReadString();
            }
            finally
            {
                NativeMethods.FreeBuf(boltffiResultBuffer);
            }
        }


        /// <summary>
        /// The version string from the manifest.
        /// </summary>
        public string Version()
        {
            ThrowIfDisposed();
            FfiBuf boltffiResultBuffer = NativeMethods.NativeXybridBundleVersion(this.Handle);
            try
            {
                WireReader resultReader = new WireReader(boltffiResultBuffer);
                return resultReader.ReadString();
            }
            finally
            {
                NativeMethods.FreeBuf(boltffiResultBuffer);
            }
        }


        /// <summary>
        /// The target platform from the manifest.
        /// </summary>
        public string Target()
        {
            ThrowIfDisposed();
            FfiBuf boltffiResultBuffer = NativeMethods.NativeXybridBundleTarget(this.Handle);
            try
            {
                WireReader resultReader = new WireReader(boltffiResultBuffer);
                return resultReader.ReadString();
            }
            finally
            {
                NativeMethods.FreeBuf(boltffiResultBuffer);
            }
        }


        /// <summary>
        /// The SHA-256 hash from the manifest.
        /// </summary>
        public string Hash()
        {
            ThrowIfDisposed();
            FfiBuf boltffiResultBuffer = NativeMethods.NativeXybridBundleHash(this.Handle);
            try
            {
                WireReader resultReader = new WireReader(boltffiResultBuffer);
                return resultReader.ReadString();
            }
            finally
            {
                NativeMethods.FreeBuf(boltffiResultBuffer);
            }
        }


        /// <summary>
        /// Whether the bundle carries a `model_metadata.json`.
        /// </summary>
        public bool HasMetadata()
        {
            ThrowIfDisposed();
            return NativeMethods.NativeXybridBundleHasMetadata(this.Handle);
        }


        /// <summary>
        /// Number of files in the bundle (excludes `manifest.json`).
        /// </summary>
        public uint FileCount()
        {
            ThrowIfDisposed();
            return NativeMethods.NativeXybridBundleFileCount(this.Handle);
        }


        /// <summary>
        /// The file name at `index`, or `None` if out of bounds.
        /// </summary>
        public string? FileName(uint index)
        {
            ThrowIfDisposed();
            FfiBuf boltffiResultBuffer = NativeMethods.NativeXybridBundleFileName(this.Handle, index);
            try
            {
                WireReader resultReader = new WireReader(boltffiResultBuffer);
                return resultReader.ReadU8() == 0 ? default(string?) : resultReader.ReadString();
            }
            finally
            {
                NativeMethods.FreeBuf(boltffiResultBuffer);
            }
        }


        /// <summary>
        /// The full bundle manifest serialized as JSON.
        /// </summary>
        public string ManifestJson()
        {
            ThrowIfDisposed();
            FfiBuf boltffiErrorBuffer = NativeMethods.NativeXybridBundleManifestJson(this.Handle, out FfiBuf boltffiResultBuffer);
            if (boltffiErrorBuffer.ptr != 0)
            {
                try
                {
                    WireReader boltffiErrorReader = new WireReader(boltffiErrorBuffer);
                    throw new global::XybridBolt.XybridErrorException(global::XybridBolt.XybridError.Decode(boltffiErrorReader));
                }
                finally
                {
                    NativeMethods.FreeBuf(boltffiErrorBuffer);
                }
            }
            try
            {
                WireReader resultReader = new WireReader(boltffiResultBuffer);
                return resultReader.ReadString();
            }
            finally
            {
                NativeMethods.FreeBuf(boltffiResultBuffer);
            }
        }


        /// <summary>
        /// The `model_metadata.json` contents, or `None` if the bundle has none.
        /// </summary>
        public string? MetadataJson()
        {
            ThrowIfDisposed();
            FfiBuf boltffiErrorBuffer = NativeMethods.NativeXybridBundleMetadataJson(this.Handle, out FfiBuf boltffiResultBuffer);
            if (boltffiErrorBuffer.ptr != 0)
            {
                try
                {
                    WireReader boltffiErrorReader = new WireReader(boltffiErrorBuffer);
                    throw new global::XybridBolt.XybridErrorException(global::XybridBolt.XybridError.Decode(boltffiErrorReader));
                }
                finally
                {
                    NativeMethods.FreeBuf(boltffiErrorBuffer);
                }
            }
            try
            {
                WireReader resultReader = new WireReader(boltffiResultBuffer);
                return resultReader.ReadU8() == 0 ? default(string?) : resultReader.ReadString();
            }
            finally
            {
                NativeMethods.FreeBuf(boltffiResultBuffer);
            }
        }


        /// <summary>
        /// Extract every bundle file to `output_dir` (created if absent).
        /// </summary>
        public void Extract(string outputDir)
        {
            ThrowIfDisposed();
            WireWriter outputDirWriter = new WireWriter();
            {
                outputDirWriter.WriteString(outputDir);
            }
            byte[] outputDirBytes = outputDirWriter.ToArray();
            FfiBuf boltffiErrorBuffer = NativeMethods.NativeXybridBundleExtract(this.Handle, outputDirBytes, (nuint)outputDirBytes.Length);
            if (boltffiErrorBuffer.ptr != 0)
            {
                try
                {
                    WireReader boltffiErrorReader = new WireReader(boltffiErrorBuffer);
                    throw new global::XybridBolt.XybridErrorException(global::XybridBolt.XybridError.Decode(boltffiErrorReader));
                }
                finally
                {
                    NativeMethods.FreeBuf(boltffiErrorBuffer);
                }
            }
        }


        private ulong TakeHandle() => unchecked((ulong)(ulong)global::System.Threading.Interlocked.Exchange(ref handle, 0));

        private void ThrowIfDisposed()
        {
            if (global::System.Threading.Interlocked.Read(ref handle) == 0)
                throw new global::System.ObjectDisposedException(nameof(XybridBundle));
        }

        private void Release()
        {
            ulong released = unchecked((ulong)(ulong)global::System.Threading.Interlocked.Exchange(ref handle, 0));
            if (released != 0) NativeMethods.NativeXybridBundleRelease(released);
        }

        ~XybridBundle() => Release();

        public void Dispose()
        {
            Release();
            global::System.GC.SuppressFinalize(this);
        }
    }
}