// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

namespace XybridBolt
{
    public enum XybridStreamEventKind : int
    {
        Token = 0,
        Complete = 1
    }
}