// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System;
using System.Text;

namespace XybridBolt
{
    public readonly struct XybridRunOptions
    {
        public XybridRunOptions(XybridGenerationConfig? GenerationConfig, XybridAbortSignal[] AbortOn, bool FallbackToCloud, uint MaxGraceTokens, string? CorrelationId) { this.GenerationConfig = GenerationConfig; this.AbortOn = AbortOn; this.FallbackToCloud = FallbackToCloud; this.MaxGraceTokens = MaxGraceTokens; this.CorrelationId = CorrelationId; }
        public XybridGenerationConfig? GenerationConfig { get; }
        public XybridAbortSignal[] AbortOn { get; }
        public bool FallbackToCloud { get; }
        public uint MaxGraceTokens { get; }
        public string? CorrelationId { get; }

        internal static XybridRunOptions Decode(WireReader reader) =>
            new XybridRunOptions(
                reader.ReadU8() == 0 ? (XybridGenerationConfig?)null : XybridGenerationConfig.Decode(reader),
                reader.ReadEncodedArray<XybridAbortSignal>(r0 => XybridAbortSignalWire.Decode(r0)),
                reader.ReadBool(),
                reader.ReadU32(),
                reader.ReadU8() == 0 ? (string?)null : reader.ReadString()
            );

        internal int WireEncodedSize() =>
            (1 + (this.GenerationConfig is { } sizeOpt0 ? sizeOpt0.WireEncodedSize() : 0)) +
            WireWriter.EncodedArraySize(this.AbortOn, sizeItem0 => 4) +
            1 +
            4 +
            (1 + (this.CorrelationId is { } sizeOpt1 ? (4 + Encoding.UTF8.GetByteCount(sizeOpt1)) : 0));

        internal void WireEncodeTo(WireWriter wire)
        {
            if (this.GenerationConfig is { } opt0) { wire.WriteU8((byte)1); opt0.WireEncodeTo(wire); } else { wire.WriteU8((byte)0); };
            wire.WriteI32(this.AbortOn.Length);
            foreach (XybridAbortSignal item0 in this.AbortOn) { item0.WireEncodeTo(wire); };
            wire.WriteBool(this.FallbackToCloud);
            wire.WriteU32(this.MaxGraceTokens);
            if (this.CorrelationId is { } opt1) { wire.WriteU8((byte)1); wire.WriteString(opt1); } else { wire.WriteU8((byte)0); };
        }
    }
}