// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System.Runtime.InteropServices;

namespace XybridBolt
{
    /// <summary>
    /// One tool call the model emitted, from [`XybridResult::tool_calls`].
    /// </summary>
    public readonly struct XybridToolCall
    {
        public XybridToolCall(string Id, string Name, string ArgumentsJson) { this.Id = Id; this.Name = Name; this.ArgumentsJson = ArgumentsJson; }
        public string Id { get; }
        public string Name { get; }
        public string ArgumentsJson { get; }

        internal static XybridToolCall Decode(WireReader reader) =>
            new XybridToolCall(
                reader.ReadString(),
                reader.ReadString(),
                reader.ReadString()
            );

        internal void Encode(WireWriter writer)
        {
            {
                writer.WriteString(this.Id);
            }
            {
                writer.WriteString(this.Name);
            }
            {
                writer.WriteString(this.ArgumentsJson);
            }
        }

    }
}