// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

namespace XybridBolt
{
    /// <summary>
    /// Errors surfaced across the FFI boundary. Variants mirror
    /// [`facade::Error`] — the facade owns the SDK→FFI translation; this enum
    /// only re-decorates it for the BoltFFI generator (proc macros must live
    /// on the type definition).
    ///
    /// Named `XybridError` (not `Error`) so the emitted Swift type doesn't
    /// shadow / collide with Swift's stdlib `Error` protocol, and so the
    /// Kotlin sealed-hierarchy name matches the existing uniffi consumer
    /// expectations.
    ///
    /// **Variant order is part of the wire contract.** BoltFFI encodes `#[error]`
    /// (and `#[data]`) enums by ordinal tag, so reordering or inserting a variant
    /// renumbers every variant after it and breaks already-built foreign clients.
    /// Only ever append at the tail, and keep this order in lockstep with
    /// [`facade::Error`] and its `code()` table.
    /// </summary>
    public abstract record XybridError
    {
        internal static XybridError Decode(WireReader reader) =>
            reader.ReadU32() switch
            {
                0 => new ModelNotFound(reader.ReadString()),
                1 => new DirectoryNotFound(reader.ReadString()),
                2 => new MetadataNotFound(reader.ReadString()),
                3 => new MetadataInvalid(reader.ReadString()),
                4 => new LoadError(reader.ReadString()),
                5 => new InferenceError(reader.ReadString()),
                6 => new AbortedForCloudFallback(reader.ReadString()),
                7 => new StreamingNotSupported(),
                8 => new NotLoaded(),
                9 => new ConfigError(reader.ReadString()),
                10 => new NetworkError(reader.ReadString()),
                11 => new Offline(reader.ReadString()),
                12 => new IoError(reader.ReadString()),
                13 => new CacheError(reader.ReadString()),
                14 => new PipelineError(reader.ReadString()),
                15 => new CircuitOpen(reader.ReadString()),
                16 => new RateLimited(reader.ReadU64()),
                17 => new Timeout(reader.ReadU64()),
                18 => new MissingArtifact(reader.ReadString()),
                19 => new UnsupportedModelCapability(reader.ReadString()),
                20 => new UnsupportedBackendCapability(reader.ReadString()),
                21 => new InvalidImage(reader.ReadString()),
                uint tag => throw new global::System.InvalidOperationException($"Invalid XybridError tag: {tag}"),
            };

        internal void Encode(WireWriter writer)
        {
            switch (this)
            {
                case ModelNotFound value:
                {
                    writer.WriteU32(0);
                    {
                        writer.WriteString(value.Id);
                    }
                    break;
                }
                case DirectoryNotFound value:
                {
                    writer.WriteU32(1);
                    {
                        writer.WriteString(value.Path);
                    }
                    break;
                }
                case MetadataNotFound value:
                {
                    writer.WriteU32(2);
                    {
                        writer.WriteString(value.Path);
                    }
                    break;
                }
                case MetadataInvalid value:
                {
                    writer.WriteU32(3);
                    {
                        writer.WriteString(value.Message);
                    }
                    break;
                }
                case LoadError value:
                {
                    writer.WriteU32(4);
                    {
                        writer.WriteString(value.Message);
                    }
                    break;
                }
                case InferenceError value:
                {
                    writer.WriteU32(5);
                    {
                        writer.WriteString(value.Message);
                    }
                    break;
                }
                case AbortedForCloudFallback value:
                {
                    writer.WriteU32(6);
                    {
                        writer.WriteString(value.Reason);
                    }
                    break;
                }
                case StreamingNotSupported value:
                {
                    writer.WriteU32(7);
                    break;
                }
                case NotLoaded value:
                {
                    writer.WriteU32(8);
                    break;
                }
                case ConfigError value:
                {
                    writer.WriteU32(9);
                    {
                        writer.WriteString(value.Message);
                    }
                    break;
                }
                case NetworkError value:
                {
                    writer.WriteU32(10);
                    {
                        writer.WriteString(value.Message);
                    }
                    break;
                }
                case Offline value:
                {
                    writer.WriteU32(11);
                    {
                        writer.WriteString(value.Message);
                    }
                    break;
                }
                case IoError value:
                {
                    writer.WriteU32(12);
                    {
                        writer.WriteString(value.Message);
                    }
                    break;
                }
                case CacheError value:
                {
                    writer.WriteU32(13);
                    {
                        writer.WriteString(value.Message);
                    }
                    break;
                }
                case PipelineError value:
                {
                    writer.WriteU32(14);
                    {
                        writer.WriteString(value.Message);
                    }
                    break;
                }
                case CircuitOpen value:
                {
                    writer.WriteU32(15);
                    {
                        writer.WriteString(value.Message);
                    }
                    break;
                }
                case RateLimited value:
                {
                    writer.WriteU32(16);
                    {
                        writer.WriteU64(value.RetryAfterSecs);
                    }
                    break;
                }
                case Timeout value:
                {
                    writer.WriteU32(17);
                    {
                        writer.WriteU64(value.TimeoutMs);
                    }
                    break;
                }
                case MissingArtifact value:
                {
                    writer.WriteU32(18);
                    {
                        writer.WriteString(value.Message);
                    }
                    break;
                }
                case UnsupportedModelCapability value:
                {
                    writer.WriteU32(19);
                    {
                        writer.WriteString(value.Message);
                    }
                    break;
                }
                case UnsupportedBackendCapability value:
                {
                    writer.WriteU32(20);
                    {
                        writer.WriteString(value.Message);
                    }
                    break;
                }
                case InvalidImage value:
                {
                    writer.WriteU32(21);
                    {
                        writer.WriteString(value.Message);
                    }
                    break;
                }
                default:
                    throw new global::System.InvalidOperationException("Unknown XybridError variant");
            }
        }

        public sealed record ModelNotFound(string Id) : XybridError;

        public sealed record DirectoryNotFound(string Path) : XybridError;

        public sealed record MetadataNotFound(string Path) : XybridError;

        public sealed record MetadataInvalid(string Message) : XybridError;

        public sealed record LoadError(string Message) : XybridError;

        public sealed record InferenceError(string Message) : XybridError;

        public sealed record AbortedForCloudFallback(string Reason) : XybridError;

        public sealed record StreamingNotSupported() : XybridError;

        public sealed record NotLoaded() : XybridError;

        public sealed record ConfigError(string Message) : XybridError;

        public sealed record NetworkError(string Message) : XybridError;

        public sealed record Offline(string Message) : XybridError;

        public sealed record IoError(string Message) : XybridError;

        public sealed record CacheError(string Message) : XybridError;

        public sealed record PipelineError(string Message) : XybridError;

        public sealed record CircuitOpen(string Message) : XybridError;

        public sealed record RateLimited(ulong RetryAfterSecs) : XybridError;

        public sealed record Timeout(ulong TimeoutMs) : XybridError;

        public sealed record MissingArtifact(string Message) : XybridError;

        public sealed record UnsupportedModelCapability(string Message) : XybridError;

        public sealed record UnsupportedBackendCapability(string Message) : XybridError;

        public sealed record InvalidImage(string Message) : XybridError;

    }


    public sealed class XybridErrorException : global::System.Exception
    {
        public XybridError Error { get; }

        public XybridErrorException(XybridError error) : base(error.ToString())
        {
            Error = error;
        }
    }
}