// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System.Runtime.InteropServices;

namespace XybridBolt
{
    /// <summary>
    /// A rolling partial transcript from live microphone audio.
    /// </summary>
    public readonly struct XybridAsrPartialResult
    {
        public XybridAsrPartialResult(string Text, bool IsStable, ulong ChunkIndex, ulong AudioDurationMs) { this.Text = Text; this.IsStable = IsStable; this.ChunkIndex = ChunkIndex; this.AudioDurationMs = AudioDurationMs; }
        public string Text { get; }
        public bool IsStable { get; }
        public ulong ChunkIndex { get; }
        public ulong AudioDurationMs { get; }

        internal static XybridAsrPartialResult Decode(WireReader reader) =>
            new XybridAsrPartialResult(
                reader.ReadString(),
                reader.ReadBool(),
                reader.ReadU64(),
                reader.ReadU64()
            );

        internal void Encode(WireWriter writer)
        {
            {
                writer.WriteString(this.Text);
            }
            {
                writer.WriteBool(this.IsStable);
            }
            {
                writer.WriteU64(this.ChunkIndex);
            }
            {
                writer.WriteU64(this.AudioDurationMs);
            }
        }

    }
}