// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

namespace XybridBolt
{
    /// <summary>
    /// Lifecycle of the background download behind a speculative load.
    /// </summary>
    public enum XybridDownloadState : int
    {
        Downloading = 0,
        Ready = 1,
        /// <summary>
        /// Download failed; the cloud keeps serving and `isLoaded` never flips.
        /// </summary>
        Failed = 2
    }
}