// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System.Runtime.InteropServices;

namespace XybridBolt
{
    /// <summary>
    /// Configuration for a live ASR session.
    ///
    /// The model is not named here — it comes from the loaded `XybridModel` the
    /// session is opened on. This only configures *how* the audio is chunked.
    /// </summary>
    /// <param name="SampleRate">
    /// Sample rate of the audio you will feed. Must be 16000; the ASR
    /// backends are fixed there, so anything else is rejected rather than
    /// silently resampled.
    /// </param>
    /// <param name="Vad">Voice-activity-detection mode.</param>
    /// <param name="VadThreshold">VAD sensitivity, 0.0–1.0. Ignored when `vad` is `Off`.</param>
    /// <param name="Language">Language hint (e.g. `"en"`); null uses the model default.</param>
    /// <param name="AudioCtx">Whisper encoder context in mel frames; null uses the model default.</param>
    public readonly struct XybridStreamingConfig
    {
        public XybridStreamingConfig(uint SampleRate, XybridVadMode Vad, float VadThreshold, string? Language, uint? AudioCtx) { this.SampleRate = SampleRate; this.Vad = Vad; this.VadThreshold = VadThreshold; this.Language = Language; this.AudioCtx = AudioCtx; }
        public uint SampleRate { get; }
        public XybridVadMode Vad { get; }
        public float VadThreshold { get; }
        public string? Language { get; }
        public uint? AudioCtx { get; }

        internal static XybridStreamingConfig Decode(WireReader reader) =>
            new XybridStreamingConfig(
                reader.ReadU32(),
                XybridVadMode.Decode(reader),
                reader.ReadF32(),
                reader.ReadU8() == 0 ? default(string?) : reader.ReadString(),
                reader.ReadU8() == 0 ? default(uint?) : reader.ReadU32()
            );

        internal void Encode(WireWriter writer)
        {
            {
                writer.WriteU32(this.SampleRate);
            }
            {
                this.Vad.Encode(writer);
            }
            {
                writer.WriteF32(this.VadThreshold);
            }
            {
                if (this.Language is { } boltffiValue0)
                {
                    writer.WriteU8(1);
                    writer.WriteString(boltffiValue0);
                }
                else
                {
                    writer.WriteU8(0);
                }
            }
            {
                if (this.AudioCtx is { } boltffiValue0)
                {
                    writer.WriteU8(1);
                    writer.WriteU32(boltffiValue0);
                }
                else
                {
                    writer.WriteU8(0);
                }
            }
        }

    }
}