// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System.Runtime.InteropServices;

namespace XybridBolt
{
    public readonly struct XybridCacheStatus
    {
        public XybridCacheStatus(ulong TotalSizeBytes, uint EntryCount, uint ModelCount, uint ExtractedModelCount, string CacheRoot) { this.TotalSizeBytes = TotalSizeBytes; this.EntryCount = EntryCount; this.ModelCount = ModelCount; this.ExtractedModelCount = ExtractedModelCount; this.CacheRoot = CacheRoot; }
        public ulong TotalSizeBytes { get; }
        public uint EntryCount { get; }
        public uint ModelCount { get; }
        public uint ExtractedModelCount { get; }
        public string CacheRoot { get; }

        internal static XybridCacheStatus Decode(WireReader reader) =>
            new XybridCacheStatus(
                reader.ReadU64(),
                reader.ReadU32(),
                reader.ReadU32(),
                reader.ReadU32(),
                reader.ReadString()
            );

        internal void Encode(WireWriter writer)
        {
            {
                writer.WriteU64(this.TotalSizeBytes);
            }
            {
                writer.WriteU32(this.EntryCount);
            }
            {
                writer.WriteU32(this.ModelCount);
            }
            {
                writer.WriteU32(this.ExtractedModelCount);
            }
            {
                writer.WriteString(this.CacheRoot);
            }
        }

    }
}