// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System.Runtime.InteropServices;

namespace XybridBolt
{
    /// <param name="Grammar">
    /// Optional GBNF grammar constraining generation to structured output
    /// (local llama backend only). Produce one from a JSON Schema with
    /// [`json_schema_to_gbnf`], or pass raw GBNF. Appended last: `#[data]`
    /// PODs serialize by field order across the FFI boundary.
    /// </param>
    public readonly struct XybridGenerationConfig
    {
        public XybridGenerationConfig(uint? MaxTokens, float? Temperature, float? TopP, float? MinP, uint? TopK, float? RepetitionPenalty, string[] StopSequences, string? Grammar) { this.MaxTokens = MaxTokens; this.Temperature = Temperature; this.TopP = TopP; this.MinP = MinP; this.TopK = TopK; this.RepetitionPenalty = RepetitionPenalty; this.StopSequences = StopSequences; this.Grammar = Grammar; }
        public uint? MaxTokens { get; }
        public float? Temperature { get; }
        public float? TopP { get; }
        public float? MinP { get; }
        public uint? TopK { get; }
        public float? RepetitionPenalty { get; }
        public string[] StopSequences { get; }
        public string? Grammar { get; }

        internal static XybridGenerationConfig Decode(WireReader reader) =>
            new XybridGenerationConfig(
                reader.ReadU8() == 0 ? default(uint?) : reader.ReadU32(),
                reader.ReadU8() == 0 ? default(float?) : reader.ReadF32(),
                reader.ReadU8() == 0 ? default(float?) : reader.ReadF32(),
                reader.ReadU8() == 0 ? default(float?) : reader.ReadF32(),
                reader.ReadU8() == 0 ? default(uint?) : reader.ReadU32(),
                reader.ReadU8() == 0 ? default(float?) : reader.ReadF32(),
                reader.ReadArray(reader => reader.ReadString()),
                reader.ReadU8() == 0 ? default(string?) : reader.ReadString()
            );

        internal void Encode(WireWriter writer)
        {
            {
                if (this.MaxTokens is { } boltffiValue0)
                {
                    writer.WriteU8(1);
                    writer.WriteU32(boltffiValue0);
                }
                else
                {
                    writer.WriteU8(0);
                }
            }
            {
                if (this.Temperature is { } boltffiValue0)
                {
                    writer.WriteU8(1);
                    writer.WriteF32(boltffiValue0);
                }
                else
                {
                    writer.WriteU8(0);
                }
            }
            {
                if (this.TopP is { } boltffiValue0)
                {
                    writer.WriteU8(1);
                    writer.WriteF32(boltffiValue0);
                }
                else
                {
                    writer.WriteU8(0);
                }
            }
            {
                if (this.MinP is { } boltffiValue0)
                {
                    writer.WriteU8(1);
                    writer.WriteF32(boltffiValue0);
                }
                else
                {
                    writer.WriteU8(0);
                }
            }
            {
                if (this.TopK is { } boltffiValue0)
                {
                    writer.WriteU8(1);
                    writer.WriteU32(boltffiValue0);
                }
                else
                {
                    writer.WriteU8(0);
                }
            }
            {
                if (this.RepetitionPenalty is { } boltffiValue0)
                {
                    writer.WriteU8(1);
                    writer.WriteF32(boltffiValue0);
                }
                else
                {
                    writer.WriteU8(0);
                }
            }
            {
                writer.WriteU32(checked((uint)this.StopSequences.Length));
                foreach (var boltffiValue0 in this.StopSequences)
                {
                    writer.WriteString(boltffiValue0);
                }
            }
            {
                if (this.Grammar is { } boltffiValue0)
                {
                    writer.WriteU8(1);
                    writer.WriteString(boltffiValue0);
                }
                else
                {
                    writer.WriteU8(0);
                }
            }
        }

    }
}