// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

namespace XybridBolt
{
    public sealed partial class XybridConversationContext : global::System.IDisposable
    {
        private long handle;

        internal ulong Handle => unchecked((ulong)(ulong)global::System.Threading.Interlocked.Read(ref handle));

        internal XybridConversationContext(ulong handle)
        {
            if (handle == 0) throw new global::System.ArgumentException("handle must not be zero", nameof(handle));
            this.handle = unchecked((long)(ulong)handle);
        }

        /// <summary>
        /// Create an empty conversation context (fresh id).
        /// </summary>
        public XybridConversationContext()
            : this(BoltFfiNew().TakeHandle()) { }


        private static XybridConversationContext BoltFfiNew()
        {
            ulong boltffiHandle = NativeMethods.NativeXybridConversationContextNew();
            return boltffiHandle == 0 ? throw new global::System.InvalidOperationException("BoltFFI returned a null XybridConversationContext handle") : new XybridConversationContext(boltffiHandle);
        }



        /// <summary>
        /// Create a context with a caller-supplied id (for telemetry correlation
        /// across turns).
        /// </summary>
        public static XybridConversationContext WithId(string id)
        {
            WireWriter idWriter = new WireWriter();
            {
                idWriter.WriteString(id);
            }
            byte[] idBytes = idWriter.ToArray();
            ulong boltffiHandle = NativeMethods.NativeXybridConversationContextWithId(idBytes, (nuint)idBytes.Length);
            return boltffiHandle == 0 ? throw new global::System.InvalidOperationException("BoltFFI returned a null XybridConversationContext handle") : new XybridConversationContext(boltffiHandle);
        }


        /// <summary>
        /// Append a turn — typically a user or assistant message envelope.
        /// </summary>
        public void Push(global::XybridBolt.XybridEnvelope envelope)
        {
            ThrowIfDisposed();
            WireWriter envelopeWriter = new WireWriter();
            {
                envelope.Encode(envelopeWriter);
            }
            byte[] envelopeBytes = envelopeWriter.ToArray();
            FfiBuf boltffiErrorBuffer = NativeMethods.NativeXybridConversationContextPush(this.Handle, envelopeBytes, (nuint)envelopeBytes.Length);
            if (boltffiErrorBuffer.ptr != 0)
            {
                try
                {
                    WireReader boltffiErrorReader = new WireReader(boltffiErrorBuffer);
                    throw new global::XybridBolt.XybridErrorException(global::XybridBolt.XybridError.Decode(boltffiErrorReader));
                }
                finally
                {
                    NativeMethods.FreeBuf(boltffiErrorBuffer);
                }
            }
        }


        /// <summary>
        /// Set the persistent system-prompt envelope (survives [`clear`](Self::clear)).
        /// </summary>
        public void SetSystem(global::XybridBolt.XybridEnvelope envelope)
        {
            ThrowIfDisposed();
            WireWriter envelopeWriter = new WireWriter();
            {
                envelope.Encode(envelopeWriter);
            }
            byte[] envelopeBytes = envelopeWriter.ToArray();
            FfiBuf boltffiErrorBuffer = NativeMethods.NativeXybridConversationContextSetSystem(this.Handle, envelopeBytes, (nuint)envelopeBytes.Length);
            if (boltffiErrorBuffer.ptr != 0)
            {
                try
                {
                    WireReader boltffiErrorReader = new WireReader(boltffiErrorBuffer);
                    throw new global::XybridBolt.XybridErrorException(global::XybridBolt.XybridError.Decode(boltffiErrorReader));
                }
                finally
                {
                    NativeMethods.FreeBuf(boltffiErrorBuffer);
                }
            }
        }


        /// <summary>
        /// Drop the history; the system envelope (if any) is preserved.
        /// </summary>
        public void Clear()
        {
            ThrowIfDisposed();
            FfiStatus status = NativeMethods.NativeXybridConversationContextClear(this.Handle);
            if (status.code != 0)
            {
                throw new global::System.InvalidOperationException($"BoltFFI call failed with status code {status.code}");
            }
        }


        /// <summary>
        /// The context id.
        /// </summary>
        public string Id()
        {
            ThrowIfDisposed();
            FfiBuf boltffiResultBuffer = NativeMethods.NativeXybridConversationContextId(this.Handle);
            try
            {
                WireReader resultReader = new WireReader(boltffiResultBuffer);
                return resultReader.ReadString();
            }
            finally
            {
                NativeMethods.FreeBuf(boltffiResultBuffer);
            }
        }


        /// <summary>
        /// Number of history turns (excludes the system envelope).
        /// </summary>
        public uint HistoryLen()
        {
            ThrowIfDisposed();
            return NativeMethods.NativeXybridConversationContextHistoryLen(this.Handle);
        }


        /// <summary>
        /// Whether a persistent system-prompt envelope is set.
        /// </summary>
        public bool HasSystem()
        {
            ThrowIfDisposed();
            return NativeMethods.NativeXybridConversationContextHasSystem(this.Handle);
        }


        /// <summary>
        /// Set the max history length before FIFO pruning.
        /// </summary>
        public void SetMaxHistoryLen(uint len)
        {
            ThrowIfDisposed();
            FfiStatus status = NativeMethods.NativeXybridConversationContextSetMaxHistoryLen(this.Handle, len);
            if (status.code != 0)
            {
                throw new global::System.InvalidOperationException($"BoltFFI call failed with status code {status.code}");
            }
        }


        private ulong TakeHandle() => unchecked((ulong)(ulong)global::System.Threading.Interlocked.Exchange(ref handle, 0));

        private void ThrowIfDisposed()
        {
            if (global::System.Threading.Interlocked.Read(ref handle) == 0)
                throw new global::System.ObjectDisposedException(nameof(XybridConversationContext));
        }

        private void Release()
        {
            ulong released = unchecked((ulong)(ulong)global::System.Threading.Interlocked.Exchange(ref handle, 0));
            if (released != 0) NativeMethods.NativeXybridConversationContextRelease(released);
        }

        ~XybridConversationContext() => Release();

        public void Dispose()
        {
            Release();
            global::System.GC.SuppressFinalize(this);
        }
    }
}