// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System.Runtime.InteropServices;

namespace XybridBolt
{
    /// <summary>
    /// A tool (function) the model may ask to call.
    ///
    /// `parameters_json` is the JSON Schema for the arguments, carried as a JSON
    /// string because no binding generator can describe an arbitrary JSON tree.
    /// </summary>
    public readonly struct XybridToolDefinition
    {
        public XybridToolDefinition(string Name, string Description, string ParametersJson) { this.Name = Name; this.Description = Description; this.ParametersJson = ParametersJson; }
        public string Name { get; }
        public string Description { get; }
        public string ParametersJson { get; }

        internal static XybridToolDefinition Decode(WireReader reader) =>
            new XybridToolDefinition(
                reader.ReadString(),
                reader.ReadString(),
                reader.ReadString()
            );

        internal void Encode(WireWriter writer)
        {
            {
                writer.WriteString(this.Name);
            }
            {
                writer.WriteString(this.Description);
            }
            {
                writer.WriteString(this.ParametersJson);
            }
        }

    }
}