// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System;
using System.Text;

namespace XybridBolt
{
    /// <summary>
    /// Single metadata key/value entry. BoltFFI doesn't auto-derive
    /// `WireEncode` for `HashMap&lt;String, String&gt;`, so we expose metadata as
    /// `Vec&lt;XybridMetadataEntry&gt;`. The conversion back to `HashMap` happens
    /// at the facade boundary inside [`XybridEnvelope::into`].
    /// </summary>
    public readonly struct XybridMetadataEntry
    {
        public XybridMetadataEntry(string Key, string Value) { this.Key = Key; this.Value = Value; }
        public string Key { get; }
        public string Value { get; }

        internal static XybridMetadataEntry Decode(WireReader reader) =>
            new XybridMetadataEntry(
                reader.ReadString(),
                reader.ReadString()
            );

        internal int WireEncodedSize() =>
            (4 + Encoding.UTF8.GetByteCount(this.Key)) +
            (4 + Encoding.UTF8.GetByteCount(this.Value));

        internal void WireEncodeTo(WireWriter wire)
        {
            wire.WriteString(this.Key);
            wire.WriteString(this.Value);
        }
    }
}