// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

namespace XybridBolt
{
    public sealed class XybridCancellationToken : global::System.IDisposable
    {
        private long handle;

        internal ulong Handle => unchecked((ulong)(ulong)global::System.Threading.Interlocked.Read(ref handle));

        internal XybridCancellationToken(ulong handle)
        {
            if (handle == 0) throw new global::System.ArgumentException("handle must not be zero", nameof(handle));
            this.handle = unchecked((long)(ulong)handle);
        }

        /// <summary>
        /// Create a fresh, non-cancelled token.
        /// </summary>
        public XybridCancellationToken()
            : this(BoltFfiNew().TakeHandle()) { }


        private static XybridCancellationToken BoltFfiNew()
        {
            ulong boltffiHandle = NativeMethods.NativeXybridCancellationTokenNew();
            return boltffiHandle == 0 ? throw new global::System.InvalidOperationException("BoltFFI returned a null XybridCancellationToken handle") : new XybridCancellationToken(boltffiHandle);
        }


        /// <summary>
        /// Request cooperative cancellation. Idempotent and thread-safe.
        /// </summary>
        public void Cancel()
        {
            ThrowIfDisposed();
            FfiStatus status = NativeMethods.NativeXybridCancellationTokenCancel(this.Handle);
            if (status.code != 0)
            {
                throw new global::System.InvalidOperationException($"BoltFFI call failed with status code {status.code}");
            }
        }


        /// <summary>
        /// Whether cancellation has been requested.
        /// </summary>
        public bool IsCancelled()
        {
            ThrowIfDisposed();
            return NativeMethods.NativeXybridCancellationTokenIsCancelled(this.Handle);
        }


        private ulong TakeHandle() => unchecked((ulong)(ulong)global::System.Threading.Interlocked.Exchange(ref handle, 0));

        private void ThrowIfDisposed()
        {
            if (global::System.Threading.Interlocked.Read(ref handle) == 0)
                throw new global::System.ObjectDisposedException(nameof(XybridCancellationToken));
        }

        private void Release()
        {
            ulong released = unchecked((ulong)(ulong)global::System.Threading.Interlocked.Exchange(ref handle, 0));
            if (released != 0) NativeMethods.NativeXybridCancellationTokenRelease(released);
        }

        ~XybridCancellationToken() => Release();

        public void Dispose()
        {
            Release();
            global::System.GC.SuppressFinalize(this);
        }
    }
}