// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

namespace XybridBolt
{
    public sealed class XybridTelemetryConfig : global::System.IDisposable
    {
        private long handle;

        internal ulong Handle => unchecked((ulong)(ulong)global::System.Threading.Interlocked.Read(ref handle));

        internal XybridTelemetryConfig(ulong handle)
        {
            if (handle == 0) throw new global::System.ArgumentException("handle must not be zero", nameof(handle));
            this.handle = unchecked((long)(ulong)handle);
        }

        /// <summary>
        /// A new config bound to the default ingest endpoint and the given API key.
        /// </summary>
        public XybridTelemetryConfig(string apiKey)
            : this(BoltFfiNew(apiKey).TakeHandle()) { }


        private static XybridTelemetryConfig BoltFfiNew(string apiKey)
        {
            WireWriter apiKeyWriter = new WireWriter();
            {
                apiKeyWriter.WriteString(apiKey);
            }
            byte[] apiKeyBytes = apiKeyWriter.ToArray();
            ulong boltffiHandle = NativeMethods.NativeXybridTelemetryConfigNew(apiKeyBytes, (nuint)apiKeyBytes.Length);
            return boltffiHandle == 0 ? throw new global::System.InvalidOperationException("BoltFFI returned a null XybridTelemetryConfig handle") : new XybridTelemetryConfig(boltffiHandle);
        }


        /// <summary>
        /// Override the ingest endpoint (self-hosted collector / non-prod).
        /// </summary>
        public void SetEndpoint(string endpoint)
        {
            ThrowIfDisposed();
            WireWriter endpointWriter = new WireWriter();
            {
                endpointWriter.WriteString(endpoint);
            }
            byte[] endpointBytes = endpointWriter.ToArray();
            FfiStatus status = NativeMethods.NativeXybridTelemetryConfigSetEndpoint(this.Handle, endpointBytes, (nuint)endpointBytes.Length);
            if (status.code != 0)
            {
                throw new global::System.InvalidOperationException($"BoltFFI call failed with status code {status.code}");
            }
        }


        /// <summary>
        /// Set the app version reported with every event.
        /// </summary>
        public void SetAppVersion(string version)
        {
            ThrowIfDisposed();
            WireWriter versionWriter = new WireWriter();
            {
                versionWriter.WriteString(version);
            }
            byte[] versionBytes = versionWriter.ToArray();
            FfiStatus status = NativeMethods.NativeXybridTelemetryConfigSetAppVersion(this.Handle, versionBytes, (nuint)versionBytes.Length);
            if (status.code != 0)
            {
                throw new global::System.InvalidOperationException($"BoltFFI call failed with status code {status.code}");
            }
        }


        /// <summary>
        /// Set the human-friendly device label reported with every event.
        /// </summary>
        public void SetDeviceLabel(string label)
        {
            ThrowIfDisposed();
            WireWriter labelWriter = new WireWriter();
            {
                labelWriter.WriteString(label);
            }
            byte[] labelBytes = labelWriter.ToArray();
            FfiStatus status = NativeMethods.NativeXybridTelemetryConfigSetDeviceLabel(this.Handle, labelBytes, (nuint)labelBytes.Length);
            if (status.code != 0)
            {
                throw new global::System.InvalidOperationException($"BoltFFI call failed with status code {status.code}");
            }
        }


        /// <summary>
        /// Attach an app-provided device attribute (stored under `device.custom`).
        /// </summary>
        public void SetDeviceAttribute(string key, string value)
        {
            ThrowIfDisposed();
            WireWriter keyWriter = new WireWriter();
            {
                keyWriter.WriteString(key);
            }
            byte[] keyBytes = keyWriter.ToArray();
            WireWriter valueWriter = new WireWriter();
            {
                valueWriter.WriteString(value);
            }
            byte[] valueBytes = valueWriter.ToArray();
            FfiStatus status = NativeMethods.NativeXybridTelemetryConfigSetDeviceAttribute(this.Handle, keyBytes, (nuint)keyBytes.Length, valueBytes, (nuint)valueBytes.Length);
            if (status.code != 0)
            {
                throw new global::System.InvalidOperationException($"BoltFFI call failed with status code {status.code}");
            }
        }


        /// <summary>
        /// Set the number of events buffered before a flush.
        /// </summary>
        public void SetBatchSize(uint batchSize)
        {
            ThrowIfDisposed();
            FfiStatus status = NativeMethods.NativeXybridTelemetryConfigSetBatchSize(this.Handle, batchSize);
            if (status.code != 0)
            {
                throw new global::System.InvalidOperationException($"BoltFFI call failed with status code {status.code}");
            }
        }


        /// <summary>
        /// Set the background flush interval, in seconds.
        /// </summary>
        public void SetFlushIntervalSecs(uint secs)
        {
            ThrowIfDisposed();
            FfiStatus status = NativeMethods.NativeXybridTelemetryConfigSetFlushIntervalSecs(this.Handle, secs);
            if (status.code != 0)
            {
                throw new global::System.InvalidOperationException($"BoltFFI call failed with status code {status.code}");
            }
        }


        /// <summary>
        /// Start the process-global telemetry exporter from this config.
        ///
        /// Consumes the config: subsequent setters no-op and a second `init` on the
        /// same handle errors. Modeled as a method (not a free `telemetry_init`)
        /// because boltffi 0.25.3 drops free functions that take a handle
        /// parameter, but lowers a handle self-method fine (same reason the
        /// generated `run` lives on `XybridModel`).
        ///
        /// # Errors
        /// Errors if this config was already consumed, or if telemetry is already
        /// initialized without an intervening [`telemetry_shutdown`].
        /// </summary>
        public void Init()
        {
            ThrowIfDisposed();
            FfiBuf boltffiErrorBuffer = NativeMethods.NativeXybridTelemetryConfigInit(this.Handle);
            if (boltffiErrorBuffer.ptr != 0)
            {
                try
                {
                    WireReader boltffiErrorReader = new WireReader(boltffiErrorBuffer);
                    throw new global::XybridBolt.XybridErrorException(global::XybridBolt.XybridError.Decode(boltffiErrorReader));
                }
                finally
                {
                    NativeMethods.FreeBuf(boltffiErrorBuffer);
                }
            }
        }


        private ulong TakeHandle() => unchecked((ulong)(ulong)global::System.Threading.Interlocked.Exchange(ref handle, 0));

        private void ThrowIfDisposed()
        {
            if (global::System.Threading.Interlocked.Read(ref handle) == 0)
                throw new global::System.ObjectDisposedException(nameof(XybridTelemetryConfig));
        }

        private void Release()
        {
            ulong released = unchecked((ulong)(ulong)global::System.Threading.Interlocked.Exchange(ref handle, 0));
            if (released != 0) NativeMethods.NativeXybridTelemetryConfigRelease(released);
        }

        ~XybridTelemetryConfig() => Release();

        public void Dispose()
        {
            Release();
            global::System.GC.SuppressFinalize(this);
        }
    }
}