// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

namespace XybridBolt
{
    public sealed class XybridAsrStreamSession : global::System.IDisposable
    {
        private long handle;

        internal ulong Handle => unchecked((ulong)(ulong)global::System.Threading.Interlocked.Read(ref handle));

        internal XybridAsrStreamSession(ulong handle)
        {
            if (handle == 0) throw new global::System.ArgumentException("handle must not be zero", nameof(handle));
            this.handle = unchecked((long)(ulong)handle);
        }

        /// <summary>
        /// Queue mono 16 kHz PCM f32 samples.
        /// </summary>
        public void Feed(float[] samples)
        {
            ThrowIfDisposed();
            FfiBuf boltffiErrorBuffer = NativeMethods.NativeXybridAsrStreamSessionFeed(this.Handle, samples, (nuint)samples.Length);
            if (boltffiErrorBuffer.ptr != 0)
            {
                try
                {
                    WireReader boltffiErrorReader = new WireReader(boltffiErrorBuffer);
                    throw new global::XybridBolt.XybridErrorException(global::XybridBolt.XybridError.Decode(boltffiErrorReader));
                }
                finally
                {
                    NativeMethods.FreeBuf(boltffiErrorBuffer);
                }
            }
        }


        /// <summary>
        /// Block until the next distinct rolling transcript is available.
        ///
        /// Returns `None` once the session is closed. Flushing finalizes the
        /// current utterance but keeps the session available for `reset` and
        /// reuse. Platform wrappers expose this pull operation as
        /// `AsyncThrowingStream` / `Flow` where appropriate.
        /// </summary>
        public global::XybridBolt.XybridAsrPartialResult? Next()
        {
            ThrowIfDisposed();
            FfiBuf boltffiErrorBuffer = NativeMethods.NativeXybridAsrStreamSessionNext(this.Handle, out FfiBuf boltffiResultBuffer);
            if (boltffiErrorBuffer.ptr != 0)
            {
                try
                {
                    WireReader boltffiErrorReader = new WireReader(boltffiErrorBuffer);
                    throw new global::XybridBolt.XybridErrorException(global::XybridBolt.XybridError.Decode(boltffiErrorReader));
                }
                finally
                {
                    NativeMethods.FreeBuf(boltffiErrorBuffer);
                }
            }
            try
            {
                WireReader resultReader = new WireReader(boltffiResultBuffer);
                return resultReader.ReadU8() == 0 ? default(global::XybridBolt.XybridAsrPartialResult?) : global::XybridBolt.XybridAsrPartialResult.Decode(resultReader);
            }
            finally
            {
                NativeMethods.FreeBuf(boltffiResultBuffer);
            }
        }


        /// <summary>
        /// Drain queued audio, finalize the session, and return the full transcript.
        /// </summary>
        public global::XybridBolt.XybridAsrTranscriptionResult Flush()
        {
            ThrowIfDisposed();
            FfiBuf boltffiErrorBuffer = NativeMethods.NativeXybridAsrStreamSessionFlush(this.Handle, out FfiBuf boltffiResultBuffer);
            if (boltffiErrorBuffer.ptr != 0)
            {
                try
                {
                    WireReader boltffiErrorReader = new WireReader(boltffiErrorBuffer);
                    throw new global::XybridBolt.XybridErrorException(global::XybridBolt.XybridError.Decode(boltffiErrorReader));
                }
                finally
                {
                    NativeMethods.FreeBuf(boltffiErrorBuffer);
                }
            }
            try
            {
                WireReader resultReader = new WireReader(boltffiResultBuffer);
                return global::XybridBolt.XybridAsrTranscriptionResult.Decode(resultReader);
            }
            finally
            {
                NativeMethods.FreeBuf(boltffiResultBuffer);
            }
        }


        /// <summary>
        /// Clear audio and transcript state without reloading the model.
        /// </summary>
        public void Reset()
        {
            ThrowIfDisposed();
            FfiBuf boltffiErrorBuffer = NativeMethods.NativeXybridAsrStreamSessionReset(this.Handle);
            if (boltffiErrorBuffer.ptr != 0)
            {
                try
                {
                    WireReader boltffiErrorReader = new WireReader(boltffiErrorBuffer);
                    throw new global::XybridBolt.XybridErrorException(global::XybridBolt.XybridError.Decode(boltffiErrorReader));
                }
                finally
                {
                    NativeMethods.FreeBuf(boltffiErrorBuffer);
                }
            }
        }


        /// <summary>
        /// Stop the worker and end the partial-result stream.
        ///
        /// Named `stop` because generated handles already reserve `close` for
        /// releasing the foreign handle itself.
        /// </summary>
        public void Stop()
        {
            ThrowIfDisposed();
            FfiBuf boltffiErrorBuffer = NativeMethods.NativeXybridAsrStreamSessionStop(this.Handle);
            if (boltffiErrorBuffer.ptr != 0)
            {
                try
                {
                    WireReader boltffiErrorReader = new WireReader(boltffiErrorBuffer);
                    throw new global::XybridBolt.XybridErrorException(global::XybridBolt.XybridError.Decode(boltffiErrorReader));
                }
                finally
                {
                    NativeMethods.FreeBuf(boltffiErrorBuffer);
                }
            }
        }


        private ulong TakeHandle() => unchecked((ulong)(ulong)global::System.Threading.Interlocked.Exchange(ref handle, 0));

        private void ThrowIfDisposed()
        {
            if (global::System.Threading.Interlocked.Read(ref handle) == 0)
                throw new global::System.ObjectDisposedException(nameof(XybridAsrStreamSession));
        }

        private void Release()
        {
            ulong released = unchecked((ulong)(ulong)global::System.Threading.Interlocked.Exchange(ref handle, 0));
            if (released != 0) NativeMethods.NativeXybridAsrStreamSessionRelease(released);
        }

        ~XybridAsrStreamSession() => Release();

        public void Dispose()
        {
            Release();
            global::System.GC.SuppressFinalize(this);
        }
    }
}