// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System.Runtime.InteropServices;

namespace XybridBolt
{
    /// <summary>
    /// Inference output. Named `XybridResult` (not `XybridInferenceResult`)
    /// to match the existing uniffi-generated Kotlin/Swift name — the iOS
    /// example references `XybridResult` directly.
    /// </summary>
    /// <param name="ExecutionTarget">
    /// Where the answer actually came from. Cloud fallback keeps `model_id`
    /// identical on both legs, so this is the only way to tell them apart.
    /// </param>
    /// <param name="ToolCalls">
    /// Tool calls the model emitted this turn. Empty unless the request
    /// offered tools via [`XybridGenerationConfig::tools`]. Appended last:
    /// `#[data]` PODs serialize by field order across the FFI boundary.
    /// </param>
    public readonly struct XybridResult
    {
        public XybridResult(XybridEnvelope Envelope, XybridOutputType OutputType, string ModelId, uint LatencyMs, XybridExecutionTarget ExecutionTarget, XybridInferenceMetrics Metrics, XybridToolCall[] ToolCalls) { this.Envelope = Envelope; this.OutputType = OutputType; this.ModelId = ModelId; this.LatencyMs = LatencyMs; this.ExecutionTarget = ExecutionTarget; this.Metrics = Metrics; this.ToolCalls = ToolCalls; }
        public XybridEnvelope Envelope { get; }
        public XybridOutputType OutputType { get; }
        public string ModelId { get; }
        public uint LatencyMs { get; }
        public XybridExecutionTarget ExecutionTarget { get; }
        public XybridInferenceMetrics Metrics { get; }
        public XybridToolCall[] ToolCalls { get; }

        internal static XybridResult Decode(WireReader reader) =>
            new XybridResult(
                XybridEnvelope.Decode(reader),
                (XybridOutputType)reader.ReadI32(),
                reader.ReadString(),
                reader.ReadU32(),
                (XybridExecutionTarget)reader.ReadI32(),
                XybridInferenceMetrics.Decode(reader),
                reader.ReadArray(reader => XybridToolCall.Decode(reader))
            );

        internal void Encode(WireWriter writer)
        {
            {
                this.Envelope.Encode(writer);
            }
            {
                writer.WriteI32((int)this.OutputType);
            }
            {
                writer.WriteString(this.ModelId);
            }
            {
                writer.WriteU32(this.LatencyMs);
            }
            {
                writer.WriteI32((int)this.ExecutionTarget);
            }
            {
                this.Metrics.Encode(writer);
            }
            {
                writer.WriteU32(checked((uint)this.ToolCalls.Length));
                foreach (var boltffiValue0 in this.ToolCalls)
                {
                    boltffiValue0.Encode(writer);
                }
            }
        }

    }
}