#!/usr/bin/env bash
# natives-manifest.sh
#
# Regenerates crates/llama-cpp-sys/natives-manifest.txt — the file that lets a
# plain `cargo build` resolve a published llama.cpp slice with no oras, no env
# var, and no CMake. See the "Prebuilt natives" section of
# crates/llama-cpp-sys/build.rs for the consumer side.
#
# The manifest is the PUBLISHER's declaration. It records:
#   - the source identity every published slice was built from (pinned
#     llama.cpp commit + plain sha256 of wrapper.cpp, wrapper.h, build.rs), so
#     a consumer whose local sources differ skips the download instead of
#     linking a stale archive;
#   - one `slice` row per (target, feature-set) with the layer blob digest.
#
# Note what is NOT here: the publisher fingerprint from natives-fingerprint.sh.
# That fingerprint folds in the LOCAL cmake/cc/NDK versions, which is correct
# for build-cache parity and wrong for distribution — a consumer without cmake
# would compute a different key and always miss. Consumers select by target +
# features + ABI attributes; the publisher declares the digest.
#
# Usage: natives-manifest.sh [--allow-empty] <rows-dir> [output-file]
#
#   <rows-dir>    directory of row files, each ONE line:
#                   <target> <features> sha256:<hex> [min_glibc=X] [crt=Y]
#                 (build-natives.yml writes one per published matrix row)
#   [output-file] defaults to crates/llama-cpp-sys/natives-manifest.txt
#   --allow-empty write a header-only manifest when no rows are available.
#                 For refreshing the source fields by hand after a wrapper /
#                 build.rs edit; CI never passes it, because in CI an empty
#                 rows dir means the publish matrix failed and overwriting a
#                 good manifest with nothing would strand every consumer.
set -euo pipefail

ALLOW_EMPTY=0
if [ "${1:-}" = "--allow-empty" ]; then
  ALLOW_EMPTY=1
  shift
fi

ROWS_DIR="${1:?usage: natives-manifest.sh [--allow-empty] <rows-dir> [output-file]}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SYS="$ROOT/crates/llama-cpp-sys"
OUT="${2:-$SYS/natives-manifest.txt}"
PKG="${XYBRID_NATIVES_PKG:-ghcr.io/xybrid-ai/llama-natives}"

[ -d "$ROWS_DIR" ] || { echo "natives-manifest: no such rows dir: $ROWS_DIR" >&2; exit 1; }

# Portable SHA-256 (Linux `sha256sum`, macOS `shasum`), matching
# natives-fingerprint.sh.
sha256() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$@" | cut -d' ' -f1
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$@" | cut -d' ' -f1
  else
    echo "natives-manifest: no sha256sum/shasum found" >&2
    exit 1
  fi
}

LLAMA_SHA="$(grep -E 'const LLAMA_CPP_COMMIT' "$SYS/build.rs" | grep -oE '[0-9a-f]{40}')"
[ -n "$LLAMA_SHA" ] || { echo "natives-manifest: could not read LLAMA_CPP_COMMIT" >&2; exit 1; }

# These three are hashed as WHOLE FILES, deliberately: build.rs recomputes the
# same three hashes and compares them field by field. No combining formula
# means no way for the two implementations to drift apart.
WRAPPER_CPP="$(sha256 "$SYS/wrapper.cpp")"
WRAPPER_H="$(sha256 "$SYS/wrapper.h")"
BUILD_RS="$(sha256 "$SYS/build.rs")"

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# GENERATED by tools/scripts/natives-manifest.sh — do not edit by hand."
  echo "#"
  echo "# Published llama.cpp native slices. build.rs downloads the row matching"
  echo "# this build's target triple + feature set, verifies its sha256, and links"
  echo "# it instead of running cmake. Any mismatch falls back to a source build."
  echo "#"
  echo "# The four source fields below pin what the slices were built from. Edit"
  echo "# wrapper.cpp, wrapper.h, build.rs, or the llama.cpp pin without"
  echo "# republishing and every row here is ignored, by design."
  echo "version 1"
  echo "registry $PKG"
  echo "llama_commit $LLAMA_SHA"
  echo "wrapper_cpp $WRAPPER_CPP"
  echo "wrapper_h $WRAPPER_H"
  echo "build_rs $BUILD_RS"
} > "$TMP"

# Rows, sorted so the file is stable across runs (matrix job order is not).
# Collected into a file rather than piped straight into `sort`, so the count
# survives — a pipeline would run the loop in a subshell and lose it.
ROWS_TMP="$(mktemp)"
trap 'rm -f "$TMP" "$ROWS_TMP"' EXIT
for row in "$ROWS_DIR"/*; do
  [ -f "$row" ] || continue
  while read -r target features digest rest; do
    [ -n "${target:-}" ] || continue
    case "$digest" in
      sha256:*) ;;
      *) echo "natives-manifest: skipping malformed row in $row: $target $features $digest" >&2; continue ;;
    esac
    echo "slice $target $features $digest${rest:+ $rest}" >> "$ROWS_TMP"
  done < "$row"
done
rows="$(wc -l < "$ROWS_TMP" | tr -d ' ')"
LC_ALL=C sort "$ROWS_TMP" >> "$TMP"

if [ "$rows" -eq 0 ] && [ "$ALLOW_EMPTY" -eq 0 ]; then
  echo "natives-manifest: no slice rows found in $ROWS_DIR — refusing to write an empty manifest" >&2
  exit 1
fi

mv "$TMP" "$OUT"
rm -f "$ROWS_TMP"
trap - EXIT
echo "natives-manifest: wrote $OUT ($rows slices)"
