#!/usr/bin/env bash
# natives-manifest.sh
#
# Regenerates crates/llama-cpp-sys/natives-manifest.txt — the file that lets a
# plain `cargo build` resolve a published llama.cpp slice with no oras, no env
# var, and no CMake. See the "Prebuilt natives" section of
# crates/llama-cpp-sys/build.rs for the consumer side.
#
# The manifest is the PUBLISHER's declaration. It records:
#   - the source identity every published slice was built from (pinned
#     llama.cpp commit + plain sha256 of wrapper.cpp, wrapper.h, build.rs), so
#     a consumer whose local sources differ skips the download instead of
#     linking a stale archive;
#   - one `slice` row per (target, feature-set) with the layer blob digest.
#
# Note what is NOT here: the publisher fingerprint from natives-fingerprint.sh.
# That fingerprint folds in the LOCAL cmake/cc/NDK versions, which is correct
# for build-cache parity and wrong for distribution — a consumer without cmake
# would compute a different key and always miss. Consumers select by target +
# features + ABI attributes; the publisher declares the digest.
#
# Rows from the previous manifest are CARRIED FORWARD when the four source
# fields are unchanged and this run produced no row for that (target,
# features). A matrix row that flaked (runner outage, registry 5xx) must not
# turn into a PR that deletes a slice which is still published and still
# valid. When the source fields differ, old rows are dropped: the slices they
# name were built from other sources and build.rs would refuse them anyway.
#
# Usage: natives-manifest.sh [--allow-empty] <rows-dir> [output-file]
#
#   <rows-dir>    directory of row files, each ONE line:
#                   <target> <features> sha256:<hex> [min_glibc=X] [crt=Y]
#                 (build-natives.yml writes one per published matrix row)
#   [output-file] defaults to crates/llama-cpp-sys/natives-manifest.txt
#   --allow-empty write a header-only manifest when no rows are available.
#                 For refreshing the source fields by hand after a wrapper /
#                 build.rs edit; CI never passes it, because in CI an empty
#                 rows dir means the publish matrix failed and overwriting a
#                 good manifest with nothing would strand every consumer.
#
# Exit codes:
#   0  manifest written
#   2  nothing to do — rows dir absent or no new rows (CI treats as benign and
#      leaves the committed manifest untouched)
#   1  anything else: broken environment, unreadable sources. CI must NOT
#      swallow this, or a permanently failing regeneration looks like "no
#      rows published" forever while the manifest quietly goes stale.
set -euo pipefail

ALLOW_EMPTY=0
if [ "${1:-}" = "--allow-empty" ]; then
  ALLOW_EMPTY=1
  shift
fi

ROWS_DIR="${1:?usage: natives-manifest.sh [--allow-empty] <rows-dir> [output-file]}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SYS="$ROOT/crates/llama-cpp-sys"
OUT="${2:-$SYS/natives-manifest.txt}"
PKG="${XYBRID_NATIVES_PKG:-ghcr.io/xybrid-ai/llama-natives}"

if [ ! -d "$ROWS_DIR" ]; then
  if [ "$ALLOW_EMPTY" -eq 1 ]; then
    mkdir -p "$ROWS_DIR"
  else
    echo "natives-manifest: no rows dir at $ROWS_DIR — nothing published" >&2
    exit 2
  fi
fi

# Portable SHA-256 (Linux `sha256sum`, macOS `shasum`), matching
# natives-fingerprint.sh.
sha256() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$@" | cut -d' ' -f1
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$@" | cut -d' ' -f1
  else
    echo "natives-manifest: no sha256sum/shasum found" >&2
    exit 1
  fi
}

# `|| true` inside the substitution: under `set -e` a no-match grep would kill
# the script before the diagnostic below could print.
LLAMA_SHA="$(grep -E 'const LLAMA_CPP_COMMIT' "$SYS/build.rs" | grep -oE '[0-9a-f]{40}' || true)"
[ -n "$LLAMA_SHA" ] || { echo "natives-manifest: could not read LLAMA_CPP_COMMIT from $SYS/build.rs" >&2; exit 1; }

# These three are hashed as WHOLE FILES, deliberately: build.rs recomputes the
# same three hashes and compares them field by field. No combining formula
# means no way for the two implementations to drift apart.
WRAPPER_CPP="$(sha256 "$SYS/wrapper.cpp")"
WRAPPER_H="$(sha256 "$SYS/wrapper.h")"
BUILD_RS="$(sha256 "$SYS/build.rs")"

TMP="$(mktemp)"
ROWS_TMP="$(mktemp)"
trap 'rm -f "$TMP" "$ROWS_TMP"' EXIT

{
  echo "# GENERATED by tools/scripts/natives-manifest.sh — do not edit by hand."
  echo "#"
  echo "# Published llama.cpp native slices. build.rs downloads the row matching"
  echo "# this build's target triple + feature set, verifies its sha256, and links"
  echo "# it instead of running cmake. Any mismatch falls back to a source build."
  echo "#"
  echo "# The four source fields below pin what the slices were built from. Edit"
  echo "# wrapper.cpp, wrapper.h, build.rs, or the llama.cpp pin without"
  echo "# republishing and every row here is ignored, by design."
  echo "version 1"
  echo "registry $PKG"
  echo "llama_commit $LLAMA_SHA"
  echo "wrapper_cpp $WRAPPER_CPP"
  echo "wrapper_h $WRAPPER_H"
  echo "build_rs $BUILD_RS"
} > "$TMP"

# New rows from this run. Collected into a file rather than piped straight
# into `sort`, so the counts survive — a pipeline would run the loop in a
# subshell and lose them.
new_rows=0
for row in "$ROWS_DIR"/*; do
  [ -f "$row" ] || continue
  while read -r target features digest rest; do
    [ -n "${target:-}" ] || continue
    case "$digest" in
      sha256:*) ;;
      *) echo "natives-manifest: skipping malformed row in $row: $target $features $digest" >&2; continue ;;
    esac
    echo "slice $target $features $digest${rest:+ $rest}" >> "$ROWS_TMP"
    new_rows=$((new_rows + 1))
  done < "$row"
done

if [ "$new_rows" -eq 0 ] && [ "$ALLOW_EMPTY" -eq 0 ]; then
  echo "natives-manifest: no slice rows found in $ROWS_DIR — leaving $OUT untouched" >&2
  exit 2
fi

# Carry forward rows from the committed manifest that this run did not
# re-emit, but only if every source field matches — otherwise those slices
# were built from different sources and must go.
carried=0
if [ -f "$OUT" ]; then
  prev_field() { awk -v k="$1" '$1 == k { print $2; exit }' "$OUT"; }
  if [ "$(prev_field registry)" = "$PKG" ] \
     && [ "$(prev_field llama_commit)" = "$LLAMA_SHA" ] \
     && [ "$(prev_field wrapper_cpp)" = "$WRAPPER_CPP" ] \
     && [ "$(prev_field wrapper_h)" = "$WRAPPER_H" ] \
     && [ "$(prev_field build_rs)" = "$BUILD_RS" ]; then
    while read -r kind target features digest rest; do
      [ "${kind:-}" = "slice" ] || continue
      if grep -qE "^slice $target $features " "$ROWS_TMP"; then
        continue
      fi
      echo "slice $target $features $digest${rest:+ $rest}" >> "$ROWS_TMP"
      carried=$((carried + 1))
      echo "natives-manifest: carried forward $target $features (no row this run)" >&2
    done < "$OUT"
  else
    echo "natives-manifest: source fields changed — previous rows dropped" >&2
  fi
fi

# Sorted so the file is stable across runs (matrix job order is not).
LC_ALL=C sort "$ROWS_TMP" >> "$TMP"

mv "$TMP" "$OUT"
echo "natives-manifest: wrote $OUT ($new_rows new, $carried carried forward)"
