#!/usr/bin/env bash
# Materialize the BuildBuddy remote config that `.bazelrc` try-imports.
#
# This is the SINGLE SOURCE OF TRUTH for the RBE flags. It used to be a
# heredoc copy-pasted into 18 CI steps, which drifted: two build-unity jobs
# silently lost --remote_timeout / --jobs / --extra_execution_platforms, and
# the last of those is load-bearing (without it, RBE toolchain resolution
# falls back to whichever exec platform registers first).
#
# Writes two configs, both keyed off the same secret:
#
#   --config=remote        full remote execution + cache (Linux exec workers)
#   --config=remote-cache  cache ONLY, never remote execution — for Apple
#                          lanes, whose actions must run on the Mac (Xcode
#                          licensing) but can still share action results
#
# Defining both costs nothing: a config is inert until its --config flag is
# passed, so a Linux lane carrying `remote-cache` (or vice versa) is a no-op.
#
# Contract:
#   BUILDBUDDY_API_KEY set    -> writes the rc
#   BUILDBUDDY_API_KEY empty  -> writes nothing, exits 0
#
# The empty case is the fork path: no secret is exposed to fork PRs, so the
# build must fall back to local execution rather than fail authenticating.
# The step deliberately does NOT gate itself with `if:` in the workflow — it
# always runs and logs which path it took, so "RBE was skipped" is visible in
# the log instead of looking identical to a passing step.
#
# Optional argument: a config name to export as $REMOTE for later steps
# (empty when there's no key, so callers can pass "$REMOTE" through to
# bazelisk unconditionally). This is OPT-IN on purpose — exporting
# --config=remote into every job would silently arm remote EXECUTION on the
# Apple lanes, which must stay cache-only (Xcode actions have to run on the
# Mac). Jobs that want it ask for it by name.
#
# Usage (CI):
#   - name: Configure BuildBuddy remote config
#     env:
#       BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
#     run: tools/scripts/write-buildbuddy-rc.sh          # rc only
#     run: tools/scripts/write-buildbuddy-rc.sh remote   # rc + $REMOTE
#
# Override the destination with BUILDBUDDY_RC_PATH (used by the tests).
set -euo pipefail

RC_PATH="${BUILDBUDDY_RC_PATH:-.context/buildbuddy.bazelrc}"
EXPORT_CONFIG="${1:-}"

emit_remote_var() {
  # Only when a job asked for it, and only inside Actions.
  if [ -n "$EXPORT_CONFIG" ] && [ -n "${GITHUB_ENV:-}" ]; then
    echo "REMOTE=$1" >> "$GITHUB_ENV"
  fi
}

if [ -z "${BUILDBUDDY_API_KEY:-}" ]; then
  echo "BUILDBUDDY_API_KEY is empty (fork PR, or the secret is unset)."
  echo "Skipping the RBE config — Bazel will build locally."
  emit_remote_var ""
  exit 0
fi

mkdir -p "$(dirname "$RC_PATH")"

# Unquoted EOF on purpose: ${BUILDBUDDY_API_KEY} must expand.
cat > "$RC_PATH" <<EOF
# Generated by tools/scripts/write-buildbuddy-rc.sh — do not edit by hand.
# Gitignored: it carries the API key.

common:remote --bes_results_url=https://app.buildbuddy.io/invocation/
common:remote --bes_backend=grpcs://remote.buildbuddy.io
common:remote --remote_header=x-buildbuddy-api-key=${BUILDBUDDY_API_KEY}
common:remote --remote_cache=grpcs://remote.buildbuddy.io
common:remote --remote_executor=grpcs://remote.buildbuddy.io
common:remote --remote_cache_compression
common:remote --remote_download_toplevel
common:remote --remote_timeout=600
common:remote --jobs=200
common:remote --extra_execution_platforms=@llvm//:rbe_linux_x86_64

common:remote-cache --bes_results_url=https://app.buildbuddy.io/invocation/
common:remote-cache --bes_backend=grpcs://remote.buildbuddy.io
common:remote-cache --remote_header=x-buildbuddy-api-key=${BUILDBUDDY_API_KEY}
common:remote-cache --remote_cache=grpcs://remote.buildbuddy.io
common:remote-cache --remote_cache_compression
common:remote-cache --remote_timeout=600
common:remote-cache --remote_upload_local_results
EOF

emit_remote_var "--config=$EXPORT_CONFIG"
echo "Wrote $RC_PATH (configs: remote, remote-cache)."
