//! Machine-readable reporting and parity gating for MLX backend benchmarks.

use serde_json::{json, Value};

/// Benchmark model metadata needed by reporting and gating.
#[derive(Clone, Copy, Debug)]
pub struct BenchModel {
    pub display_name: &'static str,
    pub mlx_fixture_id: &'static str,
    pub gguf_fixture_id: &'static str,
    pub threshold_policy: ThresholdPolicy,
}

/// Whether a benchmark pair participates in the regression gate.
#[derive(Clone, Copy, Debug)]
pub enum ThresholdPolicy {
    Enforced,
    Informational(&'static str),
}

impl ThresholdPolicy {
    pub fn label(self) -> &'static str {
        match self {
            Self::Enforced => "enforced",
            Self::Informational(_) => "informational",
        }
    }

    pub fn is_enforced(self) -> bool {
        matches!(self, Self::Enforced)
    }

    fn informational_reason(self) -> Option<&'static str> {
        match self {
            Self::Enforced => None,
            Self::Informational(reason) => Some(reason),
        }
    }
}

/// One measured or skipped benchmark cell.
#[derive(Clone, Debug)]
pub struct CellResult {
    pub model: String,
    pub backend: String,
    pub fixture_id: String,
    pub threshold_policy: ThresholdPolicy,
    pub prompt_tps: Option<f32>,
    pub decode_tps: Option<f32>,
    pub ttft_ms: Option<f32>,
    pub peak_mem_mb: Option<f32>,
    pub status: CellStatus,
}

/// Completion state for a benchmark cell.
#[derive(Clone, Debug)]
pub enum CellStatus {
    Ok,
    Skipped(String),
    Failed(String),
}

impl CellStatus {
    pub fn label(&self) -> &'static str {
        match self {
            Self::Ok => "ok",
            Self::Skipped(_) => "skipped",
            Self::Failed(_) => "failed",
        }
    }

    pub fn detail(&self) -> Option<&str> {
        match self {
            Self::Ok => None,
            Self::Skipped(reason) | Self::Failed(reason) => Some(reason),
        }
    }
}

/// Render the benchmark report as a markdown table for humans.
pub fn render_markdown(
    models: &[BenchModel],
    results: &[CellResult],
    output_tokens: usize,
    rounds: usize,
    parity_floor: f32,
) -> String {
    let mut out = String::new();
    out.push_str("# LLM Backend Comparison — MLX vs llama.cpp\n\n");
    out.push_str(&format!(
        "Generated by `cargo bench -p xybrid-core --no-default-features \
         --features \"llm-mlx-runtime llm-llamacpp\" --bench llm_backend_compare`.\n\
         Host: `{}`. Output budget: {} tokens. Rounds: {} (round 0 discarded).\n\n",
        std::env::consts::OS,
        output_tokens,
        rounds,
    ));

    out.push_str("| model | backend | fixture | prompt-tokens/s | decode-tokens/s | ttft-ms | peak-mem-mb | gate | status |\n");
    out.push_str("|-------|---------|---------|-----------------|-----------------|---------|-------------|-----------|--------|\n");
    for cell in results {
        out.push_str(&format!(
            "| {} | {} | {} | {} | {} | {} | {} | {} | {} |\n",
            cell.model,
            cell.backend,
            cell.fixture_id,
            format_f32(cell.prompt_tps),
            format_f32(cell.decode_tps),
            format_f32(cell.ttft_ms),
            format_f32(cell.peak_mem_mb),
            cell.threshold_policy.label(),
            cell.status.label(),
        ));
    }
    out.push('\n');

    let notes: Vec<&CellResult> = results
        .iter()
        .filter(|c| !matches!(c.status, CellStatus::Ok))
        .collect();
    if !notes.is_empty() {
        out.push_str("## Notes\n\n");
        for cell in notes {
            let detail = match &cell.status {
                CellStatus::Skipped(s) => format!("skipped — {s}"),
                CellStatus::Failed(s) => format!("failed — {s}"),
                CellStatus::Ok => unreachable!(),
            };
            out.push_str(&format!(
                "- **{} / {}**: {}\n",
                cell.model, cell.backend, detail
            ));
        }
        out.push('\n');
    }

    let informational: Vec<&BenchModel> = models
        .iter()
        .filter(|model| !model.threshold_policy.is_enforced())
        .collect();
    if !informational.is_empty() {
        out.push_str("## Informational Pairs\n\n");
        for model in informational {
            let Some(reason) = model.threshold_policy.informational_reason() else {
                continue;
            };
            out.push_str(&format!(
                "- **{}**: MLX fixture `{}` vs llama.cpp fixture `{}`. {}\n",
                model.display_name, model.mlx_fixture_id, model.gguf_fixture_id, reason,
            ));
        }
        out.push('\n');
    }

    out.push_str(&format!(
        "## Parity Floor\n\nFor pairs marked `enforced`, MLX decode-tokens/s must be at least \
         `{parity_floor}x` the llama.cpp median for the same model. This is a regression floor, \
         not a speedup claim. Enforced pairs whose cells are skipped or failed also fail the gate.\n",
    ));

    out
}

/// Render the benchmark report as structured data for scripts.
pub fn render_json(
    models: &[BenchModel],
    results: &[CellResult],
    output_tokens: usize,
    rounds: usize,
) -> Value {
    json!({
        "schema_version": 1,
        "output_tokens": output_tokens,
        "rounds": rounds,
        "models": models.iter().map(model_json).collect::<Vec<_>>(),
        "cells": results.iter().map(cell_json).collect::<Vec<_>>(),
    })
}

/// Check all enforced benchmark pairs for completed cells and parity.
pub fn check_threshold(
    models: &[BenchModel],
    results: &[CellResult],
    parity_floor: f32,
) -> Result<(), Vec<String>> {
    let mut regressions = Vec::new();
    for model in models {
        if !model.threshold_policy.is_enforced() {
            continue;
        }

        let mlx = results
            .iter()
            .find(|c| c.model == model.display_name && c.backend == "mlx");
        let llama = results
            .iter()
            .find(|c| c.model == model.display_name && c.backend == "llama.cpp");
        let Some(mlx_cell) = mlx else {
            regressions.push(format!(
                "{}: missing enforced MLX measurement",
                model.display_name
            ));
            continue;
        };
        let Some(llama_cell) = llama else {
            regressions.push(format!(
                "{}: missing enforced llama.cpp measurement",
                model.display_name
            ));
            continue;
        };

        let mlx_tps = match enforced_decode_tps(mlx_cell) {
            Ok(v) => v,
            Err(reason) => {
                regressions.push(format!("{}: MLX {reason}", model.display_name));
                continue;
            }
        };
        let llama_tps = match enforced_decode_tps(llama_cell) {
            Ok(v) => v,
            Err(reason) => {
                regressions.push(format!("{}: llama.cpp {reason}", model.display_name));
                continue;
            }
        };
        let ratio = mlx_tps / llama_tps;
        if ratio < parity_floor {
            regressions.push(format!(
                "{}: MLX decode-tps {:.2} / llama.cpp {:.2} = {:.2}x < {:.2}x parity floor",
                model.display_name, mlx_tps, llama_tps, ratio, parity_floor,
            ));
        }
    }
    if regressions.is_empty() {
        Ok(())
    } else {
        Err(regressions)
    }
}

fn enforced_decode_tps(cell: &CellResult) -> Result<f32, String> {
    match (&cell.status, cell.decode_tps) {
        (CellStatus::Ok, Some(v)) => Ok(v),
        (CellStatus::Ok, None) => Err("completed without decode-tps".into()),
        (CellStatus::Skipped(reason), _) => Err(format!("skipped: {reason}")),
        (CellStatus::Failed(reason), _) => Err(format!("failed: {reason}")),
    }
}

fn format_f32(opt: Option<f32>) -> String {
    opt.map(|v| format!("{v:.1}")).unwrap_or_else(|| "—".into())
}

fn model_json(model: &BenchModel) -> Value {
    json!({
        "model": model.display_name,
        "mlx_fixture": model.mlx_fixture_id,
        "llama_cpp_fixture": model.gguf_fixture_id,
        "gate": model.threshold_policy.label(),
        "informational_reason": model.threshold_policy.informational_reason(),
    })
}

fn cell_json(cell: &CellResult) -> Value {
    json!({
        "model": cell.model,
        "backend": cell.backend,
        "fixture": cell.fixture_id,
        "gate": cell.threshold_policy.label(),
        "prompt_tps": cell.prompt_tps,
        "decode_tps": cell.decode_tps,
        "ttft_ms": cell.ttft_ms,
        "peak_mem_mb": cell.peak_mem_mb,
        "status": cell.status.label(),
        "status_detail": cell.status.detail(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cell(
        model: &str,
        backend: &str,
        threshold_policy: ThresholdPolicy,
        decode_tps: Option<f32>,
        status: CellStatus,
    ) -> CellResult {
        CellResult {
            model: model.into(),
            backend: backend.into(),
            fixture_id: format!("{model}-{backend}"),
            threshold_policy,
            prompt_tps: Some(10.0),
            decode_tps,
            ttft_ms: Some(20.0),
            peak_mem_mb: Some(1024.0),
            status,
        }
    }

    fn enforced_qwen() -> BenchModel {
        BenchModel {
            display_name: "qwen3-4b",
            mlx_fixture_id: "qwen3-4b-mlx",
            gguf_fixture_id: "qwen3-4b-bf16-gguf",
            threshold_policy: ThresholdPolicy::Enforced,
        }
    }

    #[test]
    fn threshold_check_rejects_missing_enforced_measurements() {
        let err = check_threshold(&[enforced_qwen()], &[], 0.95).unwrap_err();

        assert!(
            err.iter()
                .any(|msg| msg.contains("qwen3-4b") && msg.contains("missing")),
            "expected missing enforced pair error, got {err:?}"
        );
    }

    #[test]
    fn threshold_check_rejects_failed_enforced_cell() {
        let results = vec![
            cell(
                "qwen3-4b",
                "mlx",
                ThresholdPolicy::Enforced,
                None,
                CellStatus::Failed("load failed".into()),
            ),
            cell(
                "qwen3-4b",
                "llama.cpp",
                ThresholdPolicy::Enforced,
                Some(50.0),
                CellStatus::Ok,
            ),
        ];

        let err = check_threshold(&[enforced_qwen()], &results, 0.95).unwrap_err();

        assert!(
            err.iter()
                .any(|msg| msg.contains("qwen3-4b") && msg.contains("load failed")),
            "expected failed enforced cell error, got {err:?}"
        );
    }

    #[test]
    fn json_report_contains_machine_readable_cells() {
        let results = vec![cell(
            "qwen3-4b",
            "mlx",
            ThresholdPolicy::Enforced,
            Some(42.0),
            CellStatus::Ok,
        )];

        let json = render_json(&[enforced_qwen()], &results, 128, 5);

        assert_eq!(json["schema_version"], 1);
        assert_eq!(json["output_tokens"], 128);
        assert_eq!(json["rounds"], 5);
        assert_eq!(json["cells"][0]["model"], "qwen3-4b");
        assert_eq!(json["cells"][0]["backend"], "mlx");
        assert_eq!(json["cells"][0]["decode_tps"], 42.0);
        assert_eq!(json["cells"][0]["gate"], "enforced");
        assert_eq!(json["cells"][0]["status"], "ok");
    }
}
