# Wav2Vec2 ASR Test Pipeline
# Audio Input -> ASR -> Text Output

stages:
  - wav2vec2-base-960h
  # Complete version:
  # - id: asr
  #   model: wav2vec2-base-960h
  #   version: "1.0"
  #   target: device
