# Wav2vec2 Single-Stage Pipeline Configuration
# Tests: Audio Input -> ASR -> Text Output

name: "Wav2vec2 ASR Test"

stages:
  - "wav2vec2-base-960h@1.0"    # ASR model - must match registry

input:
  kind: "Audio"

metrics:
  network_rtt: 50         # Fast network
  battery: 80             # Good battery
  temperature: 24.0       # Normal temperature

availability:
  "wav2vec2-base-960h@1.0": true   # Available locally
