include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - cargokit/build_tool/**
    - lib/src/rust/**
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - unawaited_futures
    - cancel_subscriptions
