# Voice Assistant: Wav2Vec2 + OpenAI + Kokoro
# ASR (device) -> LLM (cloud) -> TTS (device)

name: va-wav2vec2-openai-kokoro

stages:
  - wav2vec2-base-960h
    # Complete version:
    # id: asr
    # model: wav2vec2-base-960h
    # version: "1.0"
    # target: device

  - model: gpt-4o-mini
    target: cloud
    provider: openai
    system_prompt: "You are a helpful voice assistant. Keep responses concise."
    max_tokens: 150
    temperature: 0.7
    # Complete version adds: id: llm

  - kokoro-82m
    # Complete version:
    # id: tts
    # model: kokoro-82m
    # version: "1.0"
    # target: device
