// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by flutter_rust_bridge_codegen
// See: https://cjycode.com/flutter_rust_bridge/

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'envelope.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `fmt`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FfiConversationContext>>
abstract class FfiConversationContext implements RustOpaqueInterface {
  /// Clear the conversation history but preserve the system prompt and ID.
  void clear();

  /// Create a new conversation context with a generated UUID.
  static FfiConversationContext create() =>
      XybridRustLib.instance.api.crateApiContextFfiConversationContextCreate();

  /// Check if a system prompt is set.
  bool hasSystem();

  /// Get the current history length (excluding system prompt).
  int historyLen();

  /// Get the conversation ID.
  String id();

  /// Get the maximum history length.
  int maxHistoryLen();

  /// Add a message to the conversation history.
  ///
  /// The envelope should have a role set via `with_role()`.
  void push({required FfiEnvelope envelope});

  /// Add a text message with a specific role.
  ///
  /// Convenience method that creates an envelope with the given role.
  void pushText({required String text, required FfiMessageRole role});

  /// Set the maximum history length before FIFO pruning.
  ///
  /// Default is 50 messages.
  void setMaxHistoryLen({required int len});

  /// Set the system prompt for this conversation.
  ///
  /// The system prompt defines the assistant's behavior and persists
  /// across `clear()` calls.
  void setSystem({required String text});

  /// Create a new conversation context with a specific ID.
  ///
  /// Useful for resuming conversations or tracking sessions.
  static FfiConversationContext withId({required String id}) => XybridRustLib
      .instance
      .api
      .crateApiContextFfiConversationContextWithId(id: id);
}

/// Message role for conversation turns.
enum FfiMessageRole {
  /// System prompt that defines assistant behavior.
  system,

  /// User message.
  user,

  /// Assistant response.
  assistant,
}
