// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by flutter_rust_bridge_codegen
// See: https://cjycode.com/flutter_rust_bridge/

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `init_sdk_cache_dir`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<XybridSdkClient>>
abstract class XybridSdkClient implements RustOpaqueInterface {
  static void setApiKey({required String apiKey}) => XybridRustLib.instance.api
      .crateApiSdkClientXybridSdkClientSetApiKey(apiKey: apiKey);
}
