// Auto-generated by BoltFFI. Do not edit.
@file:Suppress("unused", "RedundantVisibilityModifier", "MemberVisibilityCanBePrivate", "PropertyName", "FunctionName", "ClassName", "LocalVariableName", "SpellCheckingInspection", "NOTHING_TO_INLINE", "KotlinRedundantDiagnosticSuppress")

package ai.xybrid

import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicLong
import kotlin.jvm.JvmInline
import java.time.Duration
import java.time.Instant
import java.util.UUID
import java.net.URI

class FfiException(val code: Int, message: String) : Exception(message)

private fun takeLastErrorMessage(): String =
    Native.boltffi_last_error_message().toString(Charsets.UTF_8)

private inline fun <T> useWireBytes(bytes: ByteArray, block: (java.nio.ByteBuffer) -> T): T {
    return block(java.nio.ByteBuffer.wrap(bytes).order(java.nio.ByteOrder.LITTLE_ENDIAN))
}

interface WireCodable {
    fun encode(writer: WireWriter)

    interface Decoder<T> {
        fun decode(reader: WireReader): T
    }
}

class WireReader {
    private val array: ByteArray?
    private val buffer: ByteBuffer?
    private var pos: Int = 0

    constructor(array: ByteArray) {
        this.array = array
        this.buffer = null
    }

    constructor(buffer: ByteBuffer) {
        this.array = null
        this.buffer = buffer.slice().order(ByteOrder.LITTLE_ENDIAN)
    }

    private fun byteAt(index: Int): Byte = array?.get(index) ?: buffer!!.get(index)

    private fun copyRange(start: Int, len: Int): ByteArray {
        val localArray = array
        if (localArray != null) {
            return localArray.copyOfRange(start, start + len)
        }
        val bytes = ByteArray(len)
        if (len == 0) return bytes
        val source = buffer!!.duplicate().order(ByteOrder.LITTLE_ENDIAN)
        source.position(start)
        source.limit(start + len)
        source.get(bytes)
        return bytes
    }

    @PublishedApi internal fun leI16(o: Int): Short {
        val localArray = array
        return if (localArray != null) {
            ((localArray[o].toInt() and 0xFF) or ((localArray[o + 1].toInt() and 0xFF) shl 8)).toShort()
        } else {
            buffer!!.getShort(o)
        }
    }

    @PublishedApi internal fun leI32(o: Int): Int {
        val localArray = array
        return if (localArray != null) {
            (localArray[o].toInt() and 0xFF) or
            ((localArray[o + 1].toInt() and 0xFF) shl 8) or
            ((localArray[o + 2].toInt() and 0xFF) shl 16) or
            ((localArray[o + 3].toInt() and 0xFF) shl 24)
        } else {
            buffer!!.getInt(o)
        }
    }

    @PublishedApi internal fun leI64(o: Int): Long {
        val localArray = array
        return if (localArray != null) {
            (localArray[o].toLong() and 0xFFL) or
            ((localArray[o + 1].toLong() and 0xFFL) shl 8) or
            ((localArray[o + 2].toLong() and 0xFFL) shl 16) or
            ((localArray[o + 3].toLong() and 0xFFL) shl 24) or
            ((localArray[o + 4].toLong() and 0xFFL) shl 32) or
            ((localArray[o + 5].toLong() and 0xFFL) shl 40) or
            ((localArray[o + 6].toLong() and 0xFFL) shl 48) or
            ((localArray[o + 7].toLong() and 0xFFL) shl 56)
        } else {
            buffer!!.getLong(o)
        }
    }

    fun readBool(): Boolean { val v = byteAt(pos) != 0.toByte(); pos += 1; return v }
    fun readI8(): Byte { val v = byteAt(pos); pos += 1; return v }
    fun readU8(): UByte { val v = byteAt(pos).toUByte(); pos += 1; return v }
    fun readI16(): Short { val v = leI16(pos); pos += 2; return v }
    fun readU16(): UShort { val v = leI16(pos).toUShort(); pos += 2; return v }
    fun readI32(): Int { val v = leI32(pos); pos += 4; return v }
    fun readU32(): UInt { val v = leI32(pos).toUInt(); pos += 4; return v }
    fun readI64(): Long { val v = leI64(pos); pos += 8; return v }
    fun readU64(): ULong { val v = leI64(pos).toULong(); pos += 8; return v }
    fun readF32(): Float { val v = Float.fromBits(leI32(pos)); pos += 4; return v }
    fun readF64(): Double { val v = Double.fromBits(leI64(pos)); pos += 8; return v }

    fun readString(): String {
        val len = leI32(pos).toUInt().toInt()
        pos += 4
        if (len == 0) return ""
        val start = pos
        pos += len
        val localArray = array
        return if (localArray != null) {
            String(localArray, start, len, Charsets.UTF_8)
        } else {
            String(copyRange(start, len), Charsets.UTF_8)
        }
    }

    fun readBytes(): ByteArray {
        val len = leI32(pos).toUInt().toInt()
        pos += 4
        if (len == 0) return ByteArray(0)
        val start = pos
        pos += len
        return copyRange(start, len)
    }

    fun readDuration(): Duration {
        val seconds = readI64()
        val nanos = readI32().toLong()
        require(seconds >= 0L) { "Duration out of range" }
        require(nanos >= 0L) { "Duration nanos out of range" }
        return Duration.ofSeconds(seconds, nanos)
    }

    fun readInstant(): Instant {
        val seconds = readI64()
        val nanos = readI32().toLong()
        require(nanos >= 0L) { "Instant nanos out of range" }
        if (seconds >= 0L) {
            return Instant.EPOCH.plus(Duration.ofSeconds(seconds, nanos))
        }
        require(seconds != Long.MIN_VALUE) { "Instant out of range" }
        return Instant.EPOCH.minus(Duration.ofSeconds(-seconds, nanos))
    }

    fun readUuid(): UUID = UUID(readI64(), readI64())

    fun readUri(): URI = URI.create(readString())

    inline fun <T> readOptional(reader: (WireReader) -> T): T? {
        val tag = readU8().toInt()
        return if (tag == 0) null else reader(this)
    }

    inline fun <T> readList(reader: (WireReader) -> T): List<T> {
        val count = readI32().toUInt().toInt()
        if (count == 0) return emptyList()
        return ArrayList<T>(count).also { list -> repeat(count) { list.add(reader(this)) } }
    }

    inline fun <T, E> readResult(okReader: (WireReader) -> T, errReader: (WireReader) -> E): BoltFFIResult<T, E> {
        val tag = readU8().toInt()
        return if (tag == 0) BoltFFIResult.Ok(okReader(this)) else BoltFFIResult.Err(errReader(this))
    }

    fun readShortArray(): ShortArray {
        val count = readI32().toUInt().toInt()
        if (count == 0) return ShortArray(0)
        val base = pos
        pos += count * 2
        val localArray = array
        return if (localArray != null) {
            ShortArray(count) { i -> leI16(base + i * 2) }
        } else {
            val localBuffer = buffer!!
            ShortArray(count) { i -> localBuffer.getShort(base + i * 2) }
        }
    }

    fun readIntArray(): IntArray {
        val count = readI32().toUInt().toInt()
        if (count == 0) return IntArray(0)
        val base = pos
        pos += count * 4
        val localArray = array
        return if (localArray != null) {
            IntArray(count) { i -> leI32(base + i * 4) }
        } else {
            val localBuffer = buffer!!
            IntArray(count) { i -> localBuffer.getInt(base + i * 4) }
        }
    }

    fun readLongArray(): LongArray {
        val count = readI32().toUInt().toInt()
        if (count == 0) return LongArray(0)
        val base = pos
        pos += count * 8
        val localArray = array
        return if (localArray != null) {
            LongArray(count) { i -> leI64(base + i * 8) }
        } else {
            val localBuffer = buffer!!
            LongArray(count) { i -> localBuffer.getLong(base + i * 8) }
        }
    }

    fun readFloatArray(): FloatArray {
        val count = readI32().toUInt().toInt()
        if (count == 0) return FloatArray(0)
        val base = pos
        pos += count * 4
        val localArray = array
        return if (localArray != null) {
            FloatArray(count) { i -> Float.fromBits(leI32(base + i * 4)) }
        } else {
            val localBuffer = buffer!!
            FloatArray(count) { i -> localBuffer.getFloat(base + i * 4) }
        }
    }

    fun readDoubleArray(): DoubleArray {
        val count = readI32().toUInt().toInt()
        if (count == 0) return DoubleArray(0)
        val base = pos
        pos += count * 8
        val localArray = array
        return if (localArray != null) {
            DoubleArray(count) { i -> Double.fromBits(leI64(base + i * 8)) }
        } else {
            val localBuffer = buffer!!
            DoubleArray(count) { i -> localBuffer.getDouble(base + i * 8) }
        }
    }

    fun readBooleanArray(): BooleanArray {
        val count = readI32().toUInt().toInt()
        if (count == 0) return BooleanArray(0)
        val base = pos
        pos += count
        val localArray = array
        return if (localArray != null) {
            BooleanArray(count) { i -> localArray[base + i] != 0.toByte() }
        } else {
            val localBuffer = buffer!!
            BooleanArray(count) { i -> localBuffer.get(base + i) != 0.toByte() }
        }
    }

    fun skip(count: Int) { pos += count }

    fun readBlittable(sizeBytes: Int): ByteArray {
        val start = pos
        pos += sizeBytes
        return copyRange(start, sizeBytes)
    }
}

sealed class BoltFFIResult<out T, out E> {
    data class Ok<T>(val value: T) : BoltFFIResult<T, Nothing>()
    data class Err<E>(val error: E) : BoltFFIResult<Nothing, E>()

    val isSuccess: Boolean get() = this is Ok
    val isFailure: Boolean get() = this is Err

    fun getOrThrow(): T = when (this) {
        is Ok -> value
        is Err -> throw when (error) {
            is Throwable -> error
            else -> FfiException(-1, error.toString())
        }
    }

    fun getOrNull(): T? = when (this) {
        is Ok -> value
        is Err -> null
    }

    fun exceptionOrNull(): Throwable? = when (this) {
        is Ok -> null
        is Err -> when (error) {
            is Throwable -> error
            else -> FfiException(-1, error.toString())
        }
    }

    inline fun <R> fold(onSuccess: (T) -> R, onFailure: (E) -> R): R = when (this) {
        is Ok -> onSuccess(value)
        is Err -> onFailure(error)
    }
}

@Suppress("UNCHECKED_CAST")
internal fun <T> boltffiUnsafeCast(value: Any?): T = value as T

private object Utf8Codec {
    fun maxBytes(value: String): Int = value.length * 3
}

class WireWriter(initialCapacity: Int = 256) {
    private var buffer: ByteBuffer = ByteBuffer.allocateDirect(initialCapacity).order(ByteOrder.LITTLE_ENDIAN)
    private var pos: Int = 0

    internal fun reset(requiredCapacity: Int) {
        if (buffer.capacity() < requiredCapacity) {
            buffer = ByteBuffer.allocateDirect(requiredCapacity).order(ByteOrder.LITTLE_ENDIAN)
        }
        pos = 0
    }

    internal fun asDirectBuffer(): ByteBuffer {
        val view = buffer.duplicate().order(ByteOrder.LITTLE_ENDIAN)
        view.limit(pos)
        view.position(0)
        return view.slice().order(ByteOrder.LITTLE_ENDIAN)
    }

    internal fun toByteArray(): ByteArray {
        val arr = ByteArray(pos)
        val view = buffer.duplicate()
        view.position(0)
        view.get(arr, 0, pos)
        return arr
    }

    private fun ensureCapacity(needed: Int) {
        val required = pos + needed
        if (required <= buffer.capacity()) return
        val nextCapacity = maxOf(buffer.capacity() * 2, required)
        val next = ByteBuffer.allocateDirect(nextCapacity).order(ByteOrder.LITTLE_ENDIAN)
        val source = buffer.duplicate().order(ByteOrder.LITTLE_ENDIAN)
        source.limit(pos)
        source.position(0)
        next.put(source)
        buffer = next
    }

    internal inline fun writeRawBytes(byteCount: Int, writer: (ByteBuffer, Int) -> Unit) {
        ensureCapacity(byteCount)
        val baseOffset = pos
        writer(buffer, baseOffset)
        pos = baseOffset + byteCount
    }

    fun writeBool(v: Boolean) { ensureCapacity(1); buffer.put(pos, if (v) 1 else 0); pos += 1 }
    fun writePadding(count: Int) {
        ensureCapacity(count)
        val view = buffer.duplicate().order(ByteOrder.LITTLE_ENDIAN)
        view.position(pos)
        repeat(count) { view.put(0) }
        pos += count
    }
    fun writeI8(v: Byte) { ensureCapacity(1); buffer.put(pos, v); pos += 1 }
    fun writeU8(v: UByte) { ensureCapacity(1); buffer.put(pos, v.toByte()); pos += 1 }

    fun writeI16(v: Short) { ensureCapacity(2); buffer.putShort(pos, v); pos += 2 }
    fun writeU16(v: UShort) = writeI16(v.toShort())

    fun writeI32(v: Int) { ensureCapacity(4); buffer.putInt(pos, v); pos += 4 }
    fun writeU32(v: UInt) = writeI32(v.toInt())

    fun writeI64(v: Long) { ensureCapacity(8); buffer.putLong(pos, v); pos += 8 }
    fun writeU64(v: ULong) = writeI64(v.toLong())

    fun writeF32(v: Float) = writeI32(java.lang.Float.floatToRawIntBits(v))
    fun writeF64(v: Double) = writeI64(java.lang.Double.doubleToRawLongBits(v))

    fun writeDuration(v: Duration) {
        require(v.seconds >= 0L) { "Invalid duration, must be non-negative" }
        require(v.nano >= 0) { "Invalid duration nanos" }
        writeI64(v.seconds)
        writeI32(v.nano)
    }

    fun writeInstant(v: Instant) {
        var epochOffset = Duration.between(Instant.EPOCH, v)
        var sign = 1L
        if (epochOffset.isNegative) {
            sign = -1L
            epochOffset = epochOffset.negated()
        }
        require(epochOffset.nano >= 0) { "Invalid instant nanos" }
        writeI64(sign * epochOffset.seconds)
        writeI32(epochOffset.nano)
    }

    fun writeUuid(v: UUID) {
        writeI64(v.mostSignificantBits)
        writeI64(v.leastSignificantBits)
    }

    fun writeUri(v: URI) {
        writeString(v.toString())
    }

    fun writeString(v: String) {
        val bytes = v.toByteArray(Charsets.UTF_8)
        writeU32(bytes.size.toUInt())
        ensureCapacity(bytes.size)
        val view = buffer.duplicate().order(ByteOrder.LITTLE_ENDIAN)
        view.position(pos)
        view.put(bytes)
        pos += bytes.size
    }

    fun writeBytes(v: ByteArray) {
        writeU32(v.size.toUInt())
        ensureCapacity(v.size)
        val view = buffer.duplicate().order(ByteOrder.LITTLE_ENDIAN)
        view.position(pos)
        view.put(v)
        pos += v.size
    }

    fun writePrimitiveList(v: IntArray) {
        writeU32(v.size.toUInt())
        val bytes = v.size * 4
        writeRawBytes(bytes) { buf, baseOffset ->
            val view = buf.duplicate().order(ByteOrder.LITTLE_ENDIAN)
            view.position(baseOffset)
            view.limit(baseOffset + bytes)
            view.slice().order(ByteOrder.LITTLE_ENDIAN).asIntBuffer().put(v)
        }
    }

    fun writePrimitiveList(v: LongArray) {
        writeU32(v.size.toUInt())
        val bytes = v.size * 8
        writeRawBytes(bytes) { buf, baseOffset ->
            val view = buf.duplicate().order(ByteOrder.LITTLE_ENDIAN)
            view.position(baseOffset)
            view.limit(baseOffset + bytes)
            view.slice().order(ByteOrder.LITTLE_ENDIAN).asLongBuffer().put(v)
        }
    }

    fun writePrimitiveList(v: FloatArray) {
        writeU32(v.size.toUInt())
        val bytes = v.size * 4
        writeRawBytes(bytes) { buf, baseOffset ->
            val view = buf.duplicate().order(ByteOrder.LITTLE_ENDIAN)
            view.position(baseOffset)
            view.limit(baseOffset + bytes)
            view.slice().order(ByteOrder.LITTLE_ENDIAN).asFloatBuffer().put(v)
        }
    }

    fun writePrimitiveList(v: DoubleArray) {
        writeU32(v.size.toUInt())
        val bytes = v.size * 8
        writeRawBytes(bytes) { buf, baseOffset ->
            val view = buf.duplicate().order(ByteOrder.LITTLE_ENDIAN)
            view.position(baseOffset)
            view.limit(baseOffset + bytes)
            view.slice().order(ByteOrder.LITTLE_ENDIAN).asDoubleBuffer().put(v)
        }
    }

    fun writePrimitiveList(v: ShortArray) {
        writeU32(v.size.toUInt())
        val bytes = v.size * 2
        writeRawBytes(bytes) { buf, baseOffset ->
            val view = buf.duplicate().order(ByteOrder.LITTLE_ENDIAN)
            view.position(baseOffset)
            view.limit(baseOffset + bytes)
            view.slice().order(ByteOrder.LITTLE_ENDIAN).asShortBuffer().put(v)
        }
    }

    fun writePrimitiveList(v: ByteArray) {
        writeU32(v.size.toUInt())
        ensureCapacity(v.size)
        val view = buffer.duplicate().order(ByteOrder.LITTLE_ENDIAN)
        view.position(pos)
        view.put(v)
        pos += v.size
    }

    fun writePrimitiveList(v: BooleanArray) {
        writeU32(v.size.toUInt())
        v.forEach { writeBool(it) }
    }

    @JvmName("writeIntList")
    fun writePrimitiveList(v: List<Int>) {
        writeU32(v.size.toUInt())
        v.forEach { writeI32(it) }
    }

    @JvmName("writeLongList")
    fun writePrimitiveList(v: List<Long>) {
        writeU32(v.size.toUInt())
        v.forEach { writeI64(it) }
    }

    inline fun <reified T> writeBlittable(v: T) {
        when (v) {
            is Byte -> writeI8(v)
            is Short -> writeI16(v)
            is Int -> writeI32(v)
            is Long -> writeI64(v)
            is Float -> writeF32(v)
            is Double -> writeF64(v)
            is Boolean -> writeBool(v)
            else -> throw IllegalArgumentException("Cannot write blittable: ${T::class}")
        }
    }

    inline fun <reified T> writeBlittableList(v: List<T>) {
        writeU32(v.size.toUInt())
        v.forEach { item -> writeBlittable(item) }
    }
}

private const val MAX_CACHED_WIRE_WRITER_BYTES: Int = 1024 * 1024

internal class WireWriterPoolState(private val cacheSize: Int = 4) {
    private val cachedWriters: Array<WireWriter?> = arrayOfNulls(cacheSize)
    private var depth: Int = 0

    fun acquire(requiredCapacity: Int): BorrowedWireWriter {
        val slot = depth
        depth = slot + 1
        val shouldCache = requiredCapacity <= MAX_CACHED_WIRE_WRITER_BYTES && slot < cacheSize
        val writer = if (shouldCache) {
            cachedWriters[slot] ?: WireWriter(requiredCapacity).also { cachedWriters[slot] = it }
        } else {
            WireWriter(requiredCapacity)
        }

        writer.reset(requiredCapacity)
        return BorrowedWireWriter(this, writer)
    }

    fun release() {
        depth -= 1
    }
}

internal class BorrowedWireWriter(
    private val state: WireWriterPoolState,
    internal val writer: WireWriter
) : AutoCloseable {
    internal val buffer: ByteBuffer
        get() = writer.asDirectBuffer()

    override fun close() {
        state.release()
    }
}

internal object WireWriterPool {
    private val state: ThreadLocal<WireWriterPoolState> = ThreadLocal.withInitial { WireWriterPoolState() }

    fun acquire(requiredCapacity: Int): BorrowedWireWriter {
        val poolState = state.get() ?: WireWriterPoolState().also { state.set(it) }
        return poolState.acquire(requiredCapacity)
    }
}

/**
 * Errors surfaced across the FFI boundary. Variants mirror
 * [`facade::Error`] — the facade owns the SDK→FFI translation; this enum
 * only re-decorates it for the BoltFFI generator (proc macros must live
 * on the type definition).
 *
 * Named `XybridError` (not `Error`) so the emitted Swift type doesn't
 * shadow / collide with Swift's stdlib `Error` protocol, and so the
 * Kotlin sealed-hierarchy name matches the existing uniffi consumer
 * expectations.
 */
sealed class XybridError : Exception() {

    data class ModelNotFound(val id: String) : XybridError()

    data class DirectoryNotFound(val path: String) : XybridError()

    data class MetadataNotFound(val path: String) : XybridError()

    data class MetadataInvalid(override val message: String) : XybridError()

    data class LoadError(override val message: String) : XybridError()

    data class InferenceError(override val message: String) : XybridError()

    data class AbortedForCloudFallback(val reason: String) : XybridError()

    data object StreamingNotSupported : XybridError()

    data object NotLoaded : XybridError()

    data class ConfigError(override val message: String) : XybridError()

    data class NetworkError(override val message: String) : XybridError()

    data class Offline(override val message: String) : XybridError()

    data class IoError(override val message: String) : XybridError()

    data class CacheError(override val message: String) : XybridError()

    data class PipelineError(override val message: String) : XybridError()

    data class CircuitOpen(override val message: String) : XybridError()

    data class RateLimited(val retryAfterSecs: ULong) : XybridError()

    data class Timeout(val timeoutMs: ULong) : XybridError()

    companion object {
        fun decode(reader: WireReader): XybridError {
            val tag = reader.readI32()
            return when (tag) {
                0 -> {
                    ModelNotFound(
                        reader.readString()
                    )
                }
                1 -> {
                    DirectoryNotFound(
                        reader.readString()
                    )
                }
                2 -> {
                    MetadataNotFound(
                        reader.readString()
                    )
                }
                3 -> {
                    MetadataInvalid(
                        reader.readString()
                    )
                }
                4 -> {
                    LoadError(
                        reader.readString()
                    )
                }
                5 -> {
                    InferenceError(
                        reader.readString()
                    )
                }
                6 -> {
                    AbortedForCloudFallback(
                        reader.readString()
                    )
                }
                7 -> {
                    StreamingNotSupported
                }
                8 -> {
                    NotLoaded
                }
                9 -> {
                    ConfigError(
                        reader.readString()
                    )
                }
                10 -> {
                    NetworkError(
                        reader.readString()
                    )
                }
                11 -> {
                    Offline(
                        reader.readString()
                    )
                }
                12 -> {
                    IoError(
                        reader.readString()
                    )
                }
                13 -> {
                    CacheError(
                        reader.readString()
                    )
                }
                14 -> {
                    PipelineError(
                        reader.readString()
                    )
                }
                15 -> {
                    CircuitOpen(
                        reader.readString()
                    )
                }
                16 -> {
                    RateLimited(
                        reader.readU64()
                    )
                }
                17 -> {
                    Timeout(
                        reader.readU64()
                    )
                }
                else -> throw FfiException(-1, "Unknown XybridError tag: $tag")
            }
        }
    }

    fun wireEncodedSize(): Int = 4 + when (this) {
        is ModelNotFound -> (4 + Utf8Codec.maxBytes(id))
        is DirectoryNotFound -> (4 + Utf8Codec.maxBytes(path))
        is MetadataNotFound -> (4 + Utf8Codec.maxBytes(path))
        is MetadataInvalid -> (4 + Utf8Codec.maxBytes(message))
        is LoadError -> (4 + Utf8Codec.maxBytes(message))
        is InferenceError -> (4 + Utf8Codec.maxBytes(message))
        is AbortedForCloudFallback -> (4 + Utf8Codec.maxBytes(reason))
        is StreamingNotSupported -> 0
        is NotLoaded -> 0
        is ConfigError -> (4 + Utf8Codec.maxBytes(message))
        is NetworkError -> (4 + Utf8Codec.maxBytes(message))
        is Offline -> (4 + Utf8Codec.maxBytes(message))
        is IoError -> (4 + Utf8Codec.maxBytes(message))
        is CacheError -> (4 + Utf8Codec.maxBytes(message))
        is PipelineError -> (4 + Utf8Codec.maxBytes(message))
        is CircuitOpen -> (4 + Utf8Codec.maxBytes(message))
        is RateLimited -> 8
        is Timeout -> 8
    }

    fun wireEncodeTo(wire: WireWriter) {
        when (this) {
            is ModelNotFound -> {
                wire.writeI32(0)
                wire.writeString(id)
            }
            is DirectoryNotFound -> {
                wire.writeI32(1)
                wire.writeString(path)
            }
            is MetadataNotFound -> {
                wire.writeI32(2)
                wire.writeString(path)
            }
            is MetadataInvalid -> {
                wire.writeI32(3)
                wire.writeString(message)
            }
            is LoadError -> {
                wire.writeI32(4)
                wire.writeString(message)
            }
            is InferenceError -> {
                wire.writeI32(5)
                wire.writeString(message)
            }
            is AbortedForCloudFallback -> {
                wire.writeI32(6)
                wire.writeString(reason)
            }
            is StreamingNotSupported -> wire.writeI32(7)
            is NotLoaded -> wire.writeI32(8)
            is ConfigError -> {
                wire.writeI32(9)
                wire.writeString(message)
            }
            is NetworkError -> {
                wire.writeI32(10)
                wire.writeString(message)
            }
            is Offline -> {
                wire.writeI32(11)
                wire.writeString(message)
            }
            is IoError -> {
                wire.writeI32(12)
                wire.writeString(message)
            }
            is CacheError -> {
                wire.writeI32(13)
                wire.writeString(message)
            }
            is PipelineError -> {
                wire.writeI32(14)
                wire.writeString(message)
            }
            is CircuitOpen -> {
                wire.writeI32(15)
                wire.writeString(message)
            }
            is RateLimited -> {
                wire.writeI32(16)
                wire.writeU64(retryAfterSecs)
            }
            is Timeout -> {
                wire.writeI32(17)
                wire.writeU64(timeoutMs)
            }
        }
    }
}

sealed class XybridEnvelopeKind {

    data class Text(val text: String) : XybridEnvelopeKind()

    data class Audio(val bytes: ByteArray) : XybridEnvelopeKind()

    data class Embedding(val values: FloatArray) : XybridEnvelopeKind()

    companion object {
        fun decode(reader: WireReader): XybridEnvelopeKind {
            val tag = reader.readI32()
            return when (tag) {
                0 -> {
                    Text(
                        reader.readString()
                    )
                }
                1 -> {
                    Audio(
                        reader.readBytes()
                    )
                }
                2 -> {
                    Embedding(
                        reader.readFloatArray()
                    )
                }
                else -> throw FfiException(-1, "Unknown XybridEnvelopeKind tag: $tag")
            }
        }
    }

    fun wireEncodedSize(): Int = 4 + when (this) {
        is Text -> (4 + Utf8Codec.maxBytes(text))
        is Audio -> (4 + bytes.size)
        is Embedding -> (4 + values.size * 4)
    }

    fun wireEncodeTo(wire: WireWriter) {
        when (this) {
            is Text -> {
                wire.writeI32(0)
                wire.writeString(text)
            }
            is Audio -> {
                wire.writeI32(1)
                wire.writePrimitiveList(bytes)
            }
            is Embedding -> {
                wire.writeI32(2)
                wire.writePrimitiveList(values)
            }
        }
    }
}

enum class XybridMessageRole(val value: Int) {
    SYSTEM(0),
    USER(1),
    ASSISTANT(2);

    companion object {
        fun fromValue(value: Int): XybridMessageRole = entries.first { it.value == value }
        fun fromWireTag(tag: Int): XybridMessageRole = entries.getOrElse(tag) {
            throw FfiException(-1, "Unknown XybridMessageRole wire tag: $tag")
        }

        fun decode(reader: WireReader): XybridMessageRole = fromWireTag(reader.readI32())
    }

    fun wireTag(): Int = ordinal

    fun wireEncodeTo(wire: WireWriter) {
        wire.writeI32(wireTag())
    }
}

enum class XybridAbortSignal(val value: Int) {
    MEMORY_PRESSURE_WARN(0),
    MEMORY_PRESSURE_CRITICAL(1),
    THERMAL_HOT(2),
    THERMAL_CRITICAL(3);

    companion object {
        fun fromValue(value: Int): XybridAbortSignal = entries.first { it.value == value }
        fun fromWireTag(tag: Int): XybridAbortSignal = entries.getOrElse(tag) {
            throw FfiException(-1, "Unknown XybridAbortSignal wire tag: $tag")
        }

        fun decode(reader: WireReader): XybridAbortSignal = fromWireTag(reader.readI32())
    }

    fun wireTag(): Int = ordinal

    fun wireEncodeTo(wire: WireWriter) {
        wire.writeI32(wireTag())
    }
}

enum class XybridOutputType(val value: Int) {
    TEXT(0),
    AUDIO(1),
    EMBEDDING(2),
    UNKNOWN(3);

    companion object {
        fun fromValue(value: Int): XybridOutputType = entries.first { it.value == value }
        fun fromWireTag(tag: Int): XybridOutputType = entries.getOrElse(tag) {
            throw FfiException(-1, "Unknown XybridOutputType wire tag: $tag")
        }

        fun decode(reader: WireReader): XybridOutputType = fromWireTag(reader.readI32())
    }

    fun wireTag(): Int = ordinal

    fun wireEncodeTo(wire: WireWriter) {
        wire.writeI32(wireTag())
    }
}

enum class XybridThermalState(val value: Int) {
    NORMAL(0),
    WARM(1),
    HOT(2),
    CRITICAL(3);

    companion object {
        fun fromValue(value: Int): XybridThermalState = entries.first { it.value == value }
        fun fromWireTag(tag: Int): XybridThermalState = entries.getOrElse(tag) {
            throw FfiException(-1, "Unknown XybridThermalState wire tag: $tag")
        }

        fun decode(reader: WireReader): XybridThermalState = fromWireTag(reader.readI32())
    }

    fun wireTag(): Int = ordinal

    fun wireEncodeTo(wire: WireWriter) {
        wire.writeI32(wireTag())
    }
}

/**
 * Single metadata key/value entry. BoltFFI doesn't auto-derive
 * `WireEncode` for `HashMap<String, String>`, so we expose metadata as
 * `Vec<XybridMetadataEntry>`. The conversion back to `HashMap` happens
 * at the facade boundary inside [`XybridEnvelope::into`].
 */
data class XybridMetadataEntry(
    val key: String,
    val `value`: String
) {
    companion object {
        fun decode(reader: WireReader): XybridMetadataEntry = XybridMetadataEntry(
            reader.readString(),
            reader.readString()
        )
    }
    fun wireEncodedSize(): Int =
        (4 + Utf8Codec.maxBytes(key)) +
        (4 + Utf8Codec.maxBytes(`value`))

    fun wireEncodeTo(wire: WireWriter) {
        wire.writeString(key)
        wire.writeString(`value`)
    }
}

data class XybridEnvelope(
    val kind: XybridEnvelopeKind,
    val metadata: List<XybridMetadataEntry>
) {
    companion object {
        fun decode(reader: WireReader): XybridEnvelope = XybridEnvelope(
            XybridEnvelopeKind.decode(reader),
            reader.readList { XybridMetadataEntry.decode(reader) }
        )
    }
    fun wireEncodedSize(): Int =
        kind.wireEncodedSize() +
        (4 + metadata.sumOf { item -> item.wireEncodedSize() })

    fun wireEncodeTo(wire: WireWriter) {
        kind.wireEncodeTo(wire)
        wire.writeU32(metadata.size.toUInt()); metadata.forEach { item -> item.wireEncodeTo(wire) }
    }
}

data class XybridGenerationConfig(
    val maxTokens: UInt? = null,
    val temperature: Float? = null,
    val topP: Float? = null,
    val minP: Float? = null,
    val topK: UInt? = null,
    val repetitionPenalty: Float? = null,
    val stopSequences: List<String>
) {
    companion object {
        fun decode(reader: WireReader): XybridGenerationConfig = XybridGenerationConfig(
            reader.readOptional { reader.readU32() },
            reader.readOptional { reader.readF32() },
            reader.readOptional { reader.readF32() },
            reader.readOptional { reader.readF32() },
            reader.readOptional { reader.readU32() },
            reader.readOptional { reader.readF32() },
            reader.readList { reader.readString() }
        )
    }
    fun wireEncodedSize(): Int =
        (maxTokens?.let { v -> 1 + 4 } ?: 1.toInt()) +
        (temperature?.let { v -> 1 + 4 } ?: 1.toInt()) +
        (topP?.let { v -> 1 + 4 } ?: 1.toInt()) +
        (minP?.let { v -> 1 + 4 } ?: 1.toInt()) +
        (topK?.let { v -> 1 + 4 } ?: 1.toInt()) +
        (repetitionPenalty?.let { v -> 1 + 4 } ?: 1.toInt()) +
        (4 + stopSequences.sumOf { item -> (4 + Utf8Codec.maxBytes(item)) })

    fun wireEncodeTo(wire: WireWriter) {
        maxTokens?.let { v -> wire.writeU8(1u); wire.writeU32(v) } ?: wire.writeU8(0u)
        temperature?.let { v -> wire.writeU8(1u); wire.writeF32(v) } ?: wire.writeU8(0u)
        topP?.let { v -> wire.writeU8(1u); wire.writeF32(v) } ?: wire.writeU8(0u)
        minP?.let { v -> wire.writeU8(1u); wire.writeF32(v) } ?: wire.writeU8(0u)
        topK?.let { v -> wire.writeU8(1u); wire.writeU32(v) } ?: wire.writeU8(0u)
        repetitionPenalty?.let { v -> wire.writeU8(1u); wire.writeF32(v) } ?: wire.writeU8(0u)
        wire.writeU32(stopSequences.size.toUInt()); stopSequences.forEach { item -> wire.writeString(item) }
    }
}

data class XybridRunOptions(
    val generationConfig: XybridGenerationConfig? = null,
    val abortOn: List<XybridAbortSignal>,
    val fallbackToCloud: Boolean,
    val maxGraceTokens: UInt,
    val correlationId: String? = null
) {
    companion object {
        fun decode(reader: WireReader): XybridRunOptions = XybridRunOptions(
            reader.readOptional { XybridGenerationConfig.decode(reader) },
            reader.readList { XybridAbortSignal.decode(reader) },
            reader.readBool(),
            reader.readU32(),
            reader.readOptional { reader.readString() }
        )
    }
    fun wireEncodedSize(): Int =
        (generationConfig?.let { v -> 1 + v.wireEncodedSize() } ?: 1.toInt()) +
        (4 + abortOn.size * 4) +
        1 +
        4 +
        (correlationId?.let { v -> 1 + (4 + Utf8Codec.maxBytes(v)) } ?: 1.toInt())

    fun wireEncodeTo(wire: WireWriter) {
        generationConfig?.let { v -> wire.writeU8(1u); v.wireEncodeTo(wire) } ?: wire.writeU8(0u)
        wire.writeU32(abortOn.size.toUInt()); abortOn.forEach { item -> item.wireEncodeTo(wire) }
        wire.writeBool(fallbackToCloud)
        wire.writeU32(maxGraceTokens)
        correlationId?.let { v -> wire.writeU8(1u); wire.writeString(v) } ?: wire.writeU8(0u)
    }
}

data class XybridStageLatency(
    val stageId: String,
    val latencyMs: UInt
) {
    companion object {
        fun decode(reader: WireReader): XybridStageLatency = XybridStageLatency(
            reader.readString(),
            reader.readU32()
        )
    }
    fun wireEncodedSize(): Int =
        (4 + Utf8Codec.maxBytes(stageId)) +
        4

    fun wireEncodeTo(wire: WireWriter) {
        wire.writeString(stageId)
        wire.writeU32(latencyMs)
    }
}

data class XybridInferenceMetrics(
    val totalMs: UInt,
    val ttftMs: UInt? = null,
    val tokensPerSecond: Float? = null,
    val prefillTps: Float? = null,
    val decodeTps: Float? = null,
    val tokensOut: UInt? = null,
    val stageLatenciesMs: List<XybridStageLatency>
) {
    companion object {
        fun decode(reader: WireReader): XybridInferenceMetrics = XybridInferenceMetrics(
            reader.readU32(),
            reader.readOptional { reader.readU32() },
            reader.readOptional { reader.readF32() },
            reader.readOptional { reader.readF32() },
            reader.readOptional { reader.readF32() },
            reader.readOptional { reader.readU32() },
            reader.readList { XybridStageLatency.decode(reader) }
        )
    }
    fun wireEncodedSize(): Int =
        4 +
        (ttftMs?.let { v -> 1 + 4 } ?: 1.toInt()) +
        (tokensPerSecond?.let { v -> 1 + 4 } ?: 1.toInt()) +
        (prefillTps?.let { v -> 1 + 4 } ?: 1.toInt()) +
        (decodeTps?.let { v -> 1 + 4 } ?: 1.toInt()) +
        (tokensOut?.let { v -> 1 + 4 } ?: 1.toInt()) +
        (4 + stageLatenciesMs.sumOf { item -> item.wireEncodedSize() })

    fun wireEncodeTo(wire: WireWriter) {
        wire.writeU32(totalMs)
        ttftMs?.let { v -> wire.writeU8(1u); wire.writeU32(v) } ?: wire.writeU8(0u)
        tokensPerSecond?.let { v -> wire.writeU8(1u); wire.writeF32(v) } ?: wire.writeU8(0u)
        prefillTps?.let { v -> wire.writeU8(1u); wire.writeF32(v) } ?: wire.writeU8(0u)
        decodeTps?.let { v -> wire.writeU8(1u); wire.writeF32(v) } ?: wire.writeU8(0u)
        tokensOut?.let { v -> wire.writeU8(1u); wire.writeU32(v) } ?: wire.writeU8(0u)
        wire.writeU32(stageLatenciesMs.size.toUInt()); stageLatenciesMs.forEach { item -> item.wireEncodeTo(wire) }
    }
}

/**
 * Inference output. Named `XybridResult` (not `XybridInferenceResult`)
 * to match the existing uniffi-generated Kotlin/Swift name — the iOS
 * example references `XybridResult` directly.
 */
data class XybridResult(
    val envelope: XybridEnvelope,
    val outputType: XybridOutputType,
    val modelId: String,
    val latencyMs: UInt,
    val metrics: XybridInferenceMetrics
) {
    companion object {
        fun decode(reader: WireReader): XybridResult = XybridResult(
            XybridEnvelope.decode(reader),
            XybridOutputType.decode(reader),
            reader.readString(),
            reader.readU32(),
            XybridInferenceMetrics.decode(reader)
        )
    }
    fun wireEncodedSize(): Int =
        envelope.wireEncodedSize() +
        4 +
        (4 + Utf8Codec.maxBytes(modelId)) +
        4 +
        metrics.wireEncodedSize()

    fun wireEncodeTo(wire: WireWriter) {
        envelope.wireEncodeTo(wire)
        outputType.wireEncodeTo(wire)
        wire.writeString(modelId)
        wire.writeU32(latencyMs)
        metrics.wireEncodeTo(wire)
    }
}

data class XybridVoiceInfo(
    val id: String,
    val name: String,
    val gender: String? = null,
    val language: String? = null,
    val style: String? = null
) {
    companion object {
        fun decode(reader: WireReader): XybridVoiceInfo = XybridVoiceInfo(
            reader.readString(),
            reader.readString(),
            reader.readOptional { reader.readString() },
            reader.readOptional { reader.readString() },
            reader.readOptional { reader.readString() }
        )
    }
    fun wireEncodedSize(): Int =
        (4 + Utf8Codec.maxBytes(id)) +
        (4 + Utf8Codec.maxBytes(name)) +
        (gender?.let { v -> 1 + (4 + Utf8Codec.maxBytes(v)) } ?: 1.toInt()) +
        (language?.let { v -> 1 + (4 + Utf8Codec.maxBytes(v)) } ?: 1.toInt()) +
        (style?.let { v -> 1 + (4 + Utf8Codec.maxBytes(v)) } ?: 1.toInt())

    fun wireEncodeTo(wire: WireWriter) {
        wire.writeString(id)
        wire.writeString(name)
        gender?.let { v -> wire.writeU8(1u); wire.writeString(v) } ?: wire.writeU8(0u)
        language?.let { v -> wire.writeU8(1u); wire.writeString(v) } ?: wire.writeU8(0u)
        style?.let { v -> wire.writeU8(1u); wire.writeString(v) } ?: wire.writeU8(0u)
    }
}

fun setThermalState(state: XybridThermalState) {
    Native.boltffi_set_thermal_state(state.value)
}

fun clearThermalState() {
    Native.boltffi_clear_thermal_state()
}

fun setBatteryLevel(percent: UByte) {
    Native.boltffi_set_battery_level(percent.toByte())
}

fun clearBatteryLevel() {
    Native.boltffi_clear_battery_level()
}

/**
 * One-stop SDK initialization: API key + gateway/ingest URL overrides in
 * one call. Delegates to [`facade::configure_runtime`]; blank strings are
 * treated as absent. This is the canonical init the Swift
 * `Xybrid.initialize(apiKey:gatewayUrl:ingestUrl:)` and Kotlin
 * `Xybrid.init(context, apiKey, gatewayUrl, ingestUrl)` wrappers call.
 */

fun configureRuntime(apiKey: String?, gatewayUrl: String?, ingestUrl: String?) {
    val wire_writer_api_key = WireWriterPool.acquire((apiKey?.let { v -> 1 + (4 + Utf8Codec.maxBytes(v)) } ?: 1.toInt()))
        kotlin.run {
            val wire = wire_writer_api_key.writer
            apiKey?.let { v -> wire.writeU8(1u); wire.writeString(v) } ?: wire.writeU8(0u)
        }
    val wire_writer_gateway_url = WireWriterPool.acquire((gatewayUrl?.let { v -> 1 + (4 + Utf8Codec.maxBytes(v)) } ?: 1.toInt()))
        kotlin.run {
            val wire = wire_writer_gateway_url.writer
            gatewayUrl?.let { v -> wire.writeU8(1u); wire.writeString(v) } ?: wire.writeU8(0u)
        }
    val wire_writer_ingest_url = WireWriterPool.acquire((ingestUrl?.let { v -> 1 + (4 + Utf8Codec.maxBytes(v)) } ?: 1.toInt()))
        kotlin.run {
            val wire = wire_writer_ingest_url.writer
            ingestUrl?.let { v -> wire.writeU8(1u); wire.writeString(v) } ?: wire.writeU8(0u)
        }
    try {
        Native.boltffi_configure_runtime(wire_writer_api_key.buffer, wire_writer_gateway_url.buffer, wire_writer_ingest_url.buffer)
    } finally {
        wire_writer_api_key.close()
        wire_writer_gateway_url.close()
        wire_writer_ingest_url.close()
    }
}

fun initSdkCacheDir(cacheDir: String) {
    Native.boltffi_init_sdk_cache_dir(cacheDir.toByteArray(Charsets.UTF_8))
}

fun setBinding(binding: String) {
    Native.boltffi_set_binding(binding.toByteArray(Charsets.UTF_8))
}

fun setApiKey(apiKey: String) {
    Native.boltffi_set_api_key(apiKey.toByteArray(Charsets.UTF_8))
}

fun setProviderApiKey(provider: String, apiKey: String) {
    Native.boltffi_set_provider_api_key(provider.toByteArray(Charsets.UTF_8), apiKey.toByteArray(Charsets.UTF_8))
}

class XybridModel private constructor(internal val handle: Long) : AutoCloseable {
    private val closed = AtomicBoolean(false)

    /**
     * Load from the xybrid registry. Recommended path.
     */
    constructor(id: String) : this(
        kotlin.run {
            val handle = Native.boltffi_xybrid_model_from_registry(id.toByteArray(Charsets.UTF_8))
            if (handle == 0L) throw FfiException(1, takeLastErrorMessage())
            handle
        }
    )

    override fun close() {
        if (!closed.compareAndSet(false, true)) return
        Native.boltffi_xybrid_model_free(handle)
    }

    companion object {
        /**
         * Load from a local model directory (must contain `model_metadata.json`).
         */
        fun fromDirectory(path: String): XybridModel {
            val handle = Native.boltffi_xybrid_model_from_directory(path.toByteArray(Charsets.UTF_8))
            if (handle == 0L) throw FfiException(1, takeLastErrorMessage())
            return XybridModel(handle)
        }
        /**
         * Load from a local `.xyb` bundle.
         */
        fun fromBundle(path: String): XybridModel {
            val handle = Native.boltffi_xybrid_model_from_bundle(path.toByteArray(Charsets.UTF_8))
            if (handle == 0L) throw FfiException(1, takeLastErrorMessage())
            return XybridModel(handle)
        }
        /**
         * Resolve and load from a HuggingFace repo (`org/repo` or `org/repo:variant`).
         */
        fun fromHuggingface(repo: String): XybridModel {
            val handle = Native.boltffi_xybrid_model_from_huggingface(repo.toByteArray(Charsets.UTF_8))
            if (handle == 0L) throw FfiException(1, takeLastErrorMessage())
            return XybridModel(handle)
        }
    }


    fun modelId(): String {
        val result = Native.boltffi_xybrid_model_model_id(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        return result
    }


    fun version(): String {
        val result = Native.boltffi_xybrid_model_version(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        return result
    }


    fun outputType(): XybridOutputType {
        return Native.boltffi_xybrid_model_output_type(handle).let { XybridOutputType.fromValue(it) }
    }


    fun isLoaded(): Boolean {
        return Native.boltffi_xybrid_model_is_loaded(handle)
    }


    fun supportsStreaming(): Boolean {
        return Native.boltffi_xybrid_model_supports_streaming(handle)
    }


    fun isLlm(): Boolean {
        return Native.boltffi_xybrid_model_is_llm(handle)
    }


    fun hasVoices(): Boolean {
        return Native.boltffi_xybrid_model_has_voices(handle)
    }


    fun voices(): List<XybridVoiceInfo> {
        val buf = Native.boltffi_xybrid_model_voices(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readList { XybridVoiceInfo.decode(reader) }
    }


    fun defaultVoice(): XybridVoiceInfo? {
        val buf = Native.boltffi_xybrid_model_default_voice(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readOptional { XybridVoiceInfo.decode(reader) }
    }


    fun voice(voiceId: String): XybridVoiceInfo? {
        val buf = Native.boltffi_xybrid_model_voice(handle, voiceId.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readOptional { XybridVoiceInfo.decode(reader) }
    }


    @Throws(XybridError::class)
    fun run(envelope: XybridEnvelope): XybridResult {
        val wire_writer_envelope = WireWriterPool.acquire(envelope.wireEncodedSize())
            kotlin.run {
                val wire = wire_writer_envelope.writer
                envelope.wireEncodeTo(wire)
            }
        try {
            val buf = Native.boltffi_xybrid_model_run(handle, wire_writer_envelope.buffer)
                ?: throw FfiException(-1, "Null buffer returned")
            val reader = WireReader(buf)
            return reader.readResult({ XybridResult.decode(reader) }, { XybridError.decode(reader) }).getOrThrow()
        } finally {
            wire_writer_envelope.close()
        }
    }


    fun warmup() {
        Native.boltffi_xybrid_model_warmup(handle)
    }


    fun unload() {
        Native.boltffi_xybrid_model_unload(handle)
    }
}

@Suppress("FunctionName")
private object Native {
    init {
        val androidLibrary = "xybrid-bolt"
        val desktopPreferredLibrary = "xybrid_bolt_jni"
        val desktopFallbackLibrary = "xybrid_bolt"
        val vmName = System.getProperty("java.vm.name").orEmpty()
        val isAndroidRuntime =
            vmName.contains("dalvik", ignoreCase = true) ||
            vmName.contains("art", ignoreCase = true)
        if (isAndroidRuntime) {
            System.loadLibrary(androidLibrary)
        } else {
            loadDesktopLibraries(desktopPreferredLibrary, desktopFallbackLibrary)
        }
    }
    @Volatile
    private var bundledLibraryDirectory: java.io.File? = null

    private fun loadDesktopLibraries(preferredLibrary: String, fallbackLibrary: String) {
        var preferredFailure = tryLoadDesktopLibrary(preferredLibrary)
        if (preferredFailure == null) {
            return
        }

        if (tryLoadOptionalDesktopLibrary(fallbackLibrary)) {
            preferredFailure = tryLoadDesktopLibrary(preferredLibrary)
            if (preferredFailure == null) {
                return
            }
        }

        throw preferredFailure
    }

    private fun tryLoadDesktopLibrary(libraryName: String): UnsatisfiedLinkError? {
        try {
            if (loadBundledLibraryIfPresent(libraryName) || loadExternalLibraryIfPresent(libraryName)) {
                return null
            }
            return UnsatisfiedLinkError("Could not load native library '$libraryName'")
        } catch (error: UnsatisfiedLinkError) {
            return error
        }
    }

    private fun tryLoadOptionalDesktopLibrary(libraryName: String): Boolean {
        return try {
            loadBundledLibraryIfPresent(libraryName) || loadExternalLibraryIfPresent(libraryName)
        } catch (_: UnsatisfiedLinkError) {
            false
        }
    }

    private fun loadExternalLibraryIfPresent(libraryName: String): Boolean {
        return try {
            System.loadLibrary(libraryName)
            true
        } catch (_: UnsatisfiedLinkError) {
            false
        }
    }

    private fun loadBundledLibraryIfPresent(libraryName: String): Boolean {
        val mappedName = System.mapLibraryName(libraryName)
        for (resourcePath in bundledLibraryResourceCandidates(mappedName)) {
            Native::class.java.getResourceAsStream(resourcePath)?.use { input ->
                val extracted = extractBundledLibrary(resourcePath, input)
                System.load(extracted.absolutePath)
                return true
            }
        }
        return false
    }

    private fun extractBundledLibrary(
        resourcePath: String,
        input: java.io.InputStream,
    ): java.io.File {
        val fileName = resourcePath.substringAfterLast('/')
        val extracted = java.io.File(bundledLibraryDirectory(), fileName)
        if (!extracted.isFile) {
            java.io.FileOutputStream(extracted).use { output ->
                input.copyTo(output)
            }
            extracted.deleteOnExit()
        }
        return extracted
    }

    private fun bundledLibraryDirectory(): java.io.File {
        bundledLibraryDirectory?.let { return it }
        synchronized(this) {
            bundledLibraryDirectory?.let { return it }
            val created = java.io.File.createTempFile("boltffi-native-", "")
            if (!created.delete() || !created.mkdir()) {
                throw java.io.IOException("failed to create temp directory for bundled native extraction")
            }
            created.deleteOnExit()
            bundledLibraryDirectory = created
            return created
        }
    }

    private fun bundledLibraryResourceCandidates(mappedName: String): List<String> {
        val candidates = mutableListOf<String>()
        for (directory in desktopNativeDirectories()) {
            candidates += "/$directory/$mappedName"
            candidates += "/native/$directory/$mappedName"
        }
        candidates += "/$mappedName"
        return candidates
    }

    private fun desktopNativeDirectories(): List<String> {
        val osName = System.getProperty("os.name").orEmpty().lowercase()
        val osArch = System.getProperty("os.arch").orEmpty().lowercase()
        return when {
            (osName.contains("mac") || osName.contains("darwin")) &&
                (osArch == "aarch64" || osArch == "arm64") ->
                listOf("darwin-arm64", "darwin-aarch64")
            (osName.contains("mac") || osName.contains("darwin")) && osArch == "x86_64" ->
                listOf("darwin-x86_64", "darwin-x86-64")
            osName.contains("linux") && (osArch == "x86_64" || osArch == "amd64") ->
                listOf("linux-x86_64", "linux-x86-64")
            osName.contains("linux") && (osArch == "aarch64" || osArch == "arm64") ->
                listOf("linux-aarch64", "linux-arm64")
            osName.contains("windows") && (osArch == "x86_64" || osArch == "amd64") ->
                listOf("windows-x86_64", "windows-x86-64", "win32-x86_64")
            else -> emptyList()
        }
    }

    @JvmStatic external fun boltffi_free_string(ptr: Long)
    @JvmStatic external fun boltffi_last_error_message(): ByteArray
    @JvmStatic external fun boltffi_set_thermal_state(state: Int): Unit
    @JvmStatic external fun boltffi_clear_thermal_state(): Unit
    @JvmStatic external fun boltffi_set_battery_level(percent: Byte): Unit
    @JvmStatic external fun boltffi_clear_battery_level(): Unit
    @JvmStatic external fun boltffi_configure_runtime(api_key: ByteBuffer, gateway_url: ByteBuffer, ingest_url: ByteBuffer): Unit
    @JvmStatic external fun boltffi_init_sdk_cache_dir(cache_dir: ByteArray): Unit
    @JvmStatic external fun boltffi_set_binding(binding: ByteArray): Unit
    @JvmStatic external fun boltffi_set_api_key(api_key: ByteArray): Unit
    @JvmStatic external fun boltffi_set_provider_api_key(provider: ByteArray, api_key: ByteArray): Unit
    @JvmStatic external fun boltffi_xybrid_model_from_registry(id: ByteArray): Long
    @JvmStatic external fun boltffi_xybrid_model_from_directory(path: ByteArray): Long
    @JvmStatic external fun boltffi_xybrid_model_from_bundle(path: ByteArray): Long
    @JvmStatic external fun boltffi_xybrid_model_from_huggingface(repo: ByteArray): Long
    @JvmStatic external fun boltffi_xybrid_model_free(handle: Long)
    @JvmStatic external fun boltffi_xybrid_model_model_id(handle: Long): String?
    @JvmStatic external fun boltffi_xybrid_model_version(handle: Long): String?
    @JvmStatic external fun boltffi_xybrid_model_output_type(handle: Long): Int
    @JvmStatic external fun boltffi_xybrid_model_is_loaded(handle: Long): Boolean
    @JvmStatic external fun boltffi_xybrid_model_supports_streaming(handle: Long): Boolean
    @JvmStatic external fun boltffi_xybrid_model_is_llm(handle: Long): Boolean
    @JvmStatic external fun boltffi_xybrid_model_has_voices(handle: Long): Boolean
    @JvmStatic external fun boltffi_xybrid_model_voices(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_xybrid_model_default_voice(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_xybrid_model_voice(handle: Long, voice_id: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_xybrid_model_run(handle: Long, envelope: ByteBuffer): ByteArray?
    @JvmStatic external fun boltffi_xybrid_model_warmup(handle: Long): Unit
    @JvmStatic external fun boltffi_xybrid_model_unload(handle: Long): Unit
}
