// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by flutter_rust_bridge_codegen
// See: https://cjycode.com/flutter_rust_bridge/

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<XybridDevice>>
abstract class XybridDevice implements RustOpaqueInterface {
  /// Mark the battery level as unknown.
  ///
  /// Hosts call this on observer teardown or when the OS reports an
  /// unknown / unavailable charge (desktop docks without battery
  /// sensors). The routing engine treats `None` as "no signal" rather
  /// than substituting an optimistic default.
  static void clearBatteryLevel() =>
      XybridRustLib.instance.api.crateApiDeviceXybridDeviceClearBatteryLevel();

  /// Mark the thermal state as unknown.
  static void clearThermalState() =>
      XybridRustLib.instance.api.crateApiDeviceXybridDeviceClearThermalState();

  /// Read the routing-engine's current device snapshot.
  ///
  /// Returns whatever the global [`xybrid_sdk::ResourceMonitor`] last
  /// observed — battery + thermal from the platform pollers / host
  /// pushes, CPU + memory from sysinfo. Force-refreshes on every
  /// call (passes [`Duration::ZERO`]) so a diagnostics surface that
  /// polls at ~1 Hz sees fresh data each tick. The refresh cost is
  /// bounded; the contract is documented in `resource-telemetry.md`
  /// at `< 1 ms` on a warm monitor.
  ///
  /// Intended for app-side diagnostics views ("what does the routing
  /// engine see on this device right now?"). Production code should
  /// not poll this — the engine reads it internally on each routing
  /// decision.
  static FfiResourceSnapshot currentSnapshot() =>
      XybridRustLib.instance.api.crateApiDeviceXybridDeviceCurrentSnapshot();

  /// Forward a battery charge percent (0..=100) from the host.
  ///
  /// Values above 100 are clamped by the underlying setter — pass
  /// through whatever the OS observer reports without rounding host
  /// side, so the SDK has the freshest possible signal.
  static void setBatteryLevel({required int percent}) =>
      XybridRustLib.instance.api
          .crateApiDeviceXybridDeviceSetBatteryLevel(percent: percent);

  /// Forward a thermal pressure reading from the host.
  static void setThermalState({required FfiThermalState state}) =>
      XybridRustLib.instance.api
          .crateApiDeviceXybridDeviceSetThermalState(state: state);
}

/// Derived memory-pressure classification mirrored onto the FFI surface.
///
/// Maps directly to [`xybrid_sdk::MemoryPressure`]. `Unknown` means the
/// snapshot couldn't be computed (sysinfo refused to answer, or the
/// host hasn't pushed an iOS / Android memory-warning observer yet).
enum FfiMemoryPressure {
  unknown,
  normal,
  warn,
  critical,
  ;
}

/// Snapshot of routing-engine signals as the runtime currently sees them.
///
/// Field-for-field mirror of [`xybrid_sdk::ResourceSnapshot`]. `Option`
/// fields are `None` when the underlying sensor isn't available on the
/// running platform — a `None` here is what the routing engine reads as
/// "no signal," which downstream gates treat as "do not penalize."
class FfiResourceSnapshot {
  final double? cpuPct;
  final int? processRssMb;
  final int? availableMemMb;
  final int? totalMemMb;
  final FfiMemoryPressure memoryPressure;
  final FfiThermalState thermalState;
  final int? batteryPct;
  final BigInt capturedAtMs;

  const FfiResourceSnapshot({
    this.cpuPct,
    this.processRssMb,
    this.availableMemMb,
    this.totalMemMb,
    required this.memoryPressure,
    required this.thermalState,
    this.batteryPct,
    required this.capturedAtMs,
  });

  @override
  int get hashCode =>
      cpuPct.hashCode ^
      processRssMb.hashCode ^
      availableMemMb.hashCode ^
      totalMemMb.hashCode ^
      memoryPressure.hashCode ^
      thermalState.hashCode ^
      batteryPct.hashCode ^
      capturedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiResourceSnapshot &&
          runtimeType == other.runtimeType &&
          cpuPct == other.cpuPct &&
          processRssMb == other.processRssMb &&
          availableMemMb == other.availableMemMb &&
          totalMemMb == other.totalMemMb &&
          memoryPressure == other.memoryPressure &&
          thermalState == other.thermalState &&
          batteryPct == other.batteryPct &&
          capturedAtMs == other.capturedAtMs;
}

/// Thermal pressure state forwarded by the host.
///
/// Maps directly to [`xybrid_sdk::ThermalState`] — mirrored as an FRB
/// enum so Dart consumers see `FfiThermalState.normal | warm | hot |
/// critical`. Variants carry the same Celsius bands as the desktop
/// pollers so host code can quantize the OS signal consistently.
enum FfiThermalState {
  /// Normal operating temperature (< 60 °C).
  normal,

  /// Warm — first throttling tier (60–70 °C).
  warm,

  /// Hot — performance reduced (70–80 °C).
  hot,

  /// Critical — heavy operations should pause (>= 80 °C).
  critical,
  ;
}
