// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by flutter_rust_bridge_codegen
// See: https://cjycode.com/flutter_rust_bridge/

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<XybridSdkClient>>
abstract class XybridSdkClient implements RustOpaqueInterface {
  static void initSdkCacheDir({required String cacheDir}) =>
      XybridRustLib.instance.api
          .crateApiSdkClientXybridSdkClientInitSdkCacheDir(cacheDir: cacheDir);

  /// Initialize the platform telemetry exporter for this process.
  ///
  /// Starts the HTTP telemetry sender targeting `endpoint`, authenticated
  /// with `api_key`. Once initialized, the normal inference paths
  /// (`Xybrid.model().run()`, `Xybrid.pipeline().run()`, conversation
  /// turns, etc.) automatically emit `ExecutionStarted` /
  /// `ExecutionCompleted` / `ExecutionFailed` events through it — no
  /// per-call wiring required.
  ///
  /// Process-wide idempotent via [`TELEMETRY_INITIALIZED`]: only the
  /// first successful call enters `init_platform_telemetry`; subsequent
  /// calls (duplicate caller, second Dart isolate, Flutter hot-restart
  /// inside a surviving process) observe the guard and return without
  /// spawning a second exporter. No reconfigure path — restart the
  /// process to change endpoint/key.
  ///
  /// Sync because `init_platform_telemetry` is sync; the HTTP exporter
  /// spins up its own background thread for batched sends.
  static void initTelemetry(
          {required String endpoint, required String apiKey}) =>
      XybridRustLib.instance.api.crateApiSdkClientXybridSdkClientInitTelemetry(
          endpoint: endpoint, apiKey: apiKey);

  /// Check if a model is cached locally (extracted and ready to use).
  ///
  /// This is a pure filesystem check — no network access required.
  /// Returns `true` if the model has been downloaded and extracted
  /// at `~/.xybrid/cache/extracted/{model_id}/model_metadata.json`.
  static bool isModelCached({required String modelId}) =>
      XybridRustLib.instance.api
          .crateApiSdkClientXybridSdkClientIsModelCached(modelId: modelId);

  /// Whether [`Self::init_telemetry`] has run at least once in this
  /// process. Reflects the authoritative process-wide state, not any
  /// Dart-side flag — survives hot-restart, multiple isolates, etc.
  static bool isTelemetryInitialized() => XybridRustLib.instance.api
      .crateApiSdkClientXybridSdkClientIsTelemetryInitialized();

  static void setApiKey({required String apiKey}) => XybridRustLib.instance.api
      .crateApiSdkClientXybridSdkClientSetApiKey(apiKey: apiKey);
}
