// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by flutter_rust_bridge_codegen
// See: https://cjycode.com/flutter_rust_bridge/

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'streaming.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_logging`, `error_chain`, `spawn`, `to_sdk`, `worker_gone`, `worker_loop`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Command`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< FfiStreamSession>>
abstract class FfiStreamSession implements RustOpaqueInterface {
  /// Feed PCM f32 mono 16 kHz samples.
  ///
  /// A cheap, ordered, non-blocking channel send — inference happens on the
  /// worker thread. Takes an owned `Vec` because the samples are moved across
  /// the thread boundary; frb hands us an owned buffer already, so this adds
  /// no copy beyond the unavoidable cross-thread handoff.
  ///
  /// # Errors
  ///
  /// If the session has been finalized (after [`flush`]) or otherwise torn
  /// down, so the worker is no longer accepting audio.
  ///
  /// [`flush`]: Self::flush
  void feed({required List<double> samples});

  /// Finalize: drain buffered audio and return the complete transcript.
  ///
  /// After this the session is finalized; further [`feed`] calls error.
  ///
  /// # Errors
  ///
  /// If finalization fails in the core, or the worker is already gone.
  ///
  /// [`feed`]: Self::feed
  Future<String> flush();

  /// Reset the session to transcribe fresh audio without reloading the model.
  ///
  /// # Errors
  ///
  /// If the reset fails in the core, or the worker is already gone.
  Future<void> reset();

  /// Subscribe to partial transcripts. Call this once, before [`feed`].
  ///
  /// Partials are delivered on this sink as rolling-window chunks complete.
  /// Audio fed before the subscription is processed will not be reported.
  ///
  /// [`feed`]: Self::feed
  Stream<FfiPartialResult> subscribe();
}

/// A partial transcript emitted while audio is streaming.
class FfiPartialResult {
  /// Best-effort transcript text so far.
  final String text;

  /// `true` once this span is committed and will not change.
  final bool isStable;

  /// Monotonic chunk sequence number this result corresponds to.
  final BigInt chunkSequence;

  /// Audio covered so far, in milliseconds.
  final BigInt audioDurationMs;

  const FfiPartialResult({
    required this.text,
    required this.isStable,
    required this.chunkSequence,
    required this.audioDurationMs,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      isStable.hashCode ^
      chunkSequence.hashCode ^
      audioDurationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiPartialResult &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          isStable == other.isStable &&
          chunkSequence == other.chunkSequence &&
          audioDurationMs == other.audioDurationMs;
}

/// Configuration for a live ASR session.
///
/// The model itself is not named here — it comes from the loaded `FfiModel`
/// you call `stream` on. This only configures *how* the audio is chunked.
class FfiStreamingConfig {
  /// PCM sample rate of the audio you will feed. Must be 16 kHz; validated
  /// (and asserted as the contract) rather than forwarded — the backends are
  /// fixed at 16 kHz.
  final int sampleRate;

  /// Voice-activity-detection mode.
  final FfiVadMode vad;

  /// Optional language hint (e.g. `"en"`); `None` uses the model default.
  final String? language;

  /// Optional Whisper encoder context in mel frames; `None` uses the model default.
  final int? audioCtx;

  const FfiStreamingConfig({
    required this.sampleRate,
    required this.vad,
    this.language,
    this.audioCtx,
  });

  @override
  int get hashCode =>
      sampleRate.hashCode ^
      vad.hashCode ^
      language.hashCode ^
      audioCtx.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiStreamingConfig &&
          runtimeType == other.runtimeType &&
          sampleRate == other.sampleRate &&
          vad == other.vad &&
          language == other.language &&
          audioCtx == other.audioCtx;
}

@freezed
sealed class FfiVadMode with _$FfiVadMode {
  const FfiVadMode._();

  /// Fixed time-window chunking; no voice-activity detection.
  const factory FfiVadMode.off() = FfiVadMode_Off;

  /// VAD on, using the bundled default Silero model.
  const factory FfiVadMode.default_() = FfiVadMode_Default;

  /// VAD on, using a Silero model from this directory.
  const factory FfiVadMode.custom({
    /// Directory containing the VAD model.
    required String modelDir,
  }) = FfiVadMode_Custom;
}
